name: pgde

version: 0.0.1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  bot_toast:
  collection:
  email_validator:
  fixnum:
  grpc:
  intl:
  ip:
  protobuf:
  retry:

dev_dependencies:
  flutter_test:
    sdk: flutter
  args:
  intl_translation:
  test:

flutter:
  uses-material-design: true