package pgvt

import (
	"github.com/empirefox/protoc-gen-dart-ext/pkg/genshared"
)

const fileTpl = `{{ renderJoin . "fileHeader" "fileBody+1" }}`

const fileHeaderTpl = genshared.DartHead + `
/// Code generated by protoc-gen-dart-ext. DO NOT EDIT.
/// source: {{ .Pgs.InputPath }}
// ignore_for_file: non_constant_identifier_names,unnecessary_brace_in_string_interps,unused_local_variable

{{ .Validators.ImportManager.RenderImports }}
`

const fileBodyTpl = `
{{ range .Messages }}
	{{ if not .Validate.Disabled }}
		{{ template "msg" .Validate }}
	{{ end }}
{{ end }}
`
