// DO NOT EDIT. Generated by protoc-gen-dart-ext/tools.

import '../l10n/pgde.l10n.dart';
import 'currency_formats.dart';

abstract class _Valuer {
  String of(PgdeLocalization l);
}

class _XXX implements _Valuer {
  const _XXX();
  String of(PgdeLocalization l) => '';
}

class _ALL implements _Valuer {
  const _ALL();
  String of(PgdeLocalization l) => l.currencyAll;
}

class _DZD implements _Valuer {
  const _DZD();
  String of(PgdeLocalization l) => l.currencyDzd;
}

class _ARS implements _Valuer {
  const _ARS();
  String of(PgdeLocalization l) => l.currencyArs;
}

class _AUD implements _Valuer {
  const _AUD();
  String of(PgdeLocalization l) => l.currencyAud;
}

class _BSD implements _Valuer {
  const _BSD();
  String of(PgdeLocalization l) => l.currencyBsd;
}

class _BHD implements _Valuer {
  const _BHD();
  String of(PgdeLocalization l) => l.currencyBhd;
}

class _BDT implements _Valuer {
  const _BDT();
  String of(PgdeLocalization l) => l.currencyBdt;
}

class _AMD implements _Valuer {
  const _AMD();
  String of(PgdeLocalization l) => l.currencyAmd;
}

class _BBD implements _Valuer {
  const _BBD();
  String of(PgdeLocalization l) => l.currencyBbd;
}

class _BMD implements _Valuer {
  const _BMD();
  String of(PgdeLocalization l) => l.currencyBmd;
}

class _BTN implements _Valuer {
  const _BTN();
  String of(PgdeLocalization l) => l.currencyBtn;
}

class _BOB implements _Valuer {
  const _BOB();
  String of(PgdeLocalization l) => l.currencyBob;
}

class _BWP implements _Valuer {
  const _BWP();
  String of(PgdeLocalization l) => l.currencyBwp;
}

class _BZD implements _Valuer {
  const _BZD();
  String of(PgdeLocalization l) => l.currencyBzd;
}

class _SBD implements _Valuer {
  const _SBD();
  String of(PgdeLocalization l) => l.currencySbd;
}

class _BND implements _Valuer {
  const _BND();
  String of(PgdeLocalization l) => l.currencyBnd;
}

class _MMK implements _Valuer {
  const _MMK();
  String of(PgdeLocalization l) => l.currencyMmk;
}

class _BIF implements _Valuer {
  const _BIF();
  String of(PgdeLocalization l) => l.currencyBif;
}

class _KHR implements _Valuer {
  const _KHR();
  String of(PgdeLocalization l) => l.currencyKhr;
}

class _CAD implements _Valuer {
  const _CAD();
  String of(PgdeLocalization l) => l.currencyCad;
}

class _CVE implements _Valuer {
  const _CVE();
  String of(PgdeLocalization l) => l.currencyCve;
}

class _KYD implements _Valuer {
  const _KYD();
  String of(PgdeLocalization l) => l.currencyKyd;
}

class _LKR implements _Valuer {
  const _LKR();
  String of(PgdeLocalization l) => l.currencyLkr;
}

class _CLP implements _Valuer {
  const _CLP();
  String of(PgdeLocalization l) => l.currencyClp;
}

class _CNY implements _Valuer {
  const _CNY();
  String of(PgdeLocalization l) => l.currencyCny;
}

class _COP implements _Valuer {
  const _COP();
  String of(PgdeLocalization l) => l.currencyCop;
}

class _KMF implements _Valuer {
  const _KMF();
  String of(PgdeLocalization l) => l.currencyKmf;
}

class _CRC implements _Valuer {
  const _CRC();
  String of(PgdeLocalization l) => l.currencyCrc;
}

class _HRK implements _Valuer {
  const _HRK();
  String of(PgdeLocalization l) => l.currencyHrk;
}

class _CUP implements _Valuer {
  const _CUP();
  String of(PgdeLocalization l) => l.currencyCup;
}

class _CZK implements _Valuer {
  const _CZK();
  String of(PgdeLocalization l) => l.currencyCzk;
}

class _DKK implements _Valuer {
  const _DKK();
  String of(PgdeLocalization l) => l.currencyDkk;
}

class _DOP implements _Valuer {
  const _DOP();
  String of(PgdeLocalization l) => l.currencyDop;
}

class _SVC implements _Valuer {
  const _SVC();
  String of(PgdeLocalization l) => l.currencySvc;
}

class _ETB implements _Valuer {
  const _ETB();
  String of(PgdeLocalization l) => l.currencyEtb;
}

class _ERN implements _Valuer {
  const _ERN();
  String of(PgdeLocalization l) => l.currencyErn;
}

class _FKP implements _Valuer {
  const _FKP();
  String of(PgdeLocalization l) => l.currencyFkp;
}

class _FJD implements _Valuer {
  const _FJD();
  String of(PgdeLocalization l) => l.currencyFjd;
}

class _DJF implements _Valuer {
  const _DJF();
  String of(PgdeLocalization l) => l.currencyDjf;
}

class _GMD implements _Valuer {
  const _GMD();
  String of(PgdeLocalization l) => l.currencyGmd;
}

class _GIP implements _Valuer {
  const _GIP();
  String of(PgdeLocalization l) => l.currencyGip;
}

class _GTQ implements _Valuer {
  const _GTQ();
  String of(PgdeLocalization l) => l.currencyGtq;
}

class _GNF implements _Valuer {
  const _GNF();
  String of(PgdeLocalization l) => l.currencyGnf;
}

class _GYD implements _Valuer {
  const _GYD();
  String of(PgdeLocalization l) => l.currencyGyd;
}

class _HTG implements _Valuer {
  const _HTG();
  String of(PgdeLocalization l) => l.currencyHtg;
}

class _HNL implements _Valuer {
  const _HNL();
  String of(PgdeLocalization l) => l.currencyHnl;
}

class _HKD implements _Valuer {
  const _HKD();
  String of(PgdeLocalization l) => l.currencyHkd;
}

class _HUF implements _Valuer {
  const _HUF();
  String of(PgdeLocalization l) => l.currencyHuf;
}

class _ISK implements _Valuer {
  const _ISK();
  String of(PgdeLocalization l) => l.currencyIsk;
}

class _INR implements _Valuer {
  const _INR();
  String of(PgdeLocalization l) => l.currencyInr;
}

class _IDR implements _Valuer {
  const _IDR();
  String of(PgdeLocalization l) => l.currencyIdr;
}

class _IRR implements _Valuer {
  const _IRR();
  String of(PgdeLocalization l) => l.currencyIrr;
}

class _IQD implements _Valuer {
  const _IQD();
  String of(PgdeLocalization l) => l.currencyIqd;
}

class _ILS implements _Valuer {
  const _ILS();
  String of(PgdeLocalization l) => l.currencyIls;
}

class _JMD implements _Valuer {
  const _JMD();
  String of(PgdeLocalization l) => l.currencyJmd;
}

class _JPY implements _Valuer {
  const _JPY();
  String of(PgdeLocalization l) => l.currencyJpy;
}

class _KZT implements _Valuer {
  const _KZT();
  String of(PgdeLocalization l) => l.currencyKzt;
}

class _JOD implements _Valuer {
  const _JOD();
  String of(PgdeLocalization l) => l.currencyJod;
}

class _KES implements _Valuer {
  const _KES();
  String of(PgdeLocalization l) => l.currencyKes;
}

class _KPW implements _Valuer {
  const _KPW();
  String of(PgdeLocalization l) => l.currencyKpw;
}

class _KRW implements _Valuer {
  const _KRW();
  String of(PgdeLocalization l) => l.currencyKrw;
}

class _KWD implements _Valuer {
  const _KWD();
  String of(PgdeLocalization l) => l.currencyKwd;
}

class _KGS implements _Valuer {
  const _KGS();
  String of(PgdeLocalization l) => l.currencyKgs;
}

class _LAK implements _Valuer {
  const _LAK();
  String of(PgdeLocalization l) => l.currencyLak;
}

class _LBP implements _Valuer {
  const _LBP();
  String of(PgdeLocalization l) => l.currencyLbp;
}

class _LSL implements _Valuer {
  const _LSL();
  String of(PgdeLocalization l) => l.currencyLsl;
}

class _LRD implements _Valuer {
  const _LRD();
  String of(PgdeLocalization l) => l.currencyLrd;
}

class _LYD implements _Valuer {
  const _LYD();
  String of(PgdeLocalization l) => l.currencyLyd;
}

class _MOP implements _Valuer {
  const _MOP();
  String of(PgdeLocalization l) => l.currencyMop;
}

class _MWK implements _Valuer {
  const _MWK();
  String of(PgdeLocalization l) => l.currencyMwk;
}

class _MYR implements _Valuer {
  const _MYR();
  String of(PgdeLocalization l) => l.currencyMyr;
}

class _MVR implements _Valuer {
  const _MVR();
  String of(PgdeLocalization l) => l.currencyMvr;
}

class _MUR implements _Valuer {
  const _MUR();
  String of(PgdeLocalization l) => l.currencyMur;
}

class _MXN implements _Valuer {
  const _MXN();
  String of(PgdeLocalization l) => l.currencyMxn;
}

class _MNT implements _Valuer {
  const _MNT();
  String of(PgdeLocalization l) => l.currencyMnt;
}

class _MDL implements _Valuer {
  const _MDL();
  String of(PgdeLocalization l) => l.currencyMdl;
}

class _MAD implements _Valuer {
  const _MAD();
  String of(PgdeLocalization l) => l.currencyMad;
}

class _OMR implements _Valuer {
  const _OMR();
  String of(PgdeLocalization l) => l.currencyOmr;
}

class _NAD implements _Valuer {
  const _NAD();
  String of(PgdeLocalization l) => l.currencyNad;
}

class _NPR implements _Valuer {
  const _NPR();
  String of(PgdeLocalization l) => l.currencyNpr;
}

class _ANG implements _Valuer {
  const _ANG();
  String of(PgdeLocalization l) => l.currencyAng;
}

class _AWG implements _Valuer {
  const _AWG();
  String of(PgdeLocalization l) => l.currencyAwg;
}

class _VUV implements _Valuer {
  const _VUV();
  String of(PgdeLocalization l) => l.currencyVuv;
}

class _NZD implements _Valuer {
  const _NZD();
  String of(PgdeLocalization l) => l.currencyNzd;
}

class _NIO implements _Valuer {
  const _NIO();
  String of(PgdeLocalization l) => l.currencyNio;
}

class _NGN implements _Valuer {
  const _NGN();
  String of(PgdeLocalization l) => l.currencyNgn;
}

class _NOK implements _Valuer {
  const _NOK();
  String of(PgdeLocalization l) => l.currencyNok;
}

class _PKR implements _Valuer {
  const _PKR();
  String of(PgdeLocalization l) => l.currencyPkr;
}

class _PAB implements _Valuer {
  const _PAB();
  String of(PgdeLocalization l) => l.currencyPab;
}

class _PGK implements _Valuer {
  const _PGK();
  String of(PgdeLocalization l) => l.currencyPgk;
}

class _PYG implements _Valuer {
  const _PYG();
  String of(PgdeLocalization l) => l.currencyPyg;
}

class _PEN implements _Valuer {
  const _PEN();
  String of(PgdeLocalization l) => l.currencyPen;
}

class _PHP implements _Valuer {
  const _PHP();
  String of(PgdeLocalization l) => l.currencyPhp;
}

class _QAR implements _Valuer {
  const _QAR();
  String of(PgdeLocalization l) => l.currencyQar;
}

class _RUB implements _Valuer {
  const _RUB();
  String of(PgdeLocalization l) => l.currencyRub;
}

class _RWF implements _Valuer {
  const _RWF();
  String of(PgdeLocalization l) => l.currencyRwf;
}

class _SHP implements _Valuer {
  const _SHP();
  String of(PgdeLocalization l) => l.currencyShp;
}

class _SAR implements _Valuer {
  const _SAR();
  String of(PgdeLocalization l) => l.currencySar;
}

class _SCR implements _Valuer {
  const _SCR();
  String of(PgdeLocalization l) => l.currencyScr;
}

class _SLL implements _Valuer {
  const _SLL();
  String of(PgdeLocalization l) => l.currencySll;
}

class _SGD implements _Valuer {
  const _SGD();
  String of(PgdeLocalization l) => l.currencySgd;
}

class _VND implements _Valuer {
  const _VND();
  String of(PgdeLocalization l) => l.currencyVnd;
}

class _SOS implements _Valuer {
  const _SOS();
  String of(PgdeLocalization l) => l.currencySos;
}

class _ZAR implements _Valuer {
  const _ZAR();
  String of(PgdeLocalization l) => l.currencyZar;
}

class _SSP implements _Valuer {
  const _SSP();
  String of(PgdeLocalization l) => l.currencySsp;
}

class _SZL implements _Valuer {
  const _SZL();
  String of(PgdeLocalization l) => l.currencySzl;
}

class _SEK implements _Valuer {
  const _SEK();
  String of(PgdeLocalization l) => l.currencySek;
}

class _CHF implements _Valuer {
  const _CHF();
  String of(PgdeLocalization l) => l.currencyChf;
}

class _SYP implements _Valuer {
  const _SYP();
  String of(PgdeLocalization l) => l.currencySyp;
}

class _THB implements _Valuer {
  const _THB();
  String of(PgdeLocalization l) => l.currencyThb;
}

class _TOP implements _Valuer {
  const _TOP();
  String of(PgdeLocalization l) => l.currencyTop;
}

class _TTD implements _Valuer {
  const _TTD();
  String of(PgdeLocalization l) => l.currencyTtd;
}

class _AED implements _Valuer {
  const _AED();
  String of(PgdeLocalization l) => l.currencyAed;
}

class _TND implements _Valuer {
  const _TND();
  String of(PgdeLocalization l) => l.currencyTnd;
}

class _UGX implements _Valuer {
  const _UGX();
  String of(PgdeLocalization l) => l.currencyUgx;
}

class _MKD implements _Valuer {
  const _MKD();
  String of(PgdeLocalization l) => l.currencyMkd;
}

class _EGP implements _Valuer {
  const _EGP();
  String of(PgdeLocalization l) => l.currencyEgp;
}

class _GBP implements _Valuer {
  const _GBP();
  String of(PgdeLocalization l) => l.currencyGbp;
}

class _TZS implements _Valuer {
  const _TZS();
  String of(PgdeLocalization l) => l.currencyTzs;
}

class _USD implements _Valuer {
  const _USD();
  String of(PgdeLocalization l) => l.currencyUsd;
}

class _UYU implements _Valuer {
  const _UYU();
  String of(PgdeLocalization l) => l.currencyUyu;
}

class _UZS implements _Valuer {
  const _UZS();
  String of(PgdeLocalization l) => l.currencyUzs;
}

class _WST implements _Valuer {
  const _WST();
  String of(PgdeLocalization l) => l.currencyWst;
}

class _YER implements _Valuer {
  const _YER();
  String of(PgdeLocalization l) => l.currencyYer;
}

class _TWD implements _Valuer {
  const _TWD();
  String of(PgdeLocalization l) => l.currencyTwd;
}

class _UYW implements _Valuer {
  const _UYW();
  String of(PgdeLocalization l) => l.currencyUyw;
}

class _VES implements _Valuer {
  const _VES();
  String of(PgdeLocalization l) => l.currencyVes;
}

class _MRU implements _Valuer {
  const _MRU();
  String of(PgdeLocalization l) => l.currencyMru;
}

class _STN implements _Valuer {
  const _STN();
  String of(PgdeLocalization l) => l.currencyStn;
}

class _CUC implements _Valuer {
  const _CUC();
  String of(PgdeLocalization l) => l.currencyCuc;
}

class _ZWL implements _Valuer {
  const _ZWL();
  String of(PgdeLocalization l) => l.currencyZwl;
}

class _BYN implements _Valuer {
  const _BYN();
  String of(PgdeLocalization l) => l.currencyByn;
}

class _TMT implements _Valuer {
  const _TMT();
  String of(PgdeLocalization l) => l.currencyTmt;
}

class _GHS implements _Valuer {
  const _GHS();
  String of(PgdeLocalization l) => l.currencyGhs;
}

class _SDG implements _Valuer {
  const _SDG();
  String of(PgdeLocalization l) => l.currencySdg;
}

class _UYI implements _Valuer {
  const _UYI();
  String of(PgdeLocalization l) => l.currencyUyi;
}

class _RSD implements _Valuer {
  const _RSD();
  String of(PgdeLocalization l) => l.currencyRsd;
}

class _MZN implements _Valuer {
  const _MZN();
  String of(PgdeLocalization l) => l.currencyMzn;
}

class _AZN implements _Valuer {
  const _AZN();
  String of(PgdeLocalization l) => l.currencyAzn;
}

class _RON implements _Valuer {
  const _RON();
  String of(PgdeLocalization l) => l.currencyRon;
}

class _CHE implements _Valuer {
  const _CHE();
  String of(PgdeLocalization l) => l.currencyChe;
}

class _CHW implements _Valuer {
  const _CHW();
  String of(PgdeLocalization l) => l.currencyChw;
}

class _TRY implements _Valuer {
  const _TRY();
  String of(PgdeLocalization l) => l.currencyTry;
}

class _XAF implements _Valuer {
  const _XAF();
  String of(PgdeLocalization l) => l.currencyXaf;
}

class _XCD implements _Valuer {
  const _XCD();
  String of(PgdeLocalization l) => l.currencyXcd;
}

class _XOF implements _Valuer {
  const _XOF();
  String of(PgdeLocalization l) => l.currencyXof;
}

class _XPF implements _Valuer {
  const _XPF();
  String of(PgdeLocalization l) => l.currencyXpf;
}

class _XBA implements _Valuer {
  const _XBA();
  String of(PgdeLocalization l) => l.currencyXba;
}

class _XBB implements _Valuer {
  const _XBB();
  String of(PgdeLocalization l) => l.currencyXbb;
}

class _XBC implements _Valuer {
  const _XBC();
  String of(PgdeLocalization l) => l.currencyXbc;
}

class _XBD implements _Valuer {
  const _XBD();
  String of(PgdeLocalization l) => l.currencyXbd;
}

class _XAU implements _Valuer {
  const _XAU();
  String of(PgdeLocalization l) => l.currencyXau;
}

class _XDR implements _Valuer {
  const _XDR();
  String of(PgdeLocalization l) => l.currencyXdr;
}

class _XAG implements _Valuer {
  const _XAG();
  String of(PgdeLocalization l) => l.currencyXag;
}

class _XPT implements _Valuer {
  const _XPT();
  String of(PgdeLocalization l) => l.currencyXpt;
}

class _XTS implements _Valuer {
  const _XTS();
  String of(PgdeLocalization l) => l.currencyXts;
}

class _XPD implements _Valuer {
  const _XPD();
  String of(PgdeLocalization l) => l.currencyXpd;
}

class _XUA implements _Valuer {
  const _XUA();
  String of(PgdeLocalization l) => l.currencyXua;
}

class _ZMW implements _Valuer {
  const _ZMW();
  String of(PgdeLocalization l) => l.currencyZmw;
}

class _SRD implements _Valuer {
  const _SRD();
  String of(PgdeLocalization l) => l.currencySrd;
}

class _MGA implements _Valuer {
  const _MGA();
  String of(PgdeLocalization l) => l.currencyMga;
}

class _COU implements _Valuer {
  const _COU();
  String of(PgdeLocalization l) => l.currencyCou;
}

class _AFN implements _Valuer {
  const _AFN();
  String of(PgdeLocalization l) => l.currencyAfn;
}

class _TJS implements _Valuer {
  const _TJS();
  String of(PgdeLocalization l) => l.currencyTjs;
}

class _AOA implements _Valuer {
  const _AOA();
  String of(PgdeLocalization l) => l.currencyAoa;
}

class _BGN implements _Valuer {
  const _BGN();
  String of(PgdeLocalization l) => l.currencyBgn;
}

class _CDF implements _Valuer {
  const _CDF();
  String of(PgdeLocalization l) => l.currencyCdf;
}

class _BAM implements _Valuer {
  const _BAM();
  String of(PgdeLocalization l) => l.currencyBam;
}

class _EUR implements _Valuer {
  const _EUR();
  String of(PgdeLocalization l) => l.currencyEur;
}

class _MXV implements _Valuer {
  const _MXV();
  String of(PgdeLocalization l) => l.currencyMxv;
}

class _UAH implements _Valuer {
  const _UAH();
  String of(PgdeLocalization l) => l.currencyUah;
}

class _GEL implements _Valuer {
  const _GEL();
  String of(PgdeLocalization l) => l.currencyGel;
}

class _BOV implements _Valuer {
  const _BOV();
  String of(PgdeLocalization l) => l.currencyBov;
}

class _PLN implements _Valuer {
  const _PLN();
  String of(PgdeLocalization l) => l.currencyPln;
}

class _BRL implements _Valuer {
  const _BRL();
  String of(PgdeLocalization l) => l.currencyBrl;
}

class _CLF implements _Valuer {
  const _CLF();
  String of(PgdeLocalization l) => l.currencyClf;
}

class _XSU implements _Valuer {
  const _XSU();
  String of(PgdeLocalization l) => l.currencyXsu;
}

class _USN implements _Valuer {
  const _USN();
  String of(PgdeLocalization l) => l.currencyUsn;
}

class Currency {
  final String ccy;
  final int nbr;
  final int mnrFactor;
  final _Valuer _v;
  const Currency._(this.ccy, this.nbr, this.mnrFactor, this._v);
  String Function(dynamic) get format => getCurrencyFormat(ccy).format;
  String Function(dynamic) get formatSimple =>
      getSimpleCurrencyFormat(ccy).format;
  String Function(dynamic) get formatNumber =>
      getCurrencyNumberFormat(ccy).format;
  String formatName(v, PgdeLocalization l) => (l == null || _v.of(l) == null)
      ? format(v)
      : (formatNumber(v) + _v.of(l));
  String l10n(PgdeLocalization l10n) => l10n == null ? ccy : _v.of(l10n) ?? ccy;

  static const XXX = const Currency._('', 0, 0, const _XXX());
  static const ALL = const Currency._('ALL', 8, 100, const _ALL());
  static const DZD = const Currency._('DZD', 12, 100, const _DZD());
  static const ARS = const Currency._('ARS', 32, 100, const _ARS());
  static const AUD = const Currency._('AUD', 36, 100, const _AUD());
  static const BSD = const Currency._('BSD', 44, 100, const _BSD());
  static const BHD = const Currency._('BHD', 48, 1000, const _BHD());
  static const BDT = const Currency._('BDT', 50, 100, const _BDT());
  static const AMD = const Currency._('AMD', 51, 100, const _AMD());
  static const BBD = const Currency._('BBD', 52, 100, const _BBD());
  static const BMD = const Currency._('BMD', 60, 100, const _BMD());
  static const BTN = const Currency._('BTN', 64, 100, const _BTN());
  static const BOB = const Currency._('BOB', 68, 100, const _BOB());
  static const BWP = const Currency._('BWP', 72, 100, const _BWP());
  static const BZD = const Currency._('BZD', 84, 100, const _BZD());
  static const SBD = const Currency._('SBD', 90, 100, const _SBD());
  static const BND = const Currency._('BND', 96, 100, const _BND());
  static const MMK = const Currency._('MMK', 104, 100, const _MMK());
  static const BIF = const Currency._('BIF', 108, 1, const _BIF());
  static const KHR = const Currency._('KHR', 116, 100, const _KHR());
  static const CAD = const Currency._('CAD', 124, 100, const _CAD());
  static const CVE = const Currency._('CVE', 132, 100, const _CVE());
  static const KYD = const Currency._('KYD', 136, 100, const _KYD());
  static const LKR = const Currency._('LKR', 144, 100, const _LKR());
  static const CLP = const Currency._('CLP', 152, 1, const _CLP());
  static const CNY = const Currency._('CNY', 156, 100, const _CNY());
  static const COP = const Currency._('COP', 170, 100, const _COP());
  static const KMF = const Currency._('KMF', 174, 1, const _KMF());
  static const CRC = const Currency._('CRC', 188, 100, const _CRC());
  static const HRK = const Currency._('HRK', 191, 100, const _HRK());
  static const CUP = const Currency._('CUP', 192, 100, const _CUP());
  static const CZK = const Currency._('CZK', 203, 100, const _CZK());
  static const DKK = const Currency._('DKK', 208, 100, const _DKK());
  static const DOP = const Currency._('DOP', 214, 100, const _DOP());
  static const SVC = const Currency._('SVC', 222, 100, const _SVC());
  static const ETB = const Currency._('ETB', 230, 100, const _ETB());
  static const ERN = const Currency._('ERN', 232, 100, const _ERN());
  static const FKP = const Currency._('FKP', 238, 100, const _FKP());
  static const FJD = const Currency._('FJD', 242, 100, const _FJD());
  static const DJF = const Currency._('DJF', 262, 1, const _DJF());
  static const GMD = const Currency._('GMD', 270, 100, const _GMD());
  static const GIP = const Currency._('GIP', 292, 100, const _GIP());
  static const GTQ = const Currency._('GTQ', 320, 100, const _GTQ());
  static const GNF = const Currency._('GNF', 324, 1, const _GNF());
  static const GYD = const Currency._('GYD', 328, 100, const _GYD());
  static const HTG = const Currency._('HTG', 332, 100, const _HTG());
  static const HNL = const Currency._('HNL', 340, 100, const _HNL());
  static const HKD = const Currency._('HKD', 344, 100, const _HKD());
  static const HUF = const Currency._('HUF', 348, 100, const _HUF());
  static const ISK = const Currency._('ISK', 352, 1, const _ISK());
  static const INR = const Currency._('INR', 356, 100, const _INR());
  static const IDR = const Currency._('IDR', 360, 100, const _IDR());
  static const IRR = const Currency._('IRR', 364, 100, const _IRR());
  static const IQD = const Currency._('IQD', 368, 1000, const _IQD());
  static const ILS = const Currency._('ILS', 376, 100, const _ILS());
  static const JMD = const Currency._('JMD', 388, 100, const _JMD());
  static const JPY = const Currency._('JPY', 392, 1, const _JPY());
  static const KZT = const Currency._('KZT', 398, 100, const _KZT());
  static const JOD = const Currency._('JOD', 400, 1000, const _JOD());
  static const KES = const Currency._('KES', 404, 100, const _KES());
  static const KPW = const Currency._('KPW', 408, 100, const _KPW());
  static const KRW = const Currency._('KRW', 410, 1, const _KRW());
  static const KWD = const Currency._('KWD', 414, 1000, const _KWD());
  static const KGS = const Currency._('KGS', 417, 100, const _KGS());
  static const LAK = const Currency._('LAK', 418, 100, const _LAK());
  static const LBP = const Currency._('LBP', 422, 100, const _LBP());
  static const LSL = const Currency._('LSL', 426, 100, const _LSL());
  static const LRD = const Currency._('LRD', 430, 100, const _LRD());
  static const LYD = const Currency._('LYD', 434, 1000, const _LYD());
  static const MOP = const Currency._('MOP', 446, 100, const _MOP());
  static const MWK = const Currency._('MWK', 454, 100, const _MWK());
  static const MYR = const Currency._('MYR', 458, 100, const _MYR());
  static const MVR = const Currency._('MVR', 462, 100, const _MVR());
  static const MUR = const Currency._('MUR', 480, 100, const _MUR());
  static const MXN = const Currency._('MXN', 484, 100, const _MXN());
  static const MNT = const Currency._('MNT', 496, 100, const _MNT());
  static const MDL = const Currency._('MDL', 498, 100, const _MDL());
  static const MAD = const Currency._('MAD', 504, 100, const _MAD());
  static const OMR = const Currency._('OMR', 512, 1000, const _OMR());
  static const NAD = const Currency._('NAD', 516, 100, const _NAD());
  static const NPR = const Currency._('NPR', 524, 100, const _NPR());
  static const ANG = const Currency._('ANG', 532, 100, const _ANG());
  static const AWG = const Currency._('AWG', 533, 100, const _AWG());
  static const VUV = const Currency._('VUV', 548, 1, const _VUV());
  static const NZD = const Currency._('NZD', 554, 100, const _NZD());
  static const NIO = const Currency._('NIO', 558, 100, const _NIO());
  static const NGN = const Currency._('NGN', 566, 100, const _NGN());
  static const NOK = const Currency._('NOK', 578, 100, const _NOK());
  static const PKR = const Currency._('PKR', 586, 100, const _PKR());
  static const PAB = const Currency._('PAB', 590, 100, const _PAB());
  static const PGK = const Currency._('PGK', 598, 100, const _PGK());
  static const PYG = const Currency._('PYG', 600, 1, const _PYG());
  static const PEN = const Currency._('PEN', 604, 100, const _PEN());
  static const PHP = const Currency._('PHP', 608, 100, const _PHP());
  static const QAR = const Currency._('QAR', 634, 100, const _QAR());
  static const RUB = const Currency._('RUB', 643, 100, const _RUB());
  static const RWF = const Currency._('RWF', 646, 1, const _RWF());
  static const SHP = const Currency._('SHP', 654, 100, const _SHP());
  static const SAR = const Currency._('SAR', 682, 100, const _SAR());
  static const SCR = const Currency._('SCR', 690, 100, const _SCR());
  static const SLL = const Currency._('SLL', 694, 100, const _SLL());
  static const SGD = const Currency._('SGD', 702, 100, const _SGD());
  static const VND = const Currency._('VND', 704, 1, const _VND());
  static const SOS = const Currency._('SOS', 706, 100, const _SOS());
  static const ZAR = const Currency._('ZAR', 710, 100, const _ZAR());
  static const SSP = const Currency._('SSP', 728, 100, const _SSP());
  static const SZL = const Currency._('SZL', 748, 100, const _SZL());
  static const SEK = const Currency._('SEK', 752, 100, const _SEK());
  static const CHF = const Currency._('CHF', 756, 100, const _CHF());
  static const SYP = const Currency._('SYP', 760, 100, const _SYP());
  static const THB = const Currency._('THB', 764, 100, const _THB());
  static const TOP = const Currency._('TOP', 776, 100, const _TOP());
  static const TTD = const Currency._('TTD', 780, 100, const _TTD());
  static const AED = const Currency._('AED', 784, 100, const _AED());
  static const TND = const Currency._('TND', 788, 1000, const _TND());
  static const UGX = const Currency._('UGX', 800, 1, const _UGX());
  static const MKD = const Currency._('MKD', 807, 100, const _MKD());
  static const EGP = const Currency._('EGP', 818, 100, const _EGP());
  static const GBP = const Currency._('GBP', 826, 100, const _GBP());
  static const TZS = const Currency._('TZS', 834, 100, const _TZS());
  static const USD = const Currency._('USD', 840, 100, const _USD());
  static const UYU = const Currency._('UYU', 858, 100, const _UYU());
  static const UZS = const Currency._('UZS', 860, 100, const _UZS());
  static const WST = const Currency._('WST', 882, 100, const _WST());
  static const YER = const Currency._('YER', 886, 100, const _YER());
  static const TWD = const Currency._('TWD', 901, 100, const _TWD());
  static const UYW = const Currency._('UYW', 927, 10000, const _UYW());
  static const VES = const Currency._('VES', 928, 100, const _VES());
  static const MRU = const Currency._('MRU', 929, 100, const _MRU());
  static const STN = const Currency._('STN', 930, 100, const _STN());
  static const CUC = const Currency._('CUC', 931, 100, const _CUC());
  static const ZWL = const Currency._('ZWL', 932, 100, const _ZWL());
  static const BYN = const Currency._('BYN', 933, 100, const _BYN());
  static const TMT = const Currency._('TMT', 934, 100, const _TMT());
  static const GHS = const Currency._('GHS', 936, 100, const _GHS());
  static const SDG = const Currency._('SDG', 938, 100, const _SDG());
  static const UYI = const Currency._('UYI', 940, 1, const _UYI());
  static const RSD = const Currency._('RSD', 941, 100, const _RSD());
  static const MZN = const Currency._('MZN', 943, 100, const _MZN());
  static const AZN = const Currency._('AZN', 944, 100, const _AZN());
  static const RON = const Currency._('RON', 946, 100, const _RON());
  static const CHE = const Currency._('CHE', 947, 100, const _CHE());
  static const CHW = const Currency._('CHW', 948, 100, const _CHW());
  static const TRY = const Currency._('TRY', 949, 100, const _TRY());
  static const XAF = const Currency._('XAF', 950, 1, const _XAF());
  static const XCD = const Currency._('XCD', 951, 100, const _XCD());
  static const XOF = const Currency._('XOF', 952, 1, const _XOF());
  static const XPF = const Currency._('XPF', 953, 1, const _XPF());
  static const XBA = const Currency._('XBA', 955, null, const _XBA());
  static const XBB = const Currency._('XBB', 956, null, const _XBB());
  static const XBC = const Currency._('XBC', 957, null, const _XBC());
  static const XBD = const Currency._('XBD', 958, null, const _XBD());
  static const XAU = const Currency._('XAU', 959, null, const _XAU());
  static const XDR = const Currency._('XDR', 960, null, const _XDR());
  static const XAG = const Currency._('XAG', 961, null, const _XAG());
  static const XPT = const Currency._('XPT', 962, null, const _XPT());
  static const XTS = const Currency._('XTS', 963, null, const _XTS());
  static const XPD = const Currency._('XPD', 964, null, const _XPD());
  static const XUA = const Currency._('XUA', 965, null, const _XUA());
  static const ZMW = const Currency._('ZMW', 967, 100, const _ZMW());
  static const SRD = const Currency._('SRD', 968, 100, const _SRD());
  static const MGA = const Currency._('MGA', 969, 100, const _MGA());
  static const COU = const Currency._('COU', 970, 100, const _COU());
  static const AFN = const Currency._('AFN', 971, 100, const _AFN());
  static const TJS = const Currency._('TJS', 972, 100, const _TJS());
  static const AOA = const Currency._('AOA', 973, 100, const _AOA());
  static const BGN = const Currency._('BGN', 975, 100, const _BGN());
  static const CDF = const Currency._('CDF', 976, 100, const _CDF());
  static const BAM = const Currency._('BAM', 977, 100, const _BAM());
  static const EUR = const Currency._('EUR', 978, 100, const _EUR());
  static const MXV = const Currency._('MXV', 979, 100, const _MXV());
  static const UAH = const Currency._('UAH', 980, 100, const _UAH());
  static const GEL = const Currency._('GEL', 981, 100, const _GEL());
  static const BOV = const Currency._('BOV', 984, 100, const _BOV());
  static const PLN = const Currency._('PLN', 985, 100, const _PLN());
  static const BRL = const Currency._('BRL', 986, 100, const _BRL());
  static const CLF = const Currency._('CLF', 990, 10000, const _CLF());
  static const XSU = const Currency._('XSU', 994, null, const _XSU());
  static const USN = const Currency._('USN', 997, 100, const _USN());
}
