// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pgde/l10n/l10n.proto

package l10n

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	descriptor "github.com/golang/protobuf/protoc-gen-go/descriptor"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Value struct {
	Ignore               bool     `protobuf:"varint,1,opt,name=ignore,proto3" json:"ignore,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Desc                 string   `protobuf:"bytes,3,opt,name=desc,proto3" json:"desc,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Value) Reset()         { *m = Value{} }
func (m *Value) String() string { return proto.CompactTextString(m) }
func (*Value) ProtoMessage()    {}
func (*Value) Descriptor() ([]byte, []int) {
	return fileDescriptor_4ceebc29c2372422, []int{0}
}

func (m *Value) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Value.Unmarshal(m, b)
}
func (m *Value) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Value.Marshal(b, m, deterministic)
}
func (m *Value) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Value.Merge(m, src)
}
func (m *Value) XXX_Size() int {
	return xxx_messageInfo_Value.Size(m)
}
func (m *Value) XXX_DiscardUnknown() {
	xxx_messageInfo_Value.DiscardUnknown(m)
}

var xxx_messageInfo_Value proto.InternalMessageInfo

func (m *Value) GetIgnore() bool {
	if m != nil {
		return m.Ignore
	}
	return false
}

func (m *Value) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *Value) GetDesc() string {
	if m != nil {
		return m.Desc
	}
	return ""
}

type Oneof struct {
	Ignore bool   `protobuf:"varint,1,opt,name=ignore,proto3" json:"ignore,omitempty"`
	Value  string `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	// can be "$" to use label
	Desc                 string   `protobuf:"bytes,3,opt,name=desc,proto3" json:"desc,omitempty"`
	Label                string   `protobuf:"bytes,4,opt,name=label,proto3" json:"label,omitempty"`
	Prefix               string   `protobuf:"bytes,5,opt,name=prefix,proto3" json:"prefix,omitempty"`
	Suffix               string   `protobuf:"bytes,6,opt,name=suffix,proto3" json:"suffix,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Oneof) Reset()         { *m = Oneof{} }
func (m *Oneof) String() string { return proto.CompactTextString(m) }
func (*Oneof) ProtoMessage()    {}
func (*Oneof) Descriptor() ([]byte, []int) {
	return fileDescriptor_4ceebc29c2372422, []int{1}
}

func (m *Oneof) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Oneof.Unmarshal(m, b)
}
func (m *Oneof) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Oneof.Marshal(b, m, deterministic)
}
func (m *Oneof) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Oneof.Merge(m, src)
}
func (m *Oneof) XXX_Size() int {
	return xxx_messageInfo_Oneof.Size(m)
}
func (m *Oneof) XXX_DiscardUnknown() {
	xxx_messageInfo_Oneof.DiscardUnknown(m)
}

var xxx_messageInfo_Oneof proto.InternalMessageInfo

func (m *Oneof) GetIgnore() bool {
	if m != nil {
		return m.Ignore
	}
	return false
}

func (m *Oneof) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *Oneof) GetDesc() string {
	if m != nil {
		return m.Desc
	}
	return ""
}

func (m *Oneof) GetLabel() string {
	if m != nil {
		return m.Label
	}
	return ""
}

func (m *Oneof) GetPrefix() string {
	if m != nil {
		return m.Prefix
	}
	return ""
}

func (m *Oneof) GetSuffix() string {
	if m != nil {
		return m.Suffix
	}
	return ""
}

type MsgOrEnum struct {
	Ignore bool   `protobuf:"varint,1,opt,name=ignore,proto3" json:"ignore,omitempty"`
	Value  string `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	// can be "$" to use label
	Desc                 string   `protobuf:"bytes,3,opt,name=desc,proto3" json:"desc,omitempty"`
	Label                string   `protobuf:"bytes,4,opt,name=label,proto3" json:"label,omitempty"`
	Helper               string   `protobuf:"bytes,5,opt,name=helper,proto3" json:"helper,omitempty"`
	Hint                 string   `protobuf:"bytes,6,opt,name=hint,proto3" json:"hint,omitempty"`
	Prefix               string   `protobuf:"bytes,7,opt,name=prefix,proto3" json:"prefix,omitempty"`
	Suffix               string   `protobuf:"bytes,8,opt,name=suffix,proto3" json:"suffix,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgOrEnum) Reset()         { *m = MsgOrEnum{} }
func (m *MsgOrEnum) String() string { return proto.CompactTextString(m) }
func (*MsgOrEnum) ProtoMessage()    {}
func (*MsgOrEnum) Descriptor() ([]byte, []int) {
	return fileDescriptor_4ceebc29c2372422, []int{2}
}

func (m *MsgOrEnum) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgOrEnum.Unmarshal(m, b)
}
func (m *MsgOrEnum) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgOrEnum.Marshal(b, m, deterministic)
}
func (m *MsgOrEnum) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgOrEnum.Merge(m, src)
}
func (m *MsgOrEnum) XXX_Size() int {
	return xxx_messageInfo_MsgOrEnum.Size(m)
}
func (m *MsgOrEnum) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgOrEnum.DiscardUnknown(m)
}

var xxx_messageInfo_MsgOrEnum proto.InternalMessageInfo

func (m *MsgOrEnum) GetIgnore() bool {
	if m != nil {
		return m.Ignore
	}
	return false
}

func (m *MsgOrEnum) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *MsgOrEnum) GetDesc() string {
	if m != nil {
		return m.Desc
	}
	return ""
}

func (m *MsgOrEnum) GetLabel() string {
	if m != nil {
		return m.Label
	}
	return ""
}

func (m *MsgOrEnum) GetHelper() string {
	if m != nil {
		return m.Helper
	}
	return ""
}

func (m *MsgOrEnum) GetHint() string {
	if m != nil {
		return m.Hint
	}
	return ""
}

func (m *MsgOrEnum) GetPrefix() string {
	if m != nil {
		return m.Prefix
	}
	return ""
}

func (m *MsgOrEnum) GetSuffix() string {
	if m != nil {
		return m.Suffix
	}
	return ""
}

// use '-' to disable assets[label, helper, hint, prefix, suffix, boolTrue, boolFalse]
type Field struct {
	Ignore bool `protobuf:"varint,1,opt,name=ignore,proto3" json:"ignore,omitempty"`
	// can be "$" to use the field name of itself, just to generate the seed arb
	// file.
	Value string `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	// can be "$" to consider label as first choice
	Desc  string `protobuf:"bytes,3,opt,name=desc,proto3" json:"desc,omitempty"`
	Label string `protobuf:"bytes,4,opt,name=label,proto3" json:"label,omitempty"`
	/// Text that provides context about the input [child]'s value, such as how
	/// the value will be used.
	///
	/// If non-null, the text is displayed below the input [child], in the same
	/// location as [errorText]. If a non-null [errorText] value is specified then
	/// the helper text is not shown.
	Helper string `protobuf:"bytes,5,opt,name=helper,proto3" json:"helper,omitempty"`
	/// Text that suggests what sort of input the field accepts.
	///
	/// Displayed on top of the input [child] (i.e., at the same location on the
	/// screen where text may be entered in the input [child]) when the input
	/// [isEmpty] and either (a) [labelText] is null or (b) the input has the
	/// focus.
	Hint string `protobuf:"bytes,6,opt,name=hint,proto3" json:"hint,omitempty"`
	/// Optional text prefix to place on the line before the input.
	///
	/// Uses the [prefixStyle]. Uses [hintStyle] if [prefixStyle] isn't specified.
	/// The prefix text is not returned as part of the user's input.
	///
	/// If a more elaborate prefix is required, consider using [prefix] instead.
	/// Only one of [prefix] and [prefixText] can be specified.
	///
	/// The [prefixText] appears after the [prefixIcon], if both are specified.
	///
	/// See also:
	///
	///  * [suffixText], the equivalent but on the trailing edge.
	Prefix string `protobuf:"bytes,7,opt,name=prefix,proto3" json:"prefix,omitempty"`
	/// Optional text suffix to place on the line after the input.
	///
	/// Uses the [suffixStyle]. Uses [hintStyle] if [suffixStyle] isn't specified.
	/// The suffix text is not returned as part of the user's input.
	///
	/// If a more elaborate suffix is required, consider using [suffix] instead.
	/// Only one of [suffix] and [suffixText] can be specified.
	///
	/// The [suffixText] appears before the [suffixIcon], if both are specified.
	///
	/// See also:
	///
	///  * [prefixText], the equivalent but on the leading edge.
	Suffix               string   `protobuf:"bytes,8,opt,name=suffix,proto3" json:"suffix,omitempty"`
	BoolTrue             string   `protobuf:"bytes,9,opt,name=boolTrue,proto3" json:"boolTrue,omitempty"`
	BoolFalse            string   `protobuf:"bytes,10,opt,name=boolFalse,proto3" json:"boolFalse,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Field) Reset()         { *m = Field{} }
func (m *Field) String() string { return proto.CompactTextString(m) }
func (*Field) ProtoMessage()    {}
func (*Field) Descriptor() ([]byte, []int) {
	return fileDescriptor_4ceebc29c2372422, []int{3}
}

func (m *Field) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Field.Unmarshal(m, b)
}
func (m *Field) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Field.Marshal(b, m, deterministic)
}
func (m *Field) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Field.Merge(m, src)
}
func (m *Field) XXX_Size() int {
	return xxx_messageInfo_Field.Size(m)
}
func (m *Field) XXX_DiscardUnknown() {
	xxx_messageInfo_Field.DiscardUnknown(m)
}

var xxx_messageInfo_Field proto.InternalMessageInfo

func (m *Field) GetIgnore() bool {
	if m != nil {
		return m.Ignore
	}
	return false
}

func (m *Field) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *Field) GetDesc() string {
	if m != nil {
		return m.Desc
	}
	return ""
}

func (m *Field) GetLabel() string {
	if m != nil {
		return m.Label
	}
	return ""
}

func (m *Field) GetHelper() string {
	if m != nil {
		return m.Helper
	}
	return ""
}

func (m *Field) GetHint() string {
	if m != nil {
		return m.Hint
	}
	return ""
}

func (m *Field) GetPrefix() string {
	if m != nil {
		return m.Prefix
	}
	return ""
}

func (m *Field) GetSuffix() string {
	if m != nil {
		return m.Suffix
	}
	return ""
}

func (m *Field) GetBoolTrue() string {
	if m != nil {
		return m.BoolTrue
	}
	return ""
}

func (m *Field) GetBoolFalse() string {
	if m != nil {
		return m.BoolFalse
	}
	return ""
}

var E_Enum = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.EnumOptions)(nil),
	ExtensionType: (*MsgOrEnum)(nil),
	Field:         919110,
	Name:          "pgde.l10n.enum",
	Tag:           "bytes,919110,opt,name=enum",
	Filename:      "pgde/l10n/l10n.proto",
}

var E_Value = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.EnumValueOptions)(nil),
	ExtensionType: (*Value)(nil),
	Field:         919110,
	Name:          "pgde.l10n.value",
	Tag:           "bytes,919110,opt,name=value",
	Filename:      "pgde/l10n/l10n.proto",
}

var E_Message = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.MessageOptions)(nil),
	ExtensionType: (*MsgOrEnum)(nil),
	Field:         919110,
	Name:          "pgde.l10n.message",
	Tag:           "bytes,919110,opt,name=message",
	Filename:      "pgde/l10n/l10n.proto",
}

var E_Oneof = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.OneofOptions)(nil),
	ExtensionType: (*Oneof)(nil),
	Field:         919110,
	Name:          "pgde.l10n.oneof",
	Tag:           "bytes,919110,opt,name=oneof",
	Filename:      "pgde/l10n/l10n.proto",
}

var E_Field = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FieldOptions)(nil),
	ExtensionType: (*Field)(nil),
	Field:         919110,
	Name:          "pgde.l10n.field",
	Tag:           "bytes,919110,opt,name=field",
	Filename:      "pgde/l10n/l10n.proto",
}

func init() {
	proto.RegisterType((*Value)(nil), "pgde.l10n.Value")
	proto.RegisterType((*Oneof)(nil), "pgde.l10n.Oneof")
	proto.RegisterType((*MsgOrEnum)(nil), "pgde.l10n.MsgOrEnum")
	proto.RegisterType((*Field)(nil), "pgde.l10n.Field")
	proto.RegisterExtension(E_Enum)
	proto.RegisterExtension(E_Value)
	proto.RegisterExtension(E_Message)
	proto.RegisterExtension(E_Oneof)
	proto.RegisterExtension(E_Field)
}

func init() { proto.RegisterFile("pgde/l10n/l10n.proto", fileDescriptor_4ceebc29c2372422) }

var fileDescriptor_4ceebc29c2372422 = []byte{
	// 434 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xd4, 0x94, 0xcf, 0xaa, 0xd4, 0x30,
	0x14, 0xc6, 0xa9, 0x4e, 0xe7, 0x4e, 0xe3, 0x46, 0xc2, 0x20, 0xe1, 0x72, 0xc5, 0x3a, 0xab, 0xd9,
	0x4c, 0xea, 0x1f, 0x90, 0x4b, 0x97, 0x82, 0x57, 0x45, 0x2e, 0x83, 0x45, 0x5c, 0xb8, 0x6b, 0xa7,
	0xa7, 0x99, 0x60, 0xda, 0x84, 0xb4, 0x95, 0x79, 0x08, 0xc1, 0x47, 0x72, 0xe7, 0x1b, 0xb9, 0x97,
	0x9c, 0x74, 0xea, 0xe8, 0xe8, 0x20, 0x88, 0x0b, 0x37, 0x25, 0xdf, 0x77, 0xbe, 0xfe, 0x38, 0x69,
	0x4e, 0x43, 0xe6, 0x46, 0x94, 0x90, 0xa8, 0x87, 0x0f, 0x1a, 0x7c, 0x70, 0x63, 0x75, 0xa7, 0x69,
	0xe4, 0x5c, 0xee, 0x8c, 0xf3, 0x58, 0x68, 0x2d, 0x14, 0x24, 0x58, 0x28, 0xfa, 0x2a, 0x29, 0xa1,
	0xdd, 0x58, 0x69, 0x3a, 0x6d, 0x7d, 0x78, 0xf1, 0x92, 0x84, 0x6f, 0x73, 0xd5, 0x03, 0xbd, 0x43,
	0xa6, 0x52, 0x34, 0xda, 0x02, 0x0b, 0xe2, 0x60, 0x39, 0xcb, 0x06, 0x45, 0xe7, 0x24, 0xfc, 0xe0,
	0x02, 0xec, 0x46, 0x1c, 0x2c, 0xa3, 0xcc, 0x0b, 0x4a, 0xc9, 0xc4, 0xa1, 0xd8, 0x4d, 0x34, 0x71,
	0xbd, 0xf8, 0x14, 0x90, 0x70, 0xdd, 0x80, 0xae, 0xfe, 0x9e, 0xe5, 0x92, 0x2a, 0x2f, 0x40, 0xb1,
	0x89, 0x4f, 0xa2, 0x70, 0x5c, 0x63, 0xa1, 0x92, 0x3b, 0x16, 0xa2, 0x3d, 0x28, 0xe7, 0xb7, 0x7d,
	0xe5, 0xfc, 0xa9, 0xf7, 0xbd, 0x5a, 0x7c, 0x0e, 0x48, 0x74, 0xdd, 0x8a, 0xb5, 0x7d, 0xd6, 0xf4,
	0xf5, 0xbf, 0xec, 0x6a, 0x0b, 0xca, 0x80, 0xdd, 0x77, 0xe5, 0x95, 0x23, 0x6c, 0x65, 0xd3, 0x0d,
	0x3d, 0xe1, 0xfa, 0x60, 0x07, 0x67, 0xbf, 0xd9, 0xc1, 0xec, 0x87, 0x1d, 0x7c, 0x0d, 0x48, 0x78,
	0x25, 0x41, 0x95, 0xff, 0x63, 0xf7, 0xf4, 0x9c, 0xcc, 0x0a, 0xad, 0xd5, 0x1b, 0xdb, 0x03, 0x8b,
	0xb0, 0x32, 0x6a, 0x7a, 0x41, 0x22, 0xb7, 0xbe, 0xca, 0x55, 0x0b, 0x8c, 0x60, 0xf1, 0xbb, 0x91,
	0xbe, 0x20, 0x13, 0x70, 0x67, 0x76, 0xc1, 0xfd, 0x04, 0xf3, 0xfd, 0x04, 0x73, 0x77, 0x94, 0x6b,
	0xd3, 0x49, 0xdd, 0xb4, 0xec, 0xcb, 0xc7, 0xcb, 0x38, 0x58, 0xde, 0x7a, 0x34, 0xe7, 0xe3, 0xc8,
	0xf3, 0xf1, 0xbc, 0x33, 0x24, 0xa4, 0xaf, 0x86, 0xef, 0x43, 0xef, 0xff, 0x12, 0x85, 0xc3, 0xff,
	0x33, 0xef, 0xf6, 0x01, 0x0f, 0x03, 0xc3, 0x67, 0x4d, 0x5f, 0x93, 0xb3, 0x1a, 0xda, 0x36, 0x17,
	0x40, 0xef, 0x1d, 0xe1, 0xae, 0x7d, 0xe5, 0xcf, 0x9a, 0xdb, 0x73, 0xd2, 0xe7, 0x24, 0xd4, 0xf8,
	0xd3, 0xdc, 0x3d, 0x02, 0xe2, 0xcf, 0x74, 0xaa, 0x37, 0x0c, 0x64, 0xfe, 0x7d, 0x07, 0xaa, 0x70,
	0x52, 0x8e, 0x41, 0x38, 0x41, 0xa7, 0x40, 0x18, 0xc8, 0xfc, 0xfb, 0x4f, 0x2f, 0xdf, 0x3d, 0x11,
	0xb2, 0xdb, 0xf6, 0x05, 0xdf, 0xe8, 0x3a, 0x81, 0xda, 0x48, 0x0b, 0x95, 0xde, 0xf9, 0x4b, 0x64,
	0xb3, 0x12, 0xd0, 0xac, 0xca, 0xdc, 0x76, 0x2b, 0xd8, 0x75, 0x89, 0x79, 0x2f, 0x92, 0xf1, 0x12,
	0x2a, 0xa6, 0x18, 0x79, 0xfc, 0x2d, 0x00, 0x00, 0xff, 0xff, 0x1d, 0x2f, 0x08, 0x39, 0x98, 0x04,
	0x00, 0x00,
}
