// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protos/units/units.proto

package units // import "github.com/empirefox/protoc-gen-dart-ext/pkg/units"

/*
https://physics.nist.gov/cuu/Units/units.html
*/

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import descriptor "github.com/golang/protobuf/protoc-gen-go/descriptor"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type PrefixType int32

const (
	PrefixType_symbol PrefixType = 0
	PrefixType_title  PrefixType = 1
)

var PrefixType_name = map[int32]string{
	0: "symbol",
	1: "title",
}
var PrefixType_value = map[string]int32{
	"symbol": 0,
	"title":  1,
}

func (x PrefixType) String() string {
	return proto.EnumName(PrefixType_name, int32(x))
}
func (PrefixType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_units_94d376692e76fe91, []int{0}
}

type Show_AtomType int32

const (
	Show_symbol Show_AtomType = 0
	// plural Form.one
	Show_one Show_AtomType = 1
	// plural Form.other
	Show_other Show_AtomType = 2
	// parse Form from plural tool
	Show_parse Show_AtomType = 3
)

var Show_AtomType_name = map[int32]string{
	0: "symbol",
	1: "one",
	2: "other",
	3: "parse",
}
var Show_AtomType_value = map[string]int32{
	"symbol": 0,
	"one":    1,
	"other":  2,
	"parse":  3,
}

func (x Show_AtomType) String() string {
	return proto.EnumName(Show_AtomType_name, int32(x))
}
func (Show_AtomType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_units_94d376692e76fe91, []int{1, 0}
}

type Unit struct {
	Show                 *Show    `protobuf:"bytes,1,opt,name=show,proto3" json:"show,omitempty"`
	Dots                 []*Cell  `protobuf:"bytes,2,rep,name=dots,proto3" json:"dots,omitempty"`
	Per                  []*Cell  `protobuf:"bytes,3,rep,name=per,proto3" json:"per,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Unit) Reset()         { *m = Unit{} }
func (m *Unit) String() string { return proto.CompactTextString(m) }
func (*Unit) ProtoMessage()    {}
func (*Unit) Descriptor() ([]byte, []int) {
	return fileDescriptor_units_94d376692e76fe91, []int{0}
}
func (m *Unit) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Unit.Unmarshal(m, b)
}
func (m *Unit) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Unit.Marshal(b, m, deterministic)
}
func (dst *Unit) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Unit.Merge(dst, src)
}
func (m *Unit) XXX_Size() int {
	return xxx_messageInfo_Unit.Size(m)
}
func (m *Unit) XXX_DiscardUnknown() {
	xxx_messageInfo_Unit.DiscardUnknown(m)
}

var xxx_messageInfo_Unit proto.InternalMessageInfo

func (m *Unit) GetShow() *Show {
	if m != nil {
		return m.Show
	}
	return nil
}

func (m *Unit) GetDots() []*Cell {
	if m != nil {
		return m.Dots
	}
	return nil
}

func (m *Unit) GetPer() []*Cell {
	if m != nil {
		return m.Per
	}
	return nil
}

type Show struct {
	Off                  bool          `protobuf:"varint,1,opt,name=off,proto3" json:"off,omitempty"`
	Prefix               PrefixType    `protobuf:"varint,2,opt,name=prefix,proto3,enum=pgde.units.PrefixType" json:"prefix,omitempty"`
	Atom                 Show_AtomType `protobuf:"varint,3,opt,name=atom,proto3,enum=pgde.units.Show_AtomType" json:"atom,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Show) Reset()         { *m = Show{} }
func (m *Show) String() string { return proto.CompactTextString(m) }
func (*Show) ProtoMessage()    {}
func (*Show) Descriptor() ([]byte, []int) {
	return fileDescriptor_units_94d376692e76fe91, []int{1}
}
func (m *Show) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Show.Unmarshal(m, b)
}
func (m *Show) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Show.Marshal(b, m, deterministic)
}
func (dst *Show) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Show.Merge(dst, src)
}
func (m *Show) XXX_Size() int {
	return xxx_messageInfo_Show.Size(m)
}
func (m *Show) XXX_DiscardUnknown() {
	xxx_messageInfo_Show.DiscardUnknown(m)
}

var xxx_messageInfo_Show proto.InternalMessageInfo

func (m *Show) GetOff() bool {
	if m != nil {
		return m.Off
	}
	return false
}

func (m *Show) GetPrefix() PrefixType {
	if m != nil {
		return m.Prefix
	}
	return PrefixType_symbol
}

func (m *Show) GetAtom() Show_AtomType {
	if m != nil {
		return m.Atom
	}
	return Show_symbol
}

type Cell struct {
	Exponent int32    `protobuf:"varint,1,opt,name=exponent,proto3" json:"exponent,omitempty"`
	Prefix   PrefixV1 `protobuf:"varint,2,opt,name=prefix,proto3,enum=pgde.units.PrefixV1" json:"prefix,omitempty"`
	// Types that are valid to be assigned to Type:
	//	*Cell_Atom
	//	*Cell_Symbol
	Type                 isCell_Type `protobuf_oneof:"type"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Cell) Reset()         { *m = Cell{} }
func (m *Cell) String() string { return proto.CompactTextString(m) }
func (*Cell) ProtoMessage()    {}
func (*Cell) Descriptor() ([]byte, []int) {
	return fileDescriptor_units_94d376692e76fe91, []int{2}
}
func (m *Cell) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Cell.Unmarshal(m, b)
}
func (m *Cell) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Cell.Marshal(b, m, deterministic)
}
func (dst *Cell) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Cell.Merge(dst, src)
}
func (m *Cell) XXX_Size() int {
	return xxx_messageInfo_Cell.Size(m)
}
func (m *Cell) XXX_DiscardUnknown() {
	xxx_messageInfo_Cell.DiscardUnknown(m)
}

var xxx_messageInfo_Cell proto.InternalMessageInfo

type isCell_Type interface {
	isCell_Type()
}

type Cell_Atom struct {
	Atom AtomV1 `protobuf:"varint,3,opt,name=atom,proto3,enum=pgde.units.AtomV1,oneof"`
}
type Cell_Symbol struct {
	Symbol string `protobuf:"bytes,4,opt,name=symbol,proto3,oneof"`
}

func (*Cell_Atom) isCell_Type()   {}
func (*Cell_Symbol) isCell_Type() {}

func (m *Cell) GetType() isCell_Type {
	if m != nil {
		return m.Type
	}
	return nil
}

func (m *Cell) GetExponent() int32 {
	if m != nil {
		return m.Exponent
	}
	return 0
}

func (m *Cell) GetPrefix() PrefixV1 {
	if m != nil {
		return m.Prefix
	}
	return PrefixV1_noPrefix
}

func (m *Cell) GetAtom() AtomV1 {
	if x, ok := m.GetType().(*Cell_Atom); ok {
		return x.Atom
	}
	return AtomV1_noAtom
}

func (m *Cell) GetSymbol() string {
	if x, ok := m.GetType().(*Cell_Symbol); ok {
		return x.Symbol
	}
	return ""
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*Cell) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _Cell_OneofMarshaler, _Cell_OneofUnmarshaler, _Cell_OneofSizer, []interface{}{
		(*Cell_Atom)(nil),
		(*Cell_Symbol)(nil),
	}
}

func _Cell_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*Cell)
	// type
	switch x := m.Type.(type) {
	case *Cell_Atom:
		b.EncodeVarint(3<<3 | proto.WireVarint)
		b.EncodeVarint(uint64(x.Atom))
	case *Cell_Symbol:
		b.EncodeVarint(4<<3 | proto.WireBytes)
		b.EncodeStringBytes(x.Symbol)
	case nil:
	default:
		return fmt.Errorf("Cell.Type has unexpected type %T", x)
	}
	return nil
}

func _Cell_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*Cell)
	switch tag {
	case 3: // type.atom
		if wire != proto.WireVarint {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeVarint()
		m.Type = &Cell_Atom{AtomV1(x)}
		return true, err
	case 4: // type.symbol
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeStringBytes()
		m.Type = &Cell_Symbol{x}
		return true, err
	default:
		return false, nil
	}
}

func _Cell_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*Cell)
	// type
	switch x := m.Type.(type) {
	case *Cell_Atom:
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(x.Atom))
	case *Cell_Symbol:
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(len(x.Symbol)))
		n += len(x.Symbol)
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

var E_Unit = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FieldOptions)(nil),
	ExtensionType: (*Unit)(nil),
	Field:         919112,
	Name:          "pgde.units.unit",
	Tag:           "bytes,919112,opt,name=unit",
	Filename:      "protos/units/units.proto",
}

func init() {
	proto.RegisterType((*Unit)(nil), "pgde.units.Unit")
	proto.RegisterType((*Show)(nil), "pgde.units.Show")
	proto.RegisterType((*Cell)(nil), "pgde.units.Cell")
	proto.RegisterEnum("pgde.units.PrefixType", PrefixType_name, PrefixType_value)
	proto.RegisterEnum("pgde.units.Show_AtomType", Show_AtomType_name, Show_AtomType_value)
	proto.RegisterExtension(E_Unit)
}

func init() { proto.RegisterFile("protos/units/units.proto", fileDescriptor_units_94d376692e76fe91) }

var fileDescriptor_units_94d376692e76fe91 = []byte{
	// 429 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x74, 0x92, 0xdf, 0xea, 0xd3, 0x30,
	0x14, 0xc7, 0x7f, 0xfd, 0xb5, 0xab, 0xdb, 0x11, 0xa4, 0x04, 0xd1, 0x6e, 0x20, 0x8c, 0xea, 0xc5,
	0x10, 0x9b, 0xb2, 0xa9, 0x20, 0xde, 0x39, 0x51, 0xbc, 0x53, 0xaa, 0xee, 0xc2, 0xbb, 0x75, 0x4d,
	0xbb, 0x60, 0xdb, 0x84, 0x34, 0xd3, 0xee, 0x1d, 0x7c, 0x04, 0x9f, 0xc1, 0xe7, 0xf0, 0xb1, 0x4c,
	0xd2, 0xee, 0x4f, 0x37, 0xbc, 0x29, 0xc9, 0xf9, 0x7e, 0x73, 0xce, 0xe7, 0x94, 0x2f, 0xf8, 0x5c,
	0x30, 0xc9, 0xea, 0x68, 0x57, 0x51, 0xd9, 0x7d, 0xb1, 0x29, 0x21, 0xe0, 0x79, 0x4a, 0xb0, 0xa9,
	0x4c, 0xa6, 0x39, 0x63, 0x79, 0x41, 0x22, 0xa3, 0x24, 0xbb, 0x2c, 0x4a, 0x49, 0xbd, 0x11, 0x94,
	0x4b, 0x26, 0x5a, 0xf7, 0x64, 0xdc, 0xeb, 0xc3, 0x05, 0xc9, 0x68, 0xd3, 0x49, 0x0f, 0x7b, 0xd2,
	0x5a, 0xb2, 0xb2, 0x15, 0x82, 0x1f, 0xe0, 0x7c, 0x55, 0x35, 0xf4, 0x04, 0x9c, 0x7a, 0xcb, 0x7e,
	0xfa, 0xd6, 0xd4, 0x9a, 0xdd, 0x5d, 0x78, 0xf8, 0x34, 0x18, 0x7f, 0x56, 0xf5, 0xd8, 0xa8, 0xda,
	0x95, 0x32, 0x59, 0xfb, 0xb7, 0x53, 0xfb, 0xd2, 0xf5, 0x96, 0x14, 0x45, 0x6c, 0x54, 0x14, 0x80,
	0xcd, 0x89, 0xf0, 0xed, 0xff, 0x98, 0xb4, 0x18, 0xfc, 0xb1, 0xc0, 0xd1, 0x8d, 0x91, 0x07, 0x36,
	0xcb, 0x32, 0x33, 0x77, 0x18, 0xeb, 0x23, 0xc2, 0xe0, 0xb6, 0xec, 0x6a, 0x8c, 0x35, 0xbb, 0xb7,
	0x78, 0x70, 0xde, 0xe1, 0x93, 0x51, 0xbe, 0xec, 0x39, 0x89, 0x3b, 0x17, 0x0a, 0xc1, 0xd1, 0x0b,
	0xa9, 0x79, 0xda, 0x3d, 0xbe, 0x44, 0xc7, 0x6f, 0x94, 0x68, 0x1e, 0x18, 0x5b, 0xf0, 0x12, 0x86,
	0x87, 0x0a, 0x02, 0x70, 0xeb, 0x7d, 0x99, 0xb0, 0xc2, 0xbb, 0x41, 0x77, 0x14, 0x48, 0x45, 0x3c,
	0x0b, 0x8d, 0x60, 0xc0, 0xe4, 0x96, 0x08, 0xef, 0x56, 0x1f, 0xf9, 0x5a, 0xd4, 0xc4, 0xb3, 0x83,
	0xdf, 0x0a, 0x58, 0xe3, 0xa3, 0x09, 0x0c, 0x49, 0xc3, 0x95, 0xb5, 0x92, 0x86, 0x7a, 0x10, 0x1f,
	0xef, 0xe8, 0xd9, 0x05, 0xfa, 0xfd, 0x6b, 0xf4, 0xd5, 0xfc, 0x08, 0x3e, 0xeb, 0x81, 0xa3, 0x73,
	0xaf, 0x26, 0x5c, 0xcd, 0x3f, 0xdc, 0xb4, 0xcc, 0xc8, 0x3f, 0x70, 0xfa, 0x8e, 0xf2, 0x8e, 0x54,
	0xbd, 0xbb, 0x2f, 0x5d, 0x70, 0xa4, 0xda, 0xe4, 0xe9, 0x63, 0x80, 0xd3, 0xaf, 0xe9, 0xed, 0xa5,
	0x76, 0x90, 0x54, 0x16, 0x6a, 0xb3, 0xd7, 0xef, 0xc0, 0xd1, 0xed, 0xd1, 0x23, 0xdc, 0x66, 0x09,
	0x1f, 0xb2, 0x84, 0xdf, 0x53, 0x52, 0xa4, 0x1f, 0xb9, 0xa4, 0xac, 0xaa, 0xfd, 0xbf, 0xbf, 0x5e,
	0x5d, 0xa7, 0x40, 0xa7, 0x24, 0x36, 0xcf, 0x97, 0x2f, 0xbe, 0x2d, 0x72, 0x2a, 0xb7, 0xbb, 0x04,
	0x6f, 0x58, 0x19, 0x91, 0x92, 0x53, 0x35, 0x99, 0x35, 0x6d, 0x32, 0x37, 0x61, 0x4e, 0xaa, 0x30,
	0x5d, 0x0b, 0x19, 0x92, 0x46, 0x46, 0xfc, 0x7b, 0xde, 0x86, 0x2e, 0x71, 0x8d, 0xfc, 0xfc, 0x5f,
	0x00, 0x00, 0x00, 0xff, 0xff, 0x06, 0xa3, 0xcf, 0xb9, 0xee, 0x02, 0x00, 0x00,
}
