// DO NOT EDIT. Generated by protoc-gen-dart-ext/tools.

import '../l10n/pgde.l10n.dart';

abstract class _Valuer {
  String of(PgdeLocalization l);
}

class _NoPrefix implements _Valuer {
  const _NoPrefix();
  String of(PgdeLocalization l) => '';
}

class _Yotta implements _Valuer {
  const _Yotta();
  String of(PgdeLocalization l) => l.prefixYotta;
}

class _Zetta implements _Valuer {
  const _Zetta();
  String of(PgdeLocalization l) => l.prefixZetta;
}

class _Exa implements _Valuer {
  const _Exa();
  String of(PgdeLocalization l) => l.prefixExa;
}

class _Peta implements _Valuer {
  const _Peta();
  String of(PgdeLocalization l) => l.prefixPeta;
}

class _Tera implements _Valuer {
  const _Tera();
  String of(PgdeLocalization l) => l.prefixTera;
}

class _Giga implements _Valuer {
  const _Giga();
  String of(PgdeLocalization l) => l.prefixGiga;
}

class _Mega implements _Valuer {
  const _Mega();
  String of(PgdeLocalization l) => l.prefixMega;
}

class _Kilo implements _Valuer {
  const _Kilo();
  String of(PgdeLocalization l) => l.prefixKilo;
}

class _Hecto implements _Valuer {
  const _Hecto();
  String of(PgdeLocalization l) => l.prefixHecto;
}

class _Deka implements _Valuer {
  const _Deka();
  String of(PgdeLocalization l) => l.prefixDeka;
}

class _Deci implements _Valuer {
  const _Deci();
  String of(PgdeLocalization l) => l.prefixDeci;
}

class _Centi implements _Valuer {
  const _Centi();
  String of(PgdeLocalization l) => l.prefixCenti;
}

class _Milli implements _Valuer {
  const _Milli();
  String of(PgdeLocalization l) => l.prefixMilli;
}

class _Micro implements _Valuer {
  const _Micro();
  String of(PgdeLocalization l) => l.prefixMicro;
}

class _Nano implements _Valuer {
  const _Nano();
  String of(PgdeLocalization l) => l.prefixNano;
}

class _Pico implements _Valuer {
  const _Pico();
  String of(PgdeLocalization l) => l.prefixPico;
}

class _Femto implements _Valuer {
  const _Femto();
  String of(PgdeLocalization l) => l.prefixFemto;
}

class _Atto implements _Valuer {
  const _Atto();
  String of(PgdeLocalization l) => l.prefixAtto;
}

class _Zepto implements _Valuer {
  const _Zepto();
  String of(PgdeLocalization l) => l.prefixZepto;
}

class _Yocto implements _Valuer {
  const _Yocto();
  String of(PgdeLocalization l) => l.prefixYocto;
}

class _Kibi implements _Valuer {
  const _Kibi();
  String of(PgdeLocalization l) => l.prefixKibi;
}

class _Mebi implements _Valuer {
  const _Mebi();
  String of(PgdeLocalization l) => l.prefixMebi;
}

class _Gibi implements _Valuer {
  const _Gibi();
  String of(PgdeLocalization l) => l.prefixGibi;
}

class _Tebi implements _Valuer {
  const _Tebi();
  String of(PgdeLocalization l) => l.prefixTebi;
}

class _Pebi implements _Valuer {
  const _Pebi();
  String of(PgdeLocalization l) => l.prefixPebi;
}

class _Exbi implements _Valuer {
  const _Exbi();
  String of(PgdeLocalization l) => l.prefixExbi;
}

class Prefix {
  static const noPrefix = const Prefix._('', 1, 1, const _NoPrefix());
  static const yotta = const Prefix._(r'Y', 10, 24, const _Yotta());
  static const zetta = const Prefix._(r'Z', 10, 21, const _Zetta());
  static const exa = const Prefix._(r'E', 10, 18, const _Exa());
  static const peta = const Prefix._(r'P', 10, 15, const _Peta());
  static const tera = const Prefix._(r'T', 10, 12, const _Tera());
  static const giga = const Prefix._(r'G', 10, 9, const _Giga());
  static const mega = const Prefix._(r'M', 10, 6, const _Mega());
  static const kilo = const Prefix._(r'k', 10, 3, const _Kilo());
  static const hecto = const Prefix._(r'h', 10, 2, const _Hecto());
  static const deka = const Prefix._(r'da', 10, 1, const _Deka());
  static const deci = const Prefix._(r'd', 10, -1, const _Deci());
  static const centi = const Prefix._(r'c', 10, -2, const _Centi());
  static const milli = const Prefix._(r'm', 10, -3, const _Milli());
  static const micro = const Prefix._(r'µ', 10, -6, const _Micro());
  static const nano = const Prefix._(r'n', 10, -9, const _Nano());
  static const pico = const Prefix._(r'p', 10, -12, const _Pico());
  static const femto = const Prefix._(r'f', 10, -15, const _Femto());
  static const atto = const Prefix._(r'a', 10, -18, const _Atto());
  static const zepto = const Prefix._(r'z', 10, -21, const _Zepto());
  static const yocto = const Prefix._(r'y', 10, -24, const _Yocto());
  static const kibi = const Prefix._(r'Ki', 2, 10, const _Kibi());
  static const mebi = const Prefix._(r'Mi', 2, 20, const _Mebi());
  static const gibi = const Prefix._(r'Gi', 2, 30, const _Gibi());
  static const tebi = const Prefix._(r'Ti', 2, 40, const _Tebi());
  static const pebi = const Prefix._(r'Pi', 2, 50, const _Pebi());
  static const exbi = const Prefix._(r'Ei', 2, 60, const _Exbi());

  final String symbol;
  final int base;
  final int exponent;
  final _Valuer _v;
  const Prefix._(this.symbol, this.base, this.exponent, this._v);
  String l10n(PgdeLocalization l10n) => _v.of(l10n) ?? symbol;
}
