// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protos/form/form.proto

package form // import "github.com/empirefox/protoc-gen-dart-ext/pkg/form"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/empirefox/protoc-gen-dart-ext/pkg/units"
import descriptor "github.com/golang/protobuf/protoc-gen-go/descriptor"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type UnitPlace int32

const (
	UnitPlace_noUnitPlace UnitPlace = 0
	UnitPlace_suffix      UnitPlace = 1
	UnitPlace_labelSuffix UnitPlace = 2
)

var UnitPlace_name = map[int32]string{
	0: "noUnitPlace",
	1: "suffix",
	2: "labelSuffix",
}
var UnitPlace_value = map[string]int32{
	"noUnitPlace": 0,
	"suffix":      1,
	"labelSuffix": 2,
}

func (x UnitPlace) String() string {
	return proto.EnumName(UnitPlace_name, int32(x))
}
func (UnitPlace) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_form_00aa4113bc49fc04, []int{0}
}

type TextInput_Type int32

const (
	TextInput_autoByType   TextInput_Type = 0
	TextInput_datetime     TextInput_Type = 2
	TextInput_emailAddress TextInput_Type = 3
	TextInput_multiline    TextInput_Type = 4
	TextInput_number       TextInput_Type = 5
	TextInput_phone        TextInput_Type = 6
	TextInput_text         TextInput_Type = 7
	TextInput_url          TextInput_Type = 8
)

var TextInput_Type_name = map[int32]string{
	0: "autoByType",
	2: "datetime",
	3: "emailAddress",
	4: "multiline",
	5: "number",
	6: "phone",
	7: "text",
	8: "url",
}
var TextInput_Type_value = map[string]int32{
	"autoByType":   0,
	"datetime":     2,
	"emailAddress": 3,
	"multiline":    4,
	"number":       5,
	"phone":        6,
	"text":         7,
	"url":          8,
}

func (x TextInput_Type) String() string {
	return proto.EnumName(TextInput_Type_name, int32(x))
}
func (TextInput_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_form_00aa4113bc49fc04, []int{2, 0}
}

type RadioInput_Type int32

const (
	RadioInput_radio RadioInput_Type = 0
	// extract a new message?
	RadioInput_dropdown         RadioInput_Type = 1
	RadioInput_segmentedControl RadioInput_Type = 2
)

var RadioInput_Type_name = map[int32]string{
	0: "radio",
	1: "dropdown",
	2: "segmentedControl",
}
var RadioInput_Type_value = map[string]int32{
	"radio":            0,
	"dropdown":         1,
	"segmentedControl": 2,
}

func (x RadioInput_Type) String() string {
	return proto.EnumName(RadioInput_Type_name, int32(x))
}
func (RadioInput_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_form_00aa4113bc49fc04, []int{9, 0}
}

type ListInput_Type int32

const (
	// values must be checked from fixed list
	ListInput_checkbox ListInput_Type = 0
	// values can be others
	ListInput_chips ListInput_Type = 1
)

var ListInput_Type_name = map[int32]string{
	0: "checkbox",
	1: "chips",
}
var ListInput_Type_value = map[string]int32{
	"checkbox": 0,
	"chips":    1,
}

func (x ListInput_Type) String() string {
	return proto.EnumName(ListInput_Type_name, int32(x))
}
func (ListInput_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_form_00aa4113bc49fc04, []int{11, 0}
}

type DatetimePickerInput_Type int32

const (
	DatetimePickerInput_date DatetimePickerInput_Type = 0
	DatetimePickerInput_time DatetimePickerInput_Type = 1
	DatetimePickerInput_both DatetimePickerInput_Type = 2
)

var DatetimePickerInput_Type_name = map[int32]string{
	0: "date",
	1: "time",
	2: "both",
}
var DatetimePickerInput_Type_value = map[string]int32{
	"date": 0,
	"time": 1,
	"both": 2,
}

func (x DatetimePickerInput_Type) String() string {
	return proto.EnumName(DatetimePickerInput_Type_name, int32(x))
}
func (DatetimePickerInput_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_form_00aa4113bc49fc04, []int{12, 0}
}

type InputOption struct {
	Icon                 MaterialIcon `protobuf:"varint,1,opt,name=icon,proto3,enum=form.MaterialIcon" json:"icon,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *InputOption) Reset()         { *m = InputOption{} }
func (m *InputOption) String() string { return proto.CompactTextString(m) }
func (*InputOption) ProtoMessage()    {}
func (*InputOption) Descriptor() ([]byte, []int) {
	return fileDescriptor_form_00aa4113bc49fc04, []int{0}
}
func (m *InputOption) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InputOption.Unmarshal(m, b)
}
func (m *InputOption) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InputOption.Marshal(b, m, deterministic)
}
func (dst *InputOption) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InputOption.Merge(dst, src)
}
func (m *InputOption) XXX_Size() int {
	return xxx_messageInfo_InputOption.Size(m)
}
func (m *InputOption) XXX_DiscardUnknown() {
	xxx_messageInfo_InputOption.DiscardUnknown(m)
}

var xxx_messageInfo_InputOption proto.InternalMessageInfo

func (m *InputOption) GetIcon() MaterialIcon {
	if m != nil {
		return m.Icon
	}
	return MaterialIcon_noMaterialIcon
}

type Field struct {
	Decoration  *InputDecoration `protobuf:"bytes,1,opt,name=decoration,proto3" json:"decoration,omitempty"`
	Hide        bool             `protobuf:"varint,2,opt,name=hide,proto3" json:"hide,omitempty"`
	Enabled     bool             `protobuf:"varint,3,opt,name=enabled,proto3" json:"enabled,omitempty"`
	EnsureAgain bool             `protobuf:"varint,4,opt,name=ensureAgain,proto3" json:"ensureAgain,omitempty"`
	// not for bool?
	EmptyAsNoChange bool `protobuf:"varint,5,opt,name=emptyAsNoChange,proto3" json:"emptyAsNoChange,omitempty"`
	DisableDesc     bool `protobuf:"varint,6,opt,name=disableDesc,proto3" json:"disableDesc,omitempty"`
	// Types that are valid to be assigned to Type:
	//	*Field_Text
	//	*Field_TypeAhead
	//	*Field_Signature
	//	*Field_Number
	//	*Field_Stepper
	//	*Field_Slider
	//	*Field_Rate
	//	*Field_Radio
	//	*Field_BoolSwitch
	//	*Field_List
	//	*Field_Datetime
	Type                 isField_Type `protobuf_oneof:"type"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Field) Reset()         { *m = Field{} }
func (m *Field) String() string { return proto.CompactTextString(m) }
func (*Field) ProtoMessage()    {}
func (*Field) Descriptor() ([]byte, []int) {
	return fileDescriptor_form_00aa4113bc49fc04, []int{1}
}
func (m *Field) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Field.Unmarshal(m, b)
}
func (m *Field) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Field.Marshal(b, m, deterministic)
}
func (dst *Field) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Field.Merge(dst, src)
}
func (m *Field) XXX_Size() int {
	return xxx_messageInfo_Field.Size(m)
}
func (m *Field) XXX_DiscardUnknown() {
	xxx_messageInfo_Field.DiscardUnknown(m)
}

var xxx_messageInfo_Field proto.InternalMessageInfo

type isField_Type interface {
	isField_Type()
}

type Field_Text struct {
	Text *TextInput `protobuf:"bytes,11,opt,name=text,proto3,oneof"`
}
type Field_TypeAhead struct {
	TypeAhead *TypeAheadInput `protobuf:"bytes,12,opt,name=typeAhead,proto3,oneof"`
}
type Field_Signature struct {
	Signature *SignatureInput `protobuf:"bytes,13,opt,name=signature,proto3,oneof"`
}
type Field_Number struct {
	Number *NumberInput `protobuf:"bytes,14,opt,name=number,proto3,oneof"`
}
type Field_Stepper struct {
	Stepper *StepperInput `protobuf:"bytes,15,opt,name=stepper,proto3,oneof"`
}
type Field_Slider struct {
	Slider *SliderInput `protobuf:"bytes,16,opt,name=slider,proto3,oneof"`
}
type Field_Rate struct {
	Rate *RateInput `protobuf:"bytes,17,opt,name=rate,proto3,oneof"`
}
type Field_Radio struct {
	Radio *RadioInput `protobuf:"bytes,18,opt,name=radio,proto3,oneof"`
}
type Field_BoolSwitch struct {
	BoolSwitch *SwitchInput `protobuf:"bytes,19,opt,name=boolSwitch,proto3,oneof"`
}
type Field_List struct {
	List *ListInput `protobuf:"bytes,20,opt,name=list,proto3,oneof"`
}
type Field_Datetime struct {
	Datetime *DatetimePickerInput `protobuf:"bytes,21,opt,name=datetime,proto3,oneof"`
}

func (*Field_Text) isField_Type()       {}
func (*Field_TypeAhead) isField_Type()  {}
func (*Field_Signature) isField_Type()  {}
func (*Field_Number) isField_Type()     {}
func (*Field_Stepper) isField_Type()    {}
func (*Field_Slider) isField_Type()     {}
func (*Field_Rate) isField_Type()       {}
func (*Field_Radio) isField_Type()      {}
func (*Field_BoolSwitch) isField_Type() {}
func (*Field_List) isField_Type()       {}
func (*Field_Datetime) isField_Type()   {}

func (m *Field) GetType() isField_Type {
	if m != nil {
		return m.Type
	}
	return nil
}

func (m *Field) GetDecoration() *InputDecoration {
	if m != nil {
		return m.Decoration
	}
	return nil
}

func (m *Field) GetHide() bool {
	if m != nil {
		return m.Hide
	}
	return false
}

func (m *Field) GetEnabled() bool {
	if m != nil {
		return m.Enabled
	}
	return false
}

func (m *Field) GetEnsureAgain() bool {
	if m != nil {
		return m.EnsureAgain
	}
	return false
}

func (m *Field) GetEmptyAsNoChange() bool {
	if m != nil {
		return m.EmptyAsNoChange
	}
	return false
}

func (m *Field) GetDisableDesc() bool {
	if m != nil {
		return m.DisableDesc
	}
	return false
}

func (m *Field) GetText() *TextInput {
	if x, ok := m.GetType().(*Field_Text); ok {
		return x.Text
	}
	return nil
}

func (m *Field) GetTypeAhead() *TypeAheadInput {
	if x, ok := m.GetType().(*Field_TypeAhead); ok {
		return x.TypeAhead
	}
	return nil
}

func (m *Field) GetSignature() *SignatureInput {
	if x, ok := m.GetType().(*Field_Signature); ok {
		return x.Signature
	}
	return nil
}

func (m *Field) GetNumber() *NumberInput {
	if x, ok := m.GetType().(*Field_Number); ok {
		return x.Number
	}
	return nil
}

func (m *Field) GetStepper() *StepperInput {
	if x, ok := m.GetType().(*Field_Stepper); ok {
		return x.Stepper
	}
	return nil
}

func (m *Field) GetSlider() *SliderInput {
	if x, ok := m.GetType().(*Field_Slider); ok {
		return x.Slider
	}
	return nil
}

func (m *Field) GetRate() *RateInput {
	if x, ok := m.GetType().(*Field_Rate); ok {
		return x.Rate
	}
	return nil
}

func (m *Field) GetRadio() *RadioInput {
	if x, ok := m.GetType().(*Field_Radio); ok {
		return x.Radio
	}
	return nil
}

func (m *Field) GetBoolSwitch() *SwitchInput {
	if x, ok := m.GetType().(*Field_BoolSwitch); ok {
		return x.BoolSwitch
	}
	return nil
}

func (m *Field) GetList() *ListInput {
	if x, ok := m.GetType().(*Field_List); ok {
		return x.List
	}
	return nil
}

func (m *Field) GetDatetime() *DatetimePickerInput {
	if x, ok := m.GetType().(*Field_Datetime); ok {
		return x.Datetime
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*Field) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _Field_OneofMarshaler, _Field_OneofUnmarshaler, _Field_OneofSizer, []interface{}{
		(*Field_Text)(nil),
		(*Field_TypeAhead)(nil),
		(*Field_Signature)(nil),
		(*Field_Number)(nil),
		(*Field_Stepper)(nil),
		(*Field_Slider)(nil),
		(*Field_Rate)(nil),
		(*Field_Radio)(nil),
		(*Field_BoolSwitch)(nil),
		(*Field_List)(nil),
		(*Field_Datetime)(nil),
	}
}

func _Field_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*Field)
	// type
	switch x := m.Type.(type) {
	case *Field_Text:
		b.EncodeVarint(11<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Text); err != nil {
			return err
		}
	case *Field_TypeAhead:
		b.EncodeVarint(12<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.TypeAhead); err != nil {
			return err
		}
	case *Field_Signature:
		b.EncodeVarint(13<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Signature); err != nil {
			return err
		}
	case *Field_Number:
		b.EncodeVarint(14<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Number); err != nil {
			return err
		}
	case *Field_Stepper:
		b.EncodeVarint(15<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Stepper); err != nil {
			return err
		}
	case *Field_Slider:
		b.EncodeVarint(16<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Slider); err != nil {
			return err
		}
	case *Field_Rate:
		b.EncodeVarint(17<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Rate); err != nil {
			return err
		}
	case *Field_Radio:
		b.EncodeVarint(18<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Radio); err != nil {
			return err
		}
	case *Field_BoolSwitch:
		b.EncodeVarint(19<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.BoolSwitch); err != nil {
			return err
		}
	case *Field_List:
		b.EncodeVarint(20<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.List); err != nil {
			return err
		}
	case *Field_Datetime:
		b.EncodeVarint(21<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Datetime); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("Field.Type has unexpected type %T", x)
	}
	return nil
}

func _Field_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*Field)
	switch tag {
	case 11: // type.text
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(TextInput)
		err := b.DecodeMessage(msg)
		m.Type = &Field_Text{msg}
		return true, err
	case 12: // type.typeAhead
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(TypeAheadInput)
		err := b.DecodeMessage(msg)
		m.Type = &Field_TypeAhead{msg}
		return true, err
	case 13: // type.signature
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(SignatureInput)
		err := b.DecodeMessage(msg)
		m.Type = &Field_Signature{msg}
		return true, err
	case 14: // type.number
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(NumberInput)
		err := b.DecodeMessage(msg)
		m.Type = &Field_Number{msg}
		return true, err
	case 15: // type.stepper
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(StepperInput)
		err := b.DecodeMessage(msg)
		m.Type = &Field_Stepper{msg}
		return true, err
	case 16: // type.slider
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(SliderInput)
		err := b.DecodeMessage(msg)
		m.Type = &Field_Slider{msg}
		return true, err
	case 17: // type.rate
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(RateInput)
		err := b.DecodeMessage(msg)
		m.Type = &Field_Rate{msg}
		return true, err
	case 18: // type.radio
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(RadioInput)
		err := b.DecodeMessage(msg)
		m.Type = &Field_Radio{msg}
		return true, err
	case 19: // type.boolSwitch
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(SwitchInput)
		err := b.DecodeMessage(msg)
		m.Type = &Field_BoolSwitch{msg}
		return true, err
	case 20: // type.list
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(ListInput)
		err := b.DecodeMessage(msg)
		m.Type = &Field_List{msg}
		return true, err
	case 21: // type.datetime
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(DatetimePickerInput)
		err := b.DecodeMessage(msg)
		m.Type = &Field_Datetime{msg}
		return true, err
	default:
		return false, nil
	}
}

func _Field_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*Field)
	// type
	switch x := m.Type.(type) {
	case *Field_Text:
		s := proto.Size(x.Text)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Field_TypeAhead:
		s := proto.Size(x.TypeAhead)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Field_Signature:
		s := proto.Size(x.Signature)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Field_Number:
		s := proto.Size(x.Number)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Field_Stepper:
		s := proto.Size(x.Stepper)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Field_Slider:
		s := proto.Size(x.Slider)
		n += 2 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Field_Rate:
		s := proto.Size(x.Rate)
		n += 2 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Field_Radio:
		s := proto.Size(x.Radio)
		n += 2 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Field_BoolSwitch:
		s := proto.Size(x.BoolSwitch)
		n += 2 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Field_List:
		s := proto.Size(x.List)
		n += 2 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Field_Datetime:
		s := proto.Size(x.Datetime)
		n += 2 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type TextInput struct {
	KeyboardType         TextInput_Type `protobuf:"varint,1,opt,name=keyboardType,proto3,enum=form.TextInput_Type" json:"keyboardType,omitempty"`
	ObscureText          bool           `protobuf:"varint,2,opt,name=obscureText,proto3" json:"obscureText,omitempty"`
	Autocorrect          bool           `protobuf:"varint,3,opt,name=autocorrect,proto3" json:"autocorrect,omitempty"`
	MaxLines             int32          `protobuf:"varint,4,opt,name=maxLines,proto3" json:"maxLines,omitempty"`
	MaxLengthEnforced    bool           `protobuf:"varint,5,opt,name=maxLengthEnforced,proto3" json:"maxLengthEnforced,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *TextInput) Reset()         { *m = TextInput{} }
func (m *TextInput) String() string { return proto.CompactTextString(m) }
func (*TextInput) ProtoMessage()    {}
func (*TextInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_form_00aa4113bc49fc04, []int{2}
}
func (m *TextInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TextInput.Unmarshal(m, b)
}
func (m *TextInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TextInput.Marshal(b, m, deterministic)
}
func (dst *TextInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TextInput.Merge(dst, src)
}
func (m *TextInput) XXX_Size() int {
	return xxx_messageInfo_TextInput.Size(m)
}
func (m *TextInput) XXX_DiscardUnknown() {
	xxx_messageInfo_TextInput.DiscardUnknown(m)
}

var xxx_messageInfo_TextInput proto.InternalMessageInfo

func (m *TextInput) GetKeyboardType() TextInput_Type {
	if m != nil {
		return m.KeyboardType
	}
	return TextInput_autoByType
}

func (m *TextInput) GetObscureText() bool {
	if m != nil {
		return m.ObscureText
	}
	return false
}

func (m *TextInput) GetAutocorrect() bool {
	if m != nil {
		return m.Autocorrect
	}
	return false
}

func (m *TextInput) GetMaxLines() int32 {
	if m != nil {
		return m.MaxLines
	}
	return 0
}

func (m *TextInput) GetMaxLengthEnforced() bool {
	if m != nil {
		return m.MaxLengthEnforced
	}
	return false
}

type TypeAheadInput struct {
	// Types that are valid to be assigned to Builder:
	//	*TypeAheadInput_CodeAccessor
	//	*TypeAheadInput_FromEnum
	Builder              isTypeAheadInput_Builder `protobuf_oneof:"builder"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *TypeAheadInput) Reset()         { *m = TypeAheadInput{} }
func (m *TypeAheadInput) String() string { return proto.CompactTextString(m) }
func (*TypeAheadInput) ProtoMessage()    {}
func (*TypeAheadInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_form_00aa4113bc49fc04, []int{3}
}
func (m *TypeAheadInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TypeAheadInput.Unmarshal(m, b)
}
func (m *TypeAheadInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TypeAheadInput.Marshal(b, m, deterministic)
}
func (dst *TypeAheadInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TypeAheadInput.Merge(dst, src)
}
func (m *TypeAheadInput) XXX_Size() int {
	return xxx_messageInfo_TypeAheadInput.Size(m)
}
func (m *TypeAheadInput) XXX_DiscardUnknown() {
	xxx_messageInfo_TypeAheadInput.DiscardUnknown(m)
}

var xxx_messageInfo_TypeAheadInput proto.InternalMessageInfo

type isTypeAheadInput_Builder interface {
	isTypeAheadInput_Builder()
}

type TypeAheadInput_CodeAccessor struct {
	CodeAccessor string `protobuf:"bytes,1,opt,name=codeAccessor,proto3,oneof"`
}
type TypeAheadInput_FromEnum struct {
	FromEnum bool `protobuf:"varint,2,opt,name=fromEnum,proto3,oneof"`
}

func (*TypeAheadInput_CodeAccessor) isTypeAheadInput_Builder() {}
func (*TypeAheadInput_FromEnum) isTypeAheadInput_Builder()     {}

func (m *TypeAheadInput) GetBuilder() isTypeAheadInput_Builder {
	if m != nil {
		return m.Builder
	}
	return nil
}

func (m *TypeAheadInput) GetCodeAccessor() string {
	if x, ok := m.GetBuilder().(*TypeAheadInput_CodeAccessor); ok {
		return x.CodeAccessor
	}
	return ""
}

func (m *TypeAheadInput) GetFromEnum() bool {
	if x, ok := m.GetBuilder().(*TypeAheadInput_FromEnum); ok {
		return x.FromEnum
	}
	return false
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*TypeAheadInput) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _TypeAheadInput_OneofMarshaler, _TypeAheadInput_OneofUnmarshaler, _TypeAheadInput_OneofSizer, []interface{}{
		(*TypeAheadInput_CodeAccessor)(nil),
		(*TypeAheadInput_FromEnum)(nil),
	}
}

func _TypeAheadInput_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*TypeAheadInput)
	// builder
	switch x := m.Builder.(type) {
	case *TypeAheadInput_CodeAccessor:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		b.EncodeStringBytes(x.CodeAccessor)
	case *TypeAheadInput_FromEnum:
		t := uint64(0)
		if x.FromEnum {
			t = 1
		}
		b.EncodeVarint(2<<3 | proto.WireVarint)
		b.EncodeVarint(t)
	case nil:
	default:
		return fmt.Errorf("TypeAheadInput.Builder has unexpected type %T", x)
	}
	return nil
}

func _TypeAheadInput_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*TypeAheadInput)
	switch tag {
	case 1: // builder.codeAccessor
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeStringBytes()
		m.Builder = &TypeAheadInput_CodeAccessor{x}
		return true, err
	case 2: // builder.fromEnum
		if wire != proto.WireVarint {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeVarint()
		m.Builder = &TypeAheadInput_FromEnum{x != 0}
		return true, err
	default:
		return false, nil
	}
}

func _TypeAheadInput_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*TypeAheadInput)
	// builder
	switch x := m.Builder.(type) {
	case *TypeAheadInput_CodeAccessor:
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(len(x.CodeAccessor)))
		n += len(x.CodeAccessor)
	case *TypeAheadInput_FromEnum:
		n += 1 // tag and wire
		n += 1
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type SignatureInput struct {
	Width                float64        `protobuf:"fixed64,1,opt,name=width,proto3" json:"width,omitempty"`
	Height               float64        `protobuf:"fixed64,2,opt,name=height,proto3" json:"height,omitempty"`
	BackgroundColor      *MaterialColor `protobuf:"bytes,3,opt,name=backgroundColor,proto3" json:"backgroundColor,omitempty"`
	PenColor             *MaterialColor `protobuf:"bytes,4,opt,name=penColor,proto3" json:"penColor,omitempty"`
	PenStrokeWidth       float64        `protobuf:"fixed64,5,opt,name=penStrokeWidth,proto3" json:"penStrokeWidth,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *SignatureInput) Reset()         { *m = SignatureInput{} }
func (m *SignatureInput) String() string { return proto.CompactTextString(m) }
func (*SignatureInput) ProtoMessage()    {}
func (*SignatureInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_form_00aa4113bc49fc04, []int{4}
}
func (m *SignatureInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignatureInput.Unmarshal(m, b)
}
func (m *SignatureInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignatureInput.Marshal(b, m, deterministic)
}
func (dst *SignatureInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignatureInput.Merge(dst, src)
}
func (m *SignatureInput) XXX_Size() int {
	return xxx_messageInfo_SignatureInput.Size(m)
}
func (m *SignatureInput) XXX_DiscardUnknown() {
	xxx_messageInfo_SignatureInput.DiscardUnknown(m)
}

var xxx_messageInfo_SignatureInput proto.InternalMessageInfo

func (m *SignatureInput) GetWidth() float64 {
	if m != nil {
		return m.Width
	}
	return 0
}

func (m *SignatureInput) GetHeight() float64 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *SignatureInput) GetBackgroundColor() *MaterialColor {
	if m != nil {
		return m.BackgroundColor
	}
	return nil
}

func (m *SignatureInput) GetPenColor() *MaterialColor {
	if m != nil {
		return m.PenColor
	}
	return nil
}

func (m *SignatureInput) GetPenStrokeWidth() float64 {
	if m != nil {
		return m.PenStrokeWidth
	}
	return 0
}

type NumberInput struct {
	FullUnit             bool      `protobuf:"varint,1,opt,name=fullUnit,proto3" json:"fullUnit,omitempty"`
	UnitPlace            UnitPlace `protobuf:"varint,2,opt,name=unitPlace,proto3,enum=form.UnitPlace" json:"unitPlace,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *NumberInput) Reset()         { *m = NumberInput{} }
func (m *NumberInput) String() string { return proto.CompactTextString(m) }
func (*NumberInput) ProtoMessage()    {}
func (*NumberInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_form_00aa4113bc49fc04, []int{5}
}
func (m *NumberInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NumberInput.Unmarshal(m, b)
}
func (m *NumberInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NumberInput.Marshal(b, m, deterministic)
}
func (dst *NumberInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NumberInput.Merge(dst, src)
}
func (m *NumberInput) XXX_Size() int {
	return xxx_messageInfo_NumberInput.Size(m)
}
func (m *NumberInput) XXX_DiscardUnknown() {
	xxx_messageInfo_NumberInput.DiscardUnknown(m)
}

var xxx_messageInfo_NumberInput proto.InternalMessageInfo

func (m *NumberInput) GetFullUnit() bool {
	if m != nil {
		return m.FullUnit
	}
	return false
}

func (m *NumberInput) GetUnitPlace() UnitPlace {
	if m != nil {
		return m.UnitPlace
	}
	return UnitPlace_noUnitPlace
}

type StepperInput struct {
	FullUnit             bool      `protobuf:"varint,1,opt,name=fullUnit,proto3" json:"fullUnit,omitempty"`
	UnitPlace            UnitPlace `protobuf:"varint,2,opt,name=unitPlace,proto3,enum=form.UnitPlace" json:"unitPlace,omitempty"`
	Step                 uint32    `protobuf:"varint,3,opt,name=step,proto3" json:"step,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *StepperInput) Reset()         { *m = StepperInput{} }
func (m *StepperInput) String() string { return proto.CompactTextString(m) }
func (*StepperInput) ProtoMessage()    {}
func (*StepperInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_form_00aa4113bc49fc04, []int{6}
}
func (m *StepperInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StepperInput.Unmarshal(m, b)
}
func (m *StepperInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StepperInput.Marshal(b, m, deterministic)
}
func (dst *StepperInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StepperInput.Merge(dst, src)
}
func (m *StepperInput) XXX_Size() int {
	return xxx_messageInfo_StepperInput.Size(m)
}
func (m *StepperInput) XXX_DiscardUnknown() {
	xxx_messageInfo_StepperInput.DiscardUnknown(m)
}

var xxx_messageInfo_StepperInput proto.InternalMessageInfo

func (m *StepperInput) GetFullUnit() bool {
	if m != nil {
		return m.FullUnit
	}
	return false
}

func (m *StepperInput) GetUnitPlace() UnitPlace {
	if m != nil {
		return m.UnitPlace
	}
	return UnitPlace_noUnitPlace
}

func (m *StepperInput) GetStep() uint32 {
	if m != nil {
		return m.Step
	}
	return 0
}

type SliderInput struct {
	FullUnit             bool      `protobuf:"varint,1,opt,name=fullUnit,proto3" json:"fullUnit,omitempty"`
	UnitPlace            UnitPlace `protobuf:"varint,2,opt,name=unitPlace,proto3,enum=form.UnitPlace" json:"unitPlace,omitempty"`
	Divisions            uint32    `protobuf:"varint,3,opt,name=divisions,proto3" json:"divisions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *SliderInput) Reset()         { *m = SliderInput{} }
func (m *SliderInput) String() string { return proto.CompactTextString(m) }
func (*SliderInput) ProtoMessage()    {}
func (*SliderInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_form_00aa4113bc49fc04, []int{7}
}
func (m *SliderInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SliderInput.Unmarshal(m, b)
}
func (m *SliderInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SliderInput.Marshal(b, m, deterministic)
}
func (dst *SliderInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SliderInput.Merge(dst, src)
}
func (m *SliderInput) XXX_Size() int {
	return xxx_messageInfo_SliderInput.Size(m)
}
func (m *SliderInput) XXX_DiscardUnknown() {
	xxx_messageInfo_SliderInput.DiscardUnknown(m)
}

var xxx_messageInfo_SliderInput proto.InternalMessageInfo

func (m *SliderInput) GetFullUnit() bool {
	if m != nil {
		return m.FullUnit
	}
	return false
}

func (m *SliderInput) GetUnitPlace() UnitPlace {
	if m != nil {
		return m.UnitPlace
	}
	return UnitPlace_noUnitPlace
}

func (m *SliderInput) GetDivisions() uint32 {
	if m != nil {
		return m.Divisions
	}
	return 0
}

type RateInput struct {
	Icon                 MaterialIcon `protobuf:"varint,1,opt,name=icon,proto3,enum=form.MaterialIcon" json:"icon,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *RateInput) Reset()         { *m = RateInput{} }
func (m *RateInput) String() string { return proto.CompactTextString(m) }
func (*RateInput) ProtoMessage()    {}
func (*RateInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_form_00aa4113bc49fc04, []int{8}
}
func (m *RateInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RateInput.Unmarshal(m, b)
}
func (m *RateInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RateInput.Marshal(b, m, deterministic)
}
func (dst *RateInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RateInput.Merge(dst, src)
}
func (m *RateInput) XXX_Size() int {
	return xxx_messageInfo_RateInput.Size(m)
}
func (m *RateInput) XXX_DiscardUnknown() {
	xxx_messageInfo_RateInput.DiscardUnknown(m)
}

var xxx_messageInfo_RateInput proto.InternalMessageInfo

func (m *RateInput) GetIcon() MaterialIcon {
	if m != nil {
		return m.Icon
	}
	return MaterialIcon_noMaterialIcon
}

type RadioInput struct {
	Type RadioInput_Type `protobuf:"varint,1,opt,name=type,proto3,enum=form.RadioInput_Type" json:"type,omitempty"`
	// Types that are valid to be assigned to Builder:
	//	*RadioInput_CodeAccessor
	//	*RadioInput_FromEnum
	Builder              isRadioInput_Builder `protobuf_oneof:"builder"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *RadioInput) Reset()         { *m = RadioInput{} }
func (m *RadioInput) String() string { return proto.CompactTextString(m) }
func (*RadioInput) ProtoMessage()    {}
func (*RadioInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_form_00aa4113bc49fc04, []int{9}
}
func (m *RadioInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RadioInput.Unmarshal(m, b)
}
func (m *RadioInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RadioInput.Marshal(b, m, deterministic)
}
func (dst *RadioInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RadioInput.Merge(dst, src)
}
func (m *RadioInput) XXX_Size() int {
	return xxx_messageInfo_RadioInput.Size(m)
}
func (m *RadioInput) XXX_DiscardUnknown() {
	xxx_messageInfo_RadioInput.DiscardUnknown(m)
}

var xxx_messageInfo_RadioInput proto.InternalMessageInfo

type isRadioInput_Builder interface {
	isRadioInput_Builder()
}

type RadioInput_CodeAccessor struct {
	CodeAccessor string `protobuf:"bytes,2,opt,name=codeAccessor,proto3,oneof"`
}
type RadioInput_FromEnum struct {
	FromEnum bool `protobuf:"varint,3,opt,name=fromEnum,proto3,oneof"`
}

func (*RadioInput_CodeAccessor) isRadioInput_Builder() {}
func (*RadioInput_FromEnum) isRadioInput_Builder()     {}

func (m *RadioInput) GetBuilder() isRadioInput_Builder {
	if m != nil {
		return m.Builder
	}
	return nil
}

func (m *RadioInput) GetType() RadioInput_Type {
	if m != nil {
		return m.Type
	}
	return RadioInput_radio
}

func (m *RadioInput) GetCodeAccessor() string {
	if x, ok := m.GetBuilder().(*RadioInput_CodeAccessor); ok {
		return x.CodeAccessor
	}
	return ""
}

func (m *RadioInput) GetFromEnum() bool {
	if x, ok := m.GetBuilder().(*RadioInput_FromEnum); ok {
		return x.FromEnum
	}
	return false
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*RadioInput) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _RadioInput_OneofMarshaler, _RadioInput_OneofUnmarshaler, _RadioInput_OneofSizer, []interface{}{
		(*RadioInput_CodeAccessor)(nil),
		(*RadioInput_FromEnum)(nil),
	}
}

func _RadioInput_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*RadioInput)
	// builder
	switch x := m.Builder.(type) {
	case *RadioInput_CodeAccessor:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		b.EncodeStringBytes(x.CodeAccessor)
	case *RadioInput_FromEnum:
		t := uint64(0)
		if x.FromEnum {
			t = 1
		}
		b.EncodeVarint(3<<3 | proto.WireVarint)
		b.EncodeVarint(t)
	case nil:
	default:
		return fmt.Errorf("RadioInput.Builder has unexpected type %T", x)
	}
	return nil
}

func _RadioInput_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*RadioInput)
	switch tag {
	case 2: // builder.codeAccessor
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeStringBytes()
		m.Builder = &RadioInput_CodeAccessor{x}
		return true, err
	case 3: // builder.fromEnum
		if wire != proto.WireVarint {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeVarint()
		m.Builder = &RadioInput_FromEnum{x != 0}
		return true, err
	default:
		return false, nil
	}
}

func _RadioInput_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*RadioInput)
	// builder
	switch x := m.Builder.(type) {
	case *RadioInput_CodeAccessor:
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(len(x.CodeAccessor)))
		n += len(x.CodeAccessor)
	case *RadioInput_FromEnum:
		n += 1 // tag and wire
		n += 1
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type SwitchInput struct {
	Checkbox             bool     `protobuf:"varint,1,opt,name=checkbox,proto3" json:"checkbox,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SwitchInput) Reset()         { *m = SwitchInput{} }
func (m *SwitchInput) String() string { return proto.CompactTextString(m) }
func (*SwitchInput) ProtoMessage()    {}
func (*SwitchInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_form_00aa4113bc49fc04, []int{10}
}
func (m *SwitchInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SwitchInput.Unmarshal(m, b)
}
func (m *SwitchInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SwitchInput.Marshal(b, m, deterministic)
}
func (dst *SwitchInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SwitchInput.Merge(dst, src)
}
func (m *SwitchInput) XXX_Size() int {
	return xxx_messageInfo_SwitchInput.Size(m)
}
func (m *SwitchInput) XXX_DiscardUnknown() {
	xxx_messageInfo_SwitchInput.DiscardUnknown(m)
}

var xxx_messageInfo_SwitchInput proto.InternalMessageInfo

func (m *SwitchInput) GetCheckbox() bool {
	if m != nil {
		return m.Checkbox
	}
	return false
}

type ListInput struct {
	Type ListInput_Type `protobuf:"varint,1,opt,name=type,proto3,enum=form.ListInput_Type" json:"type,omitempty"`
	// Types that are valid to be assigned to Builder:
	//	*ListInput_CodeAccessor
	//	*ListInput_FromEnum
	Builder              isListInput_Builder `protobuf_oneof:"builder"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *ListInput) Reset()         { *m = ListInput{} }
func (m *ListInput) String() string { return proto.CompactTextString(m) }
func (*ListInput) ProtoMessage()    {}
func (*ListInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_form_00aa4113bc49fc04, []int{11}
}
func (m *ListInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListInput.Unmarshal(m, b)
}
func (m *ListInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListInput.Marshal(b, m, deterministic)
}
func (dst *ListInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListInput.Merge(dst, src)
}
func (m *ListInput) XXX_Size() int {
	return xxx_messageInfo_ListInput.Size(m)
}
func (m *ListInput) XXX_DiscardUnknown() {
	xxx_messageInfo_ListInput.DiscardUnknown(m)
}

var xxx_messageInfo_ListInput proto.InternalMessageInfo

type isListInput_Builder interface {
	isListInput_Builder()
}

type ListInput_CodeAccessor struct {
	CodeAccessor string `protobuf:"bytes,2,opt,name=codeAccessor,proto3,oneof"`
}
type ListInput_FromEnum struct {
	FromEnum bool `protobuf:"varint,3,opt,name=fromEnum,proto3,oneof"`
}

func (*ListInput_CodeAccessor) isListInput_Builder() {}
func (*ListInput_FromEnum) isListInput_Builder()     {}

func (m *ListInput) GetBuilder() isListInput_Builder {
	if m != nil {
		return m.Builder
	}
	return nil
}

func (m *ListInput) GetType() ListInput_Type {
	if m != nil {
		return m.Type
	}
	return ListInput_checkbox
}

func (m *ListInput) GetCodeAccessor() string {
	if x, ok := m.GetBuilder().(*ListInput_CodeAccessor); ok {
		return x.CodeAccessor
	}
	return ""
}

func (m *ListInput) GetFromEnum() bool {
	if x, ok := m.GetBuilder().(*ListInput_FromEnum); ok {
		return x.FromEnum
	}
	return false
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*ListInput) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _ListInput_OneofMarshaler, _ListInput_OneofUnmarshaler, _ListInput_OneofSizer, []interface{}{
		(*ListInput_CodeAccessor)(nil),
		(*ListInput_FromEnum)(nil),
	}
}

func _ListInput_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*ListInput)
	// builder
	switch x := m.Builder.(type) {
	case *ListInput_CodeAccessor:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		b.EncodeStringBytes(x.CodeAccessor)
	case *ListInput_FromEnum:
		t := uint64(0)
		if x.FromEnum {
			t = 1
		}
		b.EncodeVarint(3<<3 | proto.WireVarint)
		b.EncodeVarint(t)
	case nil:
	default:
		return fmt.Errorf("ListInput.Builder has unexpected type %T", x)
	}
	return nil
}

func _ListInput_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*ListInput)
	switch tag {
	case 2: // builder.codeAccessor
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeStringBytes()
		m.Builder = &ListInput_CodeAccessor{x}
		return true, err
	case 3: // builder.fromEnum
		if wire != proto.WireVarint {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeVarint()
		m.Builder = &ListInput_FromEnum{x != 0}
		return true, err
	default:
		return false, nil
	}
}

func _ListInput_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*ListInput)
	// builder
	switch x := m.Builder.(type) {
	case *ListInput_CodeAccessor:
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(len(x.CodeAccessor)))
		n += len(x.CodeAccessor)
	case *ListInput_FromEnum:
		n += 1 // tag and wire
		n += 1
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type DatetimePickerInput struct {
	Type DatetimePickerInput_Type `protobuf:"varint,1,opt,name=type,proto3,enum=form.DatetimePickerInput_Type" json:"type,omitempty"`
	// format must in target_package.TimeFormatNameRegister
	Format               string   `protobuf:"bytes,2,opt,name=format,proto3" json:"format,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DatetimePickerInput) Reset()         { *m = DatetimePickerInput{} }
func (m *DatetimePickerInput) String() string { return proto.CompactTextString(m) }
func (*DatetimePickerInput) ProtoMessage()    {}
func (*DatetimePickerInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_form_00aa4113bc49fc04, []int{12}
}
func (m *DatetimePickerInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DatetimePickerInput.Unmarshal(m, b)
}
func (m *DatetimePickerInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DatetimePickerInput.Marshal(b, m, deterministic)
}
func (dst *DatetimePickerInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DatetimePickerInput.Merge(dst, src)
}
func (m *DatetimePickerInput) XXX_Size() int {
	return xxx_messageInfo_DatetimePickerInput.Size(m)
}
func (m *DatetimePickerInput) XXX_DiscardUnknown() {
	xxx_messageInfo_DatetimePickerInput.DiscardUnknown(m)
}

var xxx_messageInfo_DatetimePickerInput proto.InternalMessageInfo

func (m *DatetimePickerInput) GetType() DatetimePickerInput_Type {
	if m != nil {
		return m.Type
	}
	return DatetimePickerInput_date
}

func (m *DatetimePickerInput) GetFormat() string {
	if m != nil {
		return m.Format
	}
	return ""
}

type InputDecoration struct {
	Icon                 MaterialIcon `protobuf:"varint,1,opt,name=icon,proto3,enum=form.MaterialIcon" json:"icon,omitempty"`
	PrefixIcon           MaterialIcon `protobuf:"varint,2,opt,name=prefixIcon,proto3,enum=form.MaterialIcon" json:"prefixIcon,omitempty"`
	SuffixIcon           MaterialIcon `protobuf:"varint,3,opt,name=suffixIcon,proto3,enum=form.MaterialIcon" json:"suffixIcon,omitempty"`
	HasCounter           bool         `protobuf:"varint,4,opt,name=hasCounter,proto3" json:"hasCounter,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *InputDecoration) Reset()         { *m = InputDecoration{} }
func (m *InputDecoration) String() string { return proto.CompactTextString(m) }
func (*InputDecoration) ProtoMessage()    {}
func (*InputDecoration) Descriptor() ([]byte, []int) {
	return fileDescriptor_form_00aa4113bc49fc04, []int{13}
}
func (m *InputDecoration) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InputDecoration.Unmarshal(m, b)
}
func (m *InputDecoration) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InputDecoration.Marshal(b, m, deterministic)
}
func (dst *InputDecoration) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InputDecoration.Merge(dst, src)
}
func (m *InputDecoration) XXX_Size() int {
	return xxx_messageInfo_InputDecoration.Size(m)
}
func (m *InputDecoration) XXX_DiscardUnknown() {
	xxx_messageInfo_InputDecoration.DiscardUnknown(m)
}

var xxx_messageInfo_InputDecoration proto.InternalMessageInfo

func (m *InputDecoration) GetIcon() MaterialIcon {
	if m != nil {
		return m.Icon
	}
	return MaterialIcon_noMaterialIcon
}

func (m *InputDecoration) GetPrefixIcon() MaterialIcon {
	if m != nil {
		return m.PrefixIcon
	}
	return MaterialIcon_noMaterialIcon
}

func (m *InputDecoration) GetSuffixIcon() MaterialIcon {
	if m != nil {
		return m.SuffixIcon
	}
	return MaterialIcon_noMaterialIcon
}

func (m *InputDecoration) GetHasCounter() bool {
	if m != nil {
		return m.HasCounter
	}
	return false
}

// TODO move to validate
type Date struct {
	// Types that are valid to be assigned to Utc:
	//	*Date_Unix
	//	*Date_Rfc3339
	Utc                  isDate_Utc `protobuf_oneof:"utc"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Date) Reset()         { *m = Date{} }
func (m *Date) String() string { return proto.CompactTextString(m) }
func (*Date) ProtoMessage()    {}
func (*Date) Descriptor() ([]byte, []int) {
	return fileDescriptor_form_00aa4113bc49fc04, []int{14}
}
func (m *Date) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Date.Unmarshal(m, b)
}
func (m *Date) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Date.Marshal(b, m, deterministic)
}
func (dst *Date) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Date.Merge(dst, src)
}
func (m *Date) XXX_Size() int {
	return xxx_messageInfo_Date.Size(m)
}
func (m *Date) XXX_DiscardUnknown() {
	xxx_messageInfo_Date.DiscardUnknown(m)
}

var xxx_messageInfo_Date proto.InternalMessageInfo

type isDate_Utc interface {
	isDate_Utc()
}

type Date_Unix struct {
	Unix int64 `protobuf:"varint,1,opt,name=unix,proto3,oneof"`
}
type Date_Rfc3339 struct {
	Rfc3339 string `protobuf:"bytes,2,opt,name=rfc3339,proto3,oneof"`
}

func (*Date_Unix) isDate_Utc()    {}
func (*Date_Rfc3339) isDate_Utc() {}

func (m *Date) GetUtc() isDate_Utc {
	if m != nil {
		return m.Utc
	}
	return nil
}

func (m *Date) GetUnix() int64 {
	if x, ok := m.GetUtc().(*Date_Unix); ok {
		return x.Unix
	}
	return 0
}

func (m *Date) GetRfc3339() string {
	if x, ok := m.GetUtc().(*Date_Rfc3339); ok {
		return x.Rfc3339
	}
	return ""
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*Date) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _Date_OneofMarshaler, _Date_OneofUnmarshaler, _Date_OneofSizer, []interface{}{
		(*Date_Unix)(nil),
		(*Date_Rfc3339)(nil),
	}
}

func _Date_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*Date)
	// utc
	switch x := m.Utc.(type) {
	case *Date_Unix:
		b.EncodeVarint(1<<3 | proto.WireVarint)
		b.EncodeVarint(uint64(x.Unix))
	case *Date_Rfc3339:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		b.EncodeStringBytes(x.Rfc3339)
	case nil:
	default:
		return fmt.Errorf("Date.Utc has unexpected type %T", x)
	}
	return nil
}

func _Date_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*Date)
	switch tag {
	case 1: // utc.unix
		if wire != proto.WireVarint {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeVarint()
		m.Utc = &Date_Unix{int64(x)}
		return true, err
	case 2: // utc.rfc3339
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeStringBytes()
		m.Utc = &Date_Rfc3339{x}
		return true, err
	default:
		return false, nil
	}
}

func _Date_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*Date)
	// utc
	switch x := m.Utc.(type) {
	case *Date_Unix:
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(x.Unix))
	case *Date_Rfc3339:
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(len(x.Rfc3339)))
		n += len(x.Rfc3339)
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

var E_DefaultField = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.EnumOptions)(nil),
	ExtensionType: (*Field)(nil),
	Field:         919112,
	Name:          "form.defaultField",
	Tag:           "bytes,919112,opt,name=defaultField",
	Filename:      "protos/form/form.proto",
}

var E_InputOption = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.EnumValueOptions)(nil),
	ExtensionType: (*InputOption)(nil),
	Field:         919112,
	Name:          "form.inputOption",
	Tag:           "bytes,919112,opt,name=inputOption",
	Filename:      "protos/form/form.proto",
}

var E_Entry = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.MessageOptions)(nil),
	ExtensionType: (*InputOption)(nil),
	Field:         919112,
	Name:          "form.entry",
	Tag:           "bytes,919112,opt,name=entry",
	Filename:      "protos/form/form.proto",
}

var E_Field = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FieldOptions)(nil),
	ExtensionType: (*Field)(nil),
	Field:         919112,
	Name:          "form.field",
	Tag:           "bytes,919112,opt,name=field",
	Filename:      "protos/form/form.proto",
}

func init() {
	proto.RegisterType((*InputOption)(nil), "form.InputOption")
	proto.RegisterType((*Field)(nil), "form.Field")
	proto.RegisterType((*TextInput)(nil), "form.TextInput")
	proto.RegisterType((*TypeAheadInput)(nil), "form.TypeAheadInput")
	proto.RegisterType((*SignatureInput)(nil), "form.SignatureInput")
	proto.RegisterType((*NumberInput)(nil), "form.NumberInput")
	proto.RegisterType((*StepperInput)(nil), "form.StepperInput")
	proto.RegisterType((*SliderInput)(nil), "form.SliderInput")
	proto.RegisterType((*RateInput)(nil), "form.RateInput")
	proto.RegisterType((*RadioInput)(nil), "form.RadioInput")
	proto.RegisterType((*SwitchInput)(nil), "form.SwitchInput")
	proto.RegisterType((*ListInput)(nil), "form.ListInput")
	proto.RegisterType((*DatetimePickerInput)(nil), "form.DatetimePickerInput")
	proto.RegisterType((*InputDecoration)(nil), "form.InputDecoration")
	proto.RegisterType((*Date)(nil), "form.Date")
	proto.RegisterEnum("form.UnitPlace", UnitPlace_name, UnitPlace_value)
	proto.RegisterEnum("form.TextInput_Type", TextInput_Type_name, TextInput_Type_value)
	proto.RegisterEnum("form.RadioInput_Type", RadioInput_Type_name, RadioInput_Type_value)
	proto.RegisterEnum("form.ListInput_Type", ListInput_Type_name, ListInput_Type_value)
	proto.RegisterEnum("form.DatetimePickerInput_Type", DatetimePickerInput_Type_name, DatetimePickerInput_Type_value)
	proto.RegisterExtension(E_DefaultField)
	proto.RegisterExtension(E_InputOption)
	proto.RegisterExtension(E_Entry)
	proto.RegisterExtension(E_Field)
}

func init() { proto.RegisterFile("protos/form/form.proto", fileDescriptor_form_00aa4113bc49fc04) }

var fileDescriptor_form_00aa4113bc49fc04 = []byte{
	// 1323 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xac, 0x57, 0xdd, 0x6e, 0xdc, 0x44,
	0x14, 0xee, 0x26, 0xbb, 0xc9, 0xfa, 0xec, 0x76, 0xe3, 0x4c, 0xd3, 0x62, 0x4a, 0x69, 0x8b, 0x55,
	0x50, 0x0b, 0x64, 0x57, 0x64, 0xa9, 0x68, 0x23, 0x21, 0x94, 0xb4, 0x45, 0x14, 0xf5, 0x4f, 0x0e,
	0x05, 0xc4, 0x0d, 0xf2, 0xcf, 0xac, 0x3d, 0x8a, 0xd7, 0x63, 0x8d, 0xc7, 0x6d, 0xf2, 0x04, 0xdc,
	0xf0, 0x1a, 0x3c, 0x06, 0x17, 0x48, 0x5c, 0xf0, 0x04, 0xbc, 0x01, 0xef, 0xc1, 0x99, 0x19, 0xdb,
	0xeb, 0xdd, 0xb4, 0xd0, 0x8b, 0xde, 0xac, 0x3c, 0xdf, 0xf9, 0xce, 0xf1, 0x39, 0x33, 0xe7, 0x7c,
	0x9e, 0x85, 0x4b, 0xb9, 0xe0, 0x92, 0x17, 0x93, 0x19, 0x17, 0x73, 0xfd, 0x33, 0xd6, 0x00, 0xe9,
	0xaa, 0xe7, 0xcb, 0xd7, 0x63, 0xce, 0xe3, 0x94, 0x4e, 0x34, 0x16, 0x94, 0xb3, 0x49, 0x44, 0x8b,
	0x50, 0xb0, 0x5c, 0x72, 0x61, 0x78, 0x97, 0xdf, 0x69, 0xfb, 0x87, 0x3c, 0x6d, 0x0c, 0x4b, 0x81,
	0x59, 0xc8, 0xb3, 0x0a, 0x7f, 0xaf, 0xc2, 0xcb, 0x8c, 0xc9, 0x62, 0x12, 0x96, 0x42, 0xd0, 0x2c,
	0x3c, 0xad, 0x8c, 0xce, 0x92, 0x51, 0xff, 0x1a, 0x8b, 0x7b, 0x1b, 0x06, 0x0f, 0xb3, 0xbc, 0x94,
	0x4f, 0x73, 0xc9, 0x78, 0x46, 0x3e, 0x82, 0xae, 0x8a, 0xe9, 0x74, 0xae, 0x77, 0x6e, 0x8e, 0xf6,
	0xc8, 0x58, 0x67, 0xfe, 0xd8, 0x97, 0x54, 0x30, 0x3f, 0x7d, 0x88, 0x16, 0x4f, 0xdb, 0xdd, 0x7f,
	0x7a, 0xd0, 0xfb, 0x9a, 0xd1, 0x34, 0x22, 0xb7, 0x01, 0x22, 0x1a, 0x72, 0xe1, 0x2b, 0x7f, 0xed,
	0x37, 0xd8, 0xbb, 0x68, 0xfc, 0x74, 0xe0, 0xfb, 0x8d, 0xd1, 0x6b, 0x11, 0x09, 0x81, 0x6e, 0xc2,
	0x22, 0xea, 0xac, 0xa1, 0x43, 0xdf, 0xd3, 0xcf, 0xc4, 0x81, 0x4d, 0x9a, 0xf9, 0x41, 0x4a, 0x23,
	0x67, 0x5d, 0xc3, 0xf5, 0x92, 0x5c, 0x87, 0x01, 0xcd, 0x8a, 0x52, 0xd0, 0x83, 0xd8, 0x67, 0x99,
	0xd3, 0xd5, 0xd6, 0x36, 0x44, 0x6e, 0xc2, 0x16, 0x9d, 0xe7, 0xf2, 0xf4, 0xa0, 0x78, 0xc2, 0xef,
	0x25, 0x7e, 0x16, 0x53, 0xa7, 0xa7, 0x59, 0xab, 0xb0, 0x8a, 0x15, 0xb1, 0x42, 0xc5, 0xbd, 0x8f,
	0x9b, 0xee, 0x6c, 0x98, 0x58, 0x2d, 0x88, 0x7c, 0x08, 0x5d, 0x49, 0x4f, 0xa4, 0x33, 0xd0, 0xc5,
	0x6c, 0x99, 0x62, 0xbe, 0x43, 0x44, 0x17, 0xf4, 0xcd, 0x39, 0x4f, 0x9b, 0xc9, 0xe7, 0x60, 0xc9,
	0xd3, 0x9c, 0x1e, 0x24, 0xd4, 0x8f, 0x9c, 0xa1, 0xe6, 0xee, 0x54, 0xdc, 0x1a, 0xae, 0x1d, 0x16,
	0x44, 0xe5, 0x55, 0xb0, 0x38, 0xf3, 0x25, 0xa6, 0xee, 0x9c, 0x6f, 0x7b, 0x1d, 0xd5, 0x70, 0xe3,
	0xd5, 0x10, 0xc9, 0x27, 0xb0, 0x91, 0x95, 0xf3, 0x80, 0x0a, 0x67, 0xa4, 0x5d, 0xb6, 0x8d, 0xcb,
	0x13, 0x8d, 0xd5, 0xfc, 0x8a, 0x42, 0xc6, 0xb0, 0x59, 0x48, 0x9a, 0xe7, 0xc8, 0xde, 0xd2, 0xec,
	0xea, 0x1c, 0x8f, 0x0c, 0x58, 0xd3, 0x6b, 0x92, 0x0a, 0x5e, 0xa4, 0x78, 0x00, 0xc2, 0xb1, 0xdb,
	0xc1, 0x8f, 0x34, 0xd6, 0x04, 0x37, 0x14, 0xb5, 0x39, 0x78, 0x84, 0xd4, 0xd9, 0x6e, 0x6f, 0x8e,
	0x87, 0x48, 0xb3, 0x39, 0xca, 0x8c, 0xe7, 0xd1, 0x13, 0x7e, 0xc4, 0xb8, 0x43, 0x34, 0xcf, 0xae,
	0x79, 0x08, 0xd5, 0x44, 0x43, 0x20, 0x53, 0x80, 0x80, 0xf3, 0xf4, 0xe8, 0x25, 0x93, 0x61, 0xe2,
	0x5c, 0x58, 0xca, 0x40, 0x63, 0x35, 0xbf, 0x45, 0x53, 0x59, 0xa4, 0xac, 0x90, 0xce, 0x4e, 0x3b,
	0x8b, 0x47, 0x88, 0x34, 0x59, 0x28, 0x33, 0xf9, 0x02, 0xfa, 0x11, 0x66, 0x23, 0xd9, 0x9c, 0x3a,
	0x17, 0x35, 0xf5, 0x5d, 0x43, 0xbd, 0x5f, 0xa1, 0xcf, 0x58, 0x78, 0xbc, 0xa8, 0xb1, 0x21, 0x1f,
	0x6e, 0x60, 0x0b, 0xe0, 0x91, 0xb9, 0x7f, 0xae, 0x81, 0xd5, 0x9c, 0x3c, 0xb9, 0x03, 0xc3, 0x63,
	0x7a, 0x1a, 0x70, 0x5f, 0x44, 0xea, 0x88, 0xab, 0x29, 0xd9, 0x59, 0x69, 0x10, 0x7d, 0xfc, 0xde,
	0x12, 0x53, 0x35, 0x1d, 0x0f, 0x0a, 0x9c, 0x4a, 0xaa, 0x68, 0x55, 0xd7, 0xb7, 0x21, 0xc5, 0xf0,
	0x4b, 0xc9, 0x71, 0x40, 0x04, 0x0d, 0x65, 0x35, 0x00, 0x6d, 0x88, 0x5c, 0x86, 0xfe, 0xdc, 0x3f,
	0x79, 0xc4, 0x32, 0x5a, 0xe8, 0x09, 0xe8, 0x79, 0xcd, 0x9a, 0x7c, 0x0a, 0xdb, 0xea, 0x99, 0x66,
	0xb1, 0x4c, 0x1e, 0x64, 0x98, 0x4f, 0x88, 0x43, 0x64, 0x06, 0xe0, 0xac, 0xc1, 0xe5, 0xd0, 0xd5,
	0x59, 0x8d, 0x00, 0xd4, 0x0b, 0x0e, 0x4f, 0xd5, 0xca, 0x3e, 0x47, 0x86, 0x8b, 0xed, 0xb2, 0xd7,
	0x88, 0x0d, 0x43, 0x3a, 0xf7, 0x59, 0x7a, 0x10, 0x45, 0x82, 0x16, 0x85, 0xbd, 0x4e, 0xce, 0x83,
	0x35, 0x2f, 0x53, 0xc9, 0x52, 0x7c, 0xa7, 0xdd, 0x25, 0x50, 0x37, 0xa5, 0xdd, 0x23, 0x16, 0xf4,
	0xf2, 0x84, 0x23, 0xbc, 0x41, 0xfa, 0x66, 0x7c, 0xec, 0x4d, 0xb2, 0x09, 0xeb, 0xa5, 0x48, 0xed,
	0xbe, 0xfb, 0x33, 0x8c, 0x96, 0x67, 0x82, 0xdc, 0x80, 0x61, 0xc8, 0x23, 0x7a, 0x10, 0x86, 0x18,
	0x9a, 0x0b, 0xbd, 0x95, 0x16, 0x1e, 0xc1, 0x12, 0x4a, 0xae, 0x40, 0x7f, 0x26, 0xf8, 0xfc, 0x01,
	0xbe, 0xc6, 0xec, 0x99, 0x3a, 0xa4, 0x1a, 0x39, 0xb4, 0x60, 0x33, 0x28, 0x59, 0x8a, 0x5d, 0xe9,
	0xfe, 0xdd, 0x81, 0xd1, 0xf2, 0xfc, 0x90, 0x1d, 0xe8, 0xbd, 0x64, 0x91, 0x4c, 0x74, 0xe8, 0x8e,
	0x67, 0x16, 0xe4, 0x12, 0x6c, 0x24, 0x94, 0xc5, 0x89, 0x39, 0x83, 0x8e, 0x57, 0xad, 0xc8, 0x97,
	0xb0, 0x15, 0xf8, 0xe1, 0x71, 0x2c, 0x78, 0x99, 0x45, 0xf7, 0x94, 0xde, 0xea, 0x23, 0x18, 0xec,
	0x5d, 0x58, 0xd6, 0x40, 0x6d, 0xf2, 0x56, 0xb9, 0x64, 0x02, 0xfd, 0x9c, 0x66, 0xc6, 0xaf, 0xfb,
	0x7a, 0xbf, 0x86, 0x84, 0x42, 0x3b, 0xc2, 0xe7, 0x23, 0x29, 0xf8, 0x31, 0xfd, 0x41, 0xa7, 0xd9,
	0xd3, 0xf9, 0xac, 0xa0, 0xee, 0x8f, 0x30, 0x68, 0x0d, 0xb9, 0xea, 0x81, 0x59, 0x99, 0xa6, 0xcf,
	0x51, 0xc1, 0x75, 0x5d, 0x7d, 0xaf, 0x59, 0x93, 0x5d, 0xb0, 0x94, 0xb2, 0x3f, 0x4b, 0xfd, 0xd0,
	0xe8, 0xea, 0xa8, 0x1e, 0x8c, 0xe7, 0x35, 0xec, 0x2d, 0x18, 0xee, 0x1c, 0x86, 0x6d, 0x41, 0x78,
	0x8b, 0xa1, 0x95, 0xb8, 0x2b, 0x6d, 0xd1, 0x3b, 0x78, 0xde, 0xd3, 0xcf, 0xee, 0x0b, 0x18, 0xb4,
	0x04, 0xe5, 0x6d, 0xbe, 0xed, 0x0a, 0x58, 0x11, 0x7b, 0xc1, 0x0a, 0xfc, 0xac, 0x14, 0xd5, 0x2b,
	0x17, 0x80, 0x3b, 0x05, 0xab, 0x51, 0xa7, 0x37, 0xfe, 0xbc, 0xfd, 0xde, 0x01, 0x58, 0x68, 0x15,
	0xb9, 0x65, 0xd4, 0xa0, 0x72, 0xbb, 0xb8, 0xaa, 0x65, 0x66, 0xe0, 0x35, 0xe5, 0x4c, 0x5f, 0xaf,
	0xfd, 0x6f, 0x5f, 0xaf, 0xaf, 0xf6, 0x35, 0x7e, 0x93, 0xcd, 0x78, 0x5a, 0x95, 0x86, 0x56, 0x93,
	0x29, 0x78, 0x1e, 0xf1, 0x97, 0x99, 0xdd, 0xc1, 0xd6, 0xb6, 0x0b, 0x1a, 0xcf, 0x69, 0x26, 0x29,
	0xf6, 0x5f, 0x86, 0xed, 0x92, 0xda, 0x6b, 0xed, 0x71, 0xb8, 0x85, 0x9b, 0xbd, 0xd0, 0x4e, 0xb5,
	0xd9, 0x61, 0x42, 0xc3, 0xe3, 0x80, 0x9f, 0xd4, 0x9b, 0x5d, 0xaf, 0xdd, 0xdf, 0x3a, 0x60, 0x35,
	0xc2, 0x89, 0xb2, 0xdd, 0xae, 0x74, 0x67, 0x45, 0x57, 0xdf, 0x76, 0xa1, 0xd7, 0xaa, 0x42, 0x87,
	0x8b, 0xfc, 0xb0, 0x56, 0x2c, 0x3b, 0x4c, 0x58, 0x5e, 0xd8, 0x9d, 0x76, 0x49, 0xbf, 0x74, 0xe0,
	0xc2, 0x2b, 0x54, 0x9b, 0xec, 0x2d, 0x65, 0x7c, 0xf5, 0xb5, 0xf2, 0xde, 0xce, 0x1d, 0x45, 0x40,
	0xd1, 0x7c, 0x23, 0x02, 0x96, 0x57, 0xad, 0xdc, 0x1b, 0x55, 0x3e, 0xa8, 0x60, 0x4a, 0x07, 0x31,
	0x17, 0xa5, 0x65, 0x4a, 0x0d, 0x3b, 0xea, 0x29, 0xe0, 0x32, 0xb1, 0xd7, 0xdc, 0x3f, 0x3a, 0xb0,
	0xb5, 0x72, 0xb5, 0x79, 0xd3, 0xc6, 0xc2, 0x6c, 0x21, 0x17, 0x74, 0xc6, 0x4e, 0x14, 0x56, 0xf5,
	0xf6, 0xab, 0xd8, 0x2d, 0x96, 0xf2, 0x29, 0xca, 0x59, 0xed, 0xb3, 0xfe, 0x7a, 0x9f, 0x05, 0x8b,
	0x5c, 0x05, 0x48, 0xfc, 0xe2, 0x1e, 0x0a, 0x14, 0x12, 0xaa, 0xfb, 0x52, 0x0b, 0x71, 0xbf, 0x82,
	0xae, 0xda, 0x23, 0xec, 0xa4, 0x2e, 0x0e, 0x92, 0xe9, 0x8a, 0x75, 0xf5, 0xd9, 0x54, 0x2b, 0xec,
	0x97, 0x4d, 0x31, 0x0b, 0xa7, 0xd3, 0xe9, 0xdd, 0xe6, 0x58, 0x6b, 0xe0, 0xb0, 0x87, 0x9a, 0x2e,
	0xc3, 0x8f, 0xef, 0x82, 0xd5, 0x0c, 0x23, 0xd9, 0x82, 0x41, 0xc6, 0x9b, 0x25, 0x6e, 0x1b, 0x7e,
	0x19, 0x4c, 0x32, 0xb8, 0x71, 0x68, 0x4c, 0xfd, 0x80, 0xa6, 0x47, 0x06, 0x58, 0xdb, 0x7f, 0x0a,
	0xc3, 0x88, 0xce, 0x7c, 0xfc, 0x90, 0x98, 0x1b, 0xe4, 0x95, 0xb1, 0xb9, 0x0d, 0x8f, 0xeb, 0xdb,
	0xf0, 0x58, 0x35, 0x87, 0xb9, 0x90, 0x16, 0xce, 0x5f, 0xbf, 0xde, 0xd1, 0x7a, 0x3a, 0x30, 0x15,
	0x6b, 0x17, 0x6f, 0x29, 0xc0, 0x3e, 0x6a, 0x24, 0x6b, 0xdd, 0x61, 0x3f, 0x78, 0x65, 0xbc, 0xef,
	0xfd, 0xb4, 0xa4, 0xab, 0x41, 0xb7, 0x5b, 0x17, 0x55, 0x63, 0xf3, 0xda, 0xa1, 0xf6, 0xbf, 0x85,
	0x1e, 0x0e, 0x99, 0x38, 0x25, 0xd7, 0xce, 0xc4, 0x7c, 0x8c, 0x0d, 0xee, 0xc7, 0x6f, 0x12, 0xd1,
	0x84, 0xd8, 0x3f, 0x84, 0xde, 0x4c, 0xd7, 0xfb, 0xfe, 0x99, 0x58, 0xba, 0x8c, 0xff, 0x2c, 0xd8,
	0xb8, 0x1e, 0x4e, 0x7f, 0xfa, 0x2c, 0x66, 0x32, 0x29, 0x83, 0x71, 0xc8, 0xe7, 0x13, 0xbc, 0xd9,
	0x32, 0x6c, 0x13, 0x7e, 0x62, 0xfe, 0x47, 0x84, 0xbb, 0x31, 0xcd, 0x76, 0x23, 0x5f, 0xc8, 0x5d,
	0xfc, 0xfc, 0x4e, 0xf2, 0xe3, 0x58, 0xff, 0x49, 0x08, 0x36, 0xb4, 0x75, 0xfa, 0x6f, 0x00, 0x00,
	0x00, 0xff, 0xff, 0xcf, 0xc6, 0x48, 0xce, 0x93, 0x0c, 0x00, 0x00,
}
