// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pgde/form/form.proto

package form

import (
	fmt "fmt"
	units "github.com/empirefox/protoc-gen-dart-ext/pkg/pgde/units"
	_ "github.com/empirefox/protoc-gen-dart-ext/pkg/pgde/zero"
	proto "github.com/golang/protobuf/proto"
	descriptor "github.com/golang/protobuf/protoc-gen-go/descriptor"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Protector int32

const (
	Protector_noProtector Protector = 0
	Protector_pin         Protector = 1
	Protector_pattern     Protector = 2
	Protector_password    Protector = 3
)

var Protector_name = map[int32]string{
	0: "noProtector",
	1: "pin",
	2: "pattern",
	3: "password",
}

var Protector_value = map[string]int32{
	"noProtector": 0,
	"pin":         1,
	"pattern":     2,
	"password":    3,
}

func (x Protector) String() string {
	return proto.EnumName(Protector_name, int32(x))
}

func (Protector) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_23d710dfe11887bd, []int{0}
}

type OneofHeader_Title_Show int32

const (
	OneofHeader_Title_icon     OneofHeader_Title_Show = 0
	OneofHeader_Title_text     OneofHeader_Title_Show = 1
	OneofHeader_Title_iconText OneofHeader_Title_Show = 2
)

var OneofHeader_Title_Show_name = map[int32]string{
	0: "icon",
	1: "text",
	2: "iconText",
}

var OneofHeader_Title_Show_value = map[string]int32{
	"icon":     0,
	"text":     1,
	"iconText": 2,
}

func (x OneofHeader_Title_Show) String() string {
	return proto.EnumName(OneofHeader_Title_Show_name, int32(x))
}

func (OneofHeader_Title_Show) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_23d710dfe11887bd, []int{1, 0, 0}
}

type OneofHeader_AfterCreate_State int32

const (
	OneofHeader_AfterCreate_hide       OneofHeader_AfterCreate_State = 0
	OneofHeader_AfterCreate_icon       OneofHeader_AfterCreate_State = 1
	OneofHeader_AfterCreate_text       OneofHeader_AfterCreate_State = 2
	OneofHeader_AfterCreate_iconText   OneofHeader_AfterCreate_State = 3
	OneofHeader_AfterCreate_frozen     OneofHeader_AfterCreate_State = 4
	OneofHeader_AfterCreate_changeable OneofHeader_AfterCreate_State = 5
)

var OneofHeader_AfterCreate_State_name = map[int32]string{
	0: "hide",
	1: "icon",
	2: "text",
	3: "iconText",
	4: "frozen",
	5: "changeable",
}

var OneofHeader_AfterCreate_State_value = map[string]int32{
	"hide":       0,
	"icon":       1,
	"text":       2,
	"iconText":   3,
	"frozen":     4,
	"changeable": 5,
}

func (x OneofHeader_AfterCreate_State) String() string {
	return proto.EnumName(OneofHeader_AfterCreate_State_name, int32(x))
}

func (OneofHeader_AfterCreate_State) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_23d710dfe11887bd, []int{1, 1, 0}
}

type Node_Type int32

const (
	Node_undefined Node_Type = 0
	// Accepts field type of entry, view or views.
	// Rejects others fields including any built-in fields.
	Node_entry Node_Type = 1
	// Leaf is a whole form, which expands everything execpt Views.
	// Id of leaf or view is for Get/Update/Remove-rpc request.
	Node_leaf Node_Type = 2
	// Define a view from within a leaf. Auto detect group.
	// Id of leaf or view is for Get/Update/Remove-rpc request.
	Node_view Node_Type = 3
	// Empty message.
	Node_typeName Node_Type = 4
	// Auto detect group.
	Node_element Node_Type = 5
)

var Node_Type_name = map[int32]string{
	0: "undefined",
	1: "entry",
	2: "leaf",
	3: "view",
	4: "typeName",
	5: "element",
}

var Node_Type_value = map[string]int32{
	"undefined": 0,
	"entry":     1,
	"leaf":      2,
	"view":      3,
	"typeName":  4,
	"element":   5,
}

func (x Node_Type) String() string {
	return proto.EnumName(Node_Type_name, int32(x))
}

func (Node_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_23d710dfe11887bd, []int{2, 0}
}

// configurable on all number fields
type Field_UnitPlace int32

const (
	Field_noUnitPlace Field_UnitPlace = 0
	Field_suffix      Field_UnitPlace = 1
	Field_labelSuffix Field_UnitPlace = 2
)

var Field_UnitPlace_name = map[int32]string{
	0: "noUnitPlace",
	1: "suffix",
	2: "labelSuffix",
}

var Field_UnitPlace_value = map[string]int32{
	"noUnitPlace": 0,
	"suffix":      1,
	"labelSuffix": 2,
}

func (x Field_UnitPlace) String() string {
	return proto.EnumName(Field_UnitPlace_name, int32(x))
}

func (Field_UnitPlace) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_23d710dfe11887bd, []int{4, 0}
}

type Field_TextInput_Type int32

const (
	Field_TextInput_autoByType   Field_TextInput_Type = 0
	Field_TextInput_datetime     Field_TextInput_Type = 2
	Field_TextInput_emailAddress Field_TextInput_Type = 3
	Field_TextInput_multiline    Field_TextInput_Type = 4
	Field_TextInput_number       Field_TextInput_Type = 5
	Field_TextInput_phone        Field_TextInput_Type = 6
	Field_TextInput_text         Field_TextInput_Type = 7
	Field_TextInput_url          Field_TextInput_Type = 8
)

var Field_TextInput_Type_name = map[int32]string{
	0: "autoByType",
	2: "datetime",
	3: "emailAddress",
	4: "multiline",
	5: "number",
	6: "phone",
	7: "text",
	8: "url",
}

var Field_TextInput_Type_value = map[string]int32{
	"autoByType":   0,
	"datetime":     2,
	"emailAddress": 3,
	"multiline":    4,
	"number":       5,
	"phone":        6,
	"text":         7,
	"url":          8,
}

func (x Field_TextInput_Type) String() string {
	return proto.EnumName(Field_TextInput_Type_name, int32(x))
}

func (Field_TextInput_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_23d710dfe11887bd, []int{4, 0, 0}
}

type Field_EnumInput_Type int32

const (
	Field_EnumInput_radio Field_EnumInput_Type = 0
	// extract a new message?
	Field_EnumInput_dropdown         Field_EnumInput_Type = 1
	Field_EnumInput_segmentedControl Field_EnumInput_Type = 2
	// values must be checked from fixed list
	Field_EnumInput_checkbox Field_EnumInput_Type = 3
	// values can be others
	Field_EnumInput_chips Field_EnumInput_Type = 4
	// support positions
	Field_EnumInput_rank Field_EnumInput_Type = 5
)

var Field_EnumInput_Type_name = map[int32]string{
	0: "radio",
	1: "dropdown",
	2: "segmentedControl",
	3: "checkbox",
	4: "chips",
	5: "rank",
}

var Field_EnumInput_Type_value = map[string]int32{
	"radio":            0,
	"dropdown":         1,
	"segmentedControl": 2,
	"checkbox":         3,
	"chips":            4,
	"rank":             5,
}

func (x Field_EnumInput_Type) String() string {
	return proto.EnumName(Field_EnumInput_Type_name, int32(x))
}

func (Field_EnumInput_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_23d710dfe11887bd, []int{4, 6, 0}
}

type Field_DatetimePickerInput_DatePickerMode int32

const (
	Field_DatetimePickerInput_day  Field_DatetimePickerInput_DatePickerMode = 0
	Field_DatetimePickerInput_year Field_DatetimePickerInput_DatePickerMode = 1
)

var Field_DatetimePickerInput_DatePickerMode_name = map[int32]string{
	0: "day",
	1: "year",
}

var Field_DatetimePickerInput_DatePickerMode_value = map[string]int32{
	"day":  0,
	"year": 1,
}

func (x Field_DatetimePickerInput_DatePickerMode) String() string {
	return proto.EnumName(Field_DatetimePickerInput_DatePickerMode_name, int32(x))
}

func (Field_DatetimePickerInput_DatePickerMode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_23d710dfe11887bd, []int{4, 8, 0}
}

type Field_InputDecoration_CounterType int32

const (
	Field_InputDecoration_byte      Field_InputDecoration_CounterType = 0
	Field_InputDecoration_character Field_InputDecoration_CounterType = 1
)

var Field_InputDecoration_CounterType_name = map[int32]string{
	0: "byte",
	1: "character",
}

var Field_InputDecoration_CounterType_value = map[string]int32{
	"byte":      0,
	"character": 1,
}

func (x Field_InputDecoration_CounterType) String() string {
	return proto.EnumName(Field_InputDecoration_CounterType_name, int32(x))
}

func (Field_InputDecoration_CounterType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_23d710dfe11887bd, []int{4, 9, 0}
}

type InputOption struct {
	Icon                 MaterialIcon `protobuf:"varint,1,opt,name=icon,proto3,enum=pgde.form.MaterialIcon" json:"icon,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *InputOption) Reset()         { *m = InputOption{} }
func (m *InputOption) String() string { return proto.CompactTextString(m) }
func (*InputOption) ProtoMessage()    {}
func (*InputOption) Descriptor() ([]byte, []int) {
	return fileDescriptor_23d710dfe11887bd, []int{0}
}

func (m *InputOption) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InputOption.Unmarshal(m, b)
}
func (m *InputOption) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InputOption.Marshal(b, m, deterministic)
}
func (m *InputOption) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InputOption.Merge(m, src)
}
func (m *InputOption) XXX_Size() int {
	return xxx_messageInfo_InputOption.Size(m)
}
func (m *InputOption) XXX_DiscardUnknown() {
	xxx_messageInfo_InputOption.DiscardUnknown(m)
}

var xxx_messageInfo_InputOption proto.InternalMessageInfo

func (m *InputOption) GetIcon() MaterialIcon {
	if m != nil {
		return m.Icon
	}
	return MaterialIcon_noMaterialIcon
}

type OneofHeader struct {
	Icon                 MaterialIcon                  `protobuf:"varint,1,opt,name=icon,proto3,enum=pgde.form.MaterialIcon" json:"icon,omitempty"`
	Title                OneofHeader_Title_Show        `protobuf:"varint,2,opt,name=title,proto3,enum=pgde.form.OneofHeader_Title_Show" json:"title,omitempty"`
	AfterCreate          OneofHeader_AfterCreate_State `protobuf:"varint,3,opt,name=afterCreate,proto3,enum=pgde.form.OneofHeader_AfterCreate_State" json:"afterCreate,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                      `json:"-"`
	XXX_unrecognized     []byte                        `json:"-"`
	XXX_sizecache        int32                         `json:"-"`
}

func (m *OneofHeader) Reset()         { *m = OneofHeader{} }
func (m *OneofHeader) String() string { return proto.CompactTextString(m) }
func (*OneofHeader) ProtoMessage()    {}
func (*OneofHeader) Descriptor() ([]byte, []int) {
	return fileDescriptor_23d710dfe11887bd, []int{1}
}

func (m *OneofHeader) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OneofHeader.Unmarshal(m, b)
}
func (m *OneofHeader) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OneofHeader.Marshal(b, m, deterministic)
}
func (m *OneofHeader) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OneofHeader.Merge(m, src)
}
func (m *OneofHeader) XXX_Size() int {
	return xxx_messageInfo_OneofHeader.Size(m)
}
func (m *OneofHeader) XXX_DiscardUnknown() {
	xxx_messageInfo_OneofHeader.DiscardUnknown(m)
}

var xxx_messageInfo_OneofHeader proto.InternalMessageInfo

func (m *OneofHeader) GetIcon() MaterialIcon {
	if m != nil {
		return m.Icon
	}
	return MaterialIcon_noMaterialIcon
}

func (m *OneofHeader) GetTitle() OneofHeader_Title_Show {
	if m != nil {
		return m.Title
	}
	return OneofHeader_Title_icon
}

func (m *OneofHeader) GetAfterCreate() OneofHeader_AfterCreate_State {
	if m != nil {
		return m.AfterCreate
	}
	return OneofHeader_AfterCreate_hide
}

type OneofHeader_Title struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OneofHeader_Title) Reset()         { *m = OneofHeader_Title{} }
func (m *OneofHeader_Title) String() string { return proto.CompactTextString(m) }
func (*OneofHeader_Title) ProtoMessage()    {}
func (*OneofHeader_Title) Descriptor() ([]byte, []int) {
	return fileDescriptor_23d710dfe11887bd, []int{1, 0}
}

func (m *OneofHeader_Title) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OneofHeader_Title.Unmarshal(m, b)
}
func (m *OneofHeader_Title) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OneofHeader_Title.Marshal(b, m, deterministic)
}
func (m *OneofHeader_Title) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OneofHeader_Title.Merge(m, src)
}
func (m *OneofHeader_Title) XXX_Size() int {
	return xxx_messageInfo_OneofHeader_Title.Size(m)
}
func (m *OneofHeader_Title) XXX_DiscardUnknown() {
	xxx_messageInfo_OneofHeader_Title.DiscardUnknown(m)
}

var xxx_messageInfo_OneofHeader_Title proto.InternalMessageInfo

type OneofHeader_AfterCreate struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OneofHeader_AfterCreate) Reset()         { *m = OneofHeader_AfterCreate{} }
func (m *OneofHeader_AfterCreate) String() string { return proto.CompactTextString(m) }
func (*OneofHeader_AfterCreate) ProtoMessage()    {}
func (*OneofHeader_AfterCreate) Descriptor() ([]byte, []int) {
	return fileDescriptor_23d710dfe11887bd, []int{1, 1}
}

func (m *OneofHeader_AfterCreate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OneofHeader_AfterCreate.Unmarshal(m, b)
}
func (m *OneofHeader_AfterCreate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OneofHeader_AfterCreate.Marshal(b, m, deterministic)
}
func (m *OneofHeader_AfterCreate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OneofHeader_AfterCreate.Merge(m, src)
}
func (m *OneofHeader_AfterCreate) XXX_Size() int {
	return xxx_messageInfo_OneofHeader_AfterCreate.Size(m)
}
func (m *OneofHeader_AfterCreate) XXX_DiscardUnknown() {
	xxx_messageInfo_OneofHeader_AfterCreate.DiscardUnknown(m)
}

var xxx_messageInfo_OneofHeader_AfterCreate proto.InternalMessageInfo

type Node struct {
	Type                 Node_Type    `protobuf:"varint,1,opt,name=type,proto3,enum=pgde.form.Node_Type" json:"type,omitempty"`
	Icon                 MaterialIcon `protobuf:"varint,3,opt,name=icon,proto3,enum=pgde.form.MaterialIcon" json:"icon,omitempty"`
	Protector            Protector    `protobuf:"varint,4,opt,name=protector,proto3,enum=pgde.form.Protector" json:"protector,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Node) Reset()         { *m = Node{} }
func (m *Node) String() string { return proto.CompactTextString(m) }
func (*Node) ProtoMessage()    {}
func (*Node) Descriptor() ([]byte, []int) {
	return fileDescriptor_23d710dfe11887bd, []int{2}
}

func (m *Node) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Node.Unmarshal(m, b)
}
func (m *Node) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Node.Marshal(b, m, deterministic)
}
func (m *Node) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Node.Merge(m, src)
}
func (m *Node) XXX_Size() int {
	return xxx_messageInfo_Node.Size(m)
}
func (m *Node) XXX_DiscardUnknown() {
	xxx_messageInfo_Node.DiscardUnknown(m)
}

var xxx_messageInfo_Node proto.InternalMessageInfo

func (m *Node) GetType() Node_Type {
	if m != nil {
		return m.Type
	}
	return Node_undefined
}

func (m *Node) GetIcon() MaterialIcon {
	if m != nil {
		return m.Icon
	}
	return MaterialIcon_noMaterialIcon
}

func (m *Node) GetProtector() Protector {
	if m != nil {
		return m.Protector
	}
	return Protector_noProtector
}

type EntryField struct {
	// Types that are valid to be assigned to Is:
	//	*EntryField_Form_
	//	*EntryField_List
	//	*EntryField_SelectOne
	//	*EntryField_SelectMany
	Is                   isEntryField_Is `protobuf_oneof:"is"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *EntryField) Reset()         { *m = EntryField{} }
func (m *EntryField) String() string { return proto.CompactTextString(m) }
func (*EntryField) ProtoMessage()    {}
func (*EntryField) Descriptor() ([]byte, []int) {
	return fileDescriptor_23d710dfe11887bd, []int{3}
}

func (m *EntryField) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EntryField.Unmarshal(m, b)
}
func (m *EntryField) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EntryField.Marshal(b, m, deterministic)
}
func (m *EntryField) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EntryField.Merge(m, src)
}
func (m *EntryField) XXX_Size() int {
	return xxx_messageInfo_EntryField.Size(m)
}
func (m *EntryField) XXX_DiscardUnknown() {
	xxx_messageInfo_EntryField.DiscardUnknown(m)
}

var xxx_messageInfo_EntryField proto.InternalMessageInfo

type isEntryField_Is interface {
	isEntryField_Is()
}

type EntryField_Form_ struct {
	Form *EntryField_Form `protobuf:"bytes,1,opt,name=form,proto3,oneof"`
}

type EntryField_List struct {
	List *EntryField_DestList `protobuf:"bytes,2,opt,name=list,proto3,oneof"`
}

type EntryField_SelectOne struct {
	SelectOne *SourceList `protobuf:"bytes,3,opt,name=selectOne,proto3,oneof"`
}

type EntryField_SelectMany struct {
	SelectMany *ChooseList `protobuf:"bytes,4,opt,name=selectMany,proto3,oneof"`
}

func (*EntryField_Form_) isEntryField_Is() {}

func (*EntryField_List) isEntryField_Is() {}

func (*EntryField_SelectOne) isEntryField_Is() {}

func (*EntryField_SelectMany) isEntryField_Is() {}

func (m *EntryField) GetIs() isEntryField_Is {
	if m != nil {
		return m.Is
	}
	return nil
}

func (m *EntryField) GetForm() *EntryField_Form {
	if x, ok := m.GetIs().(*EntryField_Form_); ok {
		return x.Form
	}
	return nil
}

func (m *EntryField) GetList() *EntryField_DestList {
	if x, ok := m.GetIs().(*EntryField_List); ok {
		return x.List
	}
	return nil
}

func (m *EntryField) GetSelectOne() *SourceList {
	if x, ok := m.GetIs().(*EntryField_SelectOne); ok {
		return x.SelectOne
	}
	return nil
}

func (m *EntryField) GetSelectMany() *ChooseList {
	if x, ok := m.GetIs().(*EntryField_SelectMany); ok {
		return x.SelectMany
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*EntryField) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*EntryField_Form_)(nil),
		(*EntryField_List)(nil),
		(*EntryField_SelectOne)(nil),
		(*EntryField_SelectMany)(nil),
	}
}

type EntryField_Form struct {
	Remove               bool     `protobuf:"varint,2,opt,name=remove,proto3" json:"remove,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EntryField_Form) Reset()         { *m = EntryField_Form{} }
func (m *EntryField_Form) String() string { return proto.CompactTextString(m) }
func (*EntryField_Form) ProtoMessage()    {}
func (*EntryField_Form) Descriptor() ([]byte, []int) {
	return fileDescriptor_23d710dfe11887bd, []int{3, 0}
}

func (m *EntryField_Form) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EntryField_Form.Unmarshal(m, b)
}
func (m *EntryField_Form) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EntryField_Form.Marshal(b, m, deterministic)
}
func (m *EntryField_Form) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EntryField_Form.Merge(m, src)
}
func (m *EntryField_Form) XXX_Size() int {
	return xxx_messageInfo_EntryField_Form.Size(m)
}
func (m *EntryField_Form) XXX_DiscardUnknown() {
	xxx_messageInfo_EntryField_Form.DiscardUnknown(m)
}

var xxx_messageInfo_EntryField_Form proto.InternalMessageInfo

func (m *EntryField_Form) GetRemove() bool {
	if m != nil {
		return m.Remove
	}
	return false
}

type EntryField_DestList struct {
	GroupByType bool   `protobuf:"varint,1,opt,name=groupByType,proto3" json:"groupByType,omitempty"`
	Pager       bool   `protobuf:"varint,2,opt,name=pager,proto3" json:"pager,omitempty"`
	Rows        uint32 `protobuf:"varint,3,opt,name=rows,proto3" json:"rows,omitempty"`
	Add         bool   `protobuf:"varint,4,opt,name=add,proto3" json:"add,omitempty"`
	Edit        bool   `protobuf:"varint,5,opt,name=edit,proto3" json:"edit,omitempty"`
	Remove      bool   `protobuf:"varint,6,opt,name=remove,proto3" json:"remove,omitempty"`
	RemoveAll   bool   `protobuf:"varint,7,opt,name=removeAll,proto3" json:"removeAll,omitempty"`
	Unique      bool   `protobuf:"varint,8,opt,name=unique,proto3" json:"unique,omitempty"`
	Rank        bool   `protobuf:"varint,9,opt,name=rank,proto3" json:"rank,omitempty"`
	// add custom search widget, only enable edit/remove when searching
	Search               bool     `protobuf:"varint,10,opt,name=search,proto3" json:"search,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EntryField_DestList) Reset()         { *m = EntryField_DestList{} }
func (m *EntryField_DestList) String() string { return proto.CompactTextString(m) }
func (*EntryField_DestList) ProtoMessage()    {}
func (*EntryField_DestList) Descriptor() ([]byte, []int) {
	return fileDescriptor_23d710dfe11887bd, []int{3, 1}
}

func (m *EntryField_DestList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EntryField_DestList.Unmarshal(m, b)
}
func (m *EntryField_DestList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EntryField_DestList.Marshal(b, m, deterministic)
}
func (m *EntryField_DestList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EntryField_DestList.Merge(m, src)
}
func (m *EntryField_DestList) XXX_Size() int {
	return xxx_messageInfo_EntryField_DestList.Size(m)
}
func (m *EntryField_DestList) XXX_DiscardUnknown() {
	xxx_messageInfo_EntryField_DestList.DiscardUnknown(m)
}

var xxx_messageInfo_EntryField_DestList proto.InternalMessageInfo

func (m *EntryField_DestList) GetGroupByType() bool {
	if m != nil {
		return m.GroupByType
	}
	return false
}

func (m *EntryField_DestList) GetPager() bool {
	if m != nil {
		return m.Pager
	}
	return false
}

func (m *EntryField_DestList) GetRows() uint32 {
	if m != nil {
		return m.Rows
	}
	return 0
}

func (m *EntryField_DestList) GetAdd() bool {
	if m != nil {
		return m.Add
	}
	return false
}

func (m *EntryField_DestList) GetEdit() bool {
	if m != nil {
		return m.Edit
	}
	return false
}

func (m *EntryField_DestList) GetRemove() bool {
	if m != nil {
		return m.Remove
	}
	return false
}

func (m *EntryField_DestList) GetRemoveAll() bool {
	if m != nil {
		return m.RemoveAll
	}
	return false
}

func (m *EntryField_DestList) GetUnique() bool {
	if m != nil {
		return m.Unique
	}
	return false
}

func (m *EntryField_DestList) GetRank() bool {
	if m != nil {
		return m.Rank
	}
	return false
}

func (m *EntryField_DestList) GetSearch() bool {
	if m != nil {
		return m.Search
	}
	return false
}

type Field struct {
	Decoration *Field_InputDecoration `protobuf:"bytes,1,opt,name=decoration,proto3" json:"decoration,omitempty"`
	Protector  Protector              `protobuf:"varint,2,opt,name=protector,proto3,enum=pgde.form.Protector" json:"protector,omitempty"`
	// Types that are valid to be assigned to Build:
	//	*Field_Hide
	//	*Field_Disabled
	//	*Field_EnsureAgain
	Build isField_Build `protobuf_oneof:"build"`
	// Types that are valid to be assigned to Type:
	//	*Field_Text
	//	*Field_Signature
	//	*Field_Number
	//	*Field_Stepper
	//	*Field_Slider
	//	*Field_Rate
	//	*Field_EnumType
	//	*Field_SelectOne
	//	*Field_SelectMany
	//	*Field_Embed
	//	*Field_BoolSwitch
	//	*Field_Datetime
	//	*Field_IgnoreMap
	Type                 isField_Type `protobuf_oneof:"type"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Field) Reset()         { *m = Field{} }
func (m *Field) String() string { return proto.CompactTextString(m) }
func (*Field) ProtoMessage()    {}
func (*Field) Descriptor() ([]byte, []int) {
	return fileDescriptor_23d710dfe11887bd, []int{4}
}

func (m *Field) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Field.Unmarshal(m, b)
}
func (m *Field) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Field.Marshal(b, m, deterministic)
}
func (m *Field) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Field.Merge(m, src)
}
func (m *Field) XXX_Size() int {
	return xxx_messageInfo_Field.Size(m)
}
func (m *Field) XXX_DiscardUnknown() {
	xxx_messageInfo_Field.DiscardUnknown(m)
}

var xxx_messageInfo_Field proto.InternalMessageInfo

func (m *Field) GetDecoration() *Field_InputDecoration {
	if m != nil {
		return m.Decoration
	}
	return nil
}

func (m *Field) GetProtector() Protector {
	if m != nil {
		return m.Protector
	}
	return Protector_noProtector
}

type isField_Build interface {
	isField_Build()
}

type Field_Hide struct {
	Hide bool `protobuf:"varint,3,opt,name=hide,proto3,oneof"`
}

type Field_Disabled struct {
	Disabled bool `protobuf:"varint,4,opt,name=disabled,proto3,oneof"`
}

type Field_EnsureAgain struct {
	EnsureAgain bool `protobuf:"varint,5,opt,name=ensureAgain,proto3,oneof"`
}

func (*Field_Hide) isField_Build() {}

func (*Field_Disabled) isField_Build() {}

func (*Field_EnsureAgain) isField_Build() {}

func (m *Field) GetBuild() isField_Build {
	if m != nil {
		return m.Build
	}
	return nil
}

func (m *Field) GetHide() bool {
	if x, ok := m.GetBuild().(*Field_Hide); ok {
		return x.Hide
	}
	return false
}

func (m *Field) GetDisabled() bool {
	if x, ok := m.GetBuild().(*Field_Disabled); ok {
		return x.Disabled
	}
	return false
}

func (m *Field) GetEnsureAgain() bool {
	if x, ok := m.GetBuild().(*Field_EnsureAgain); ok {
		return x.EnsureAgain
	}
	return false
}

type isField_Type interface {
	isField_Type()
}

type Field_Text struct {
	Text *Field_TextInput `protobuf:"bytes,11,opt,name=text,proto3,oneof"`
}

type Field_Signature struct {
	Signature *Field_SignatureInput `protobuf:"bytes,12,opt,name=signature,proto3,oneof"`
}

type Field_Number struct {
	Number *Field_NumberInput `protobuf:"bytes,13,opt,name=number,proto3,oneof"`
}

type Field_Stepper struct {
	Stepper *Field_StepperInput `protobuf:"bytes,14,opt,name=stepper,proto3,oneof"`
}

type Field_Slider struct {
	Slider *Field_SliderInput `protobuf:"bytes,15,opt,name=slider,proto3,oneof"`
}

type Field_Rate struct {
	Rate *Field_RateInput `protobuf:"bytes,16,opt,name=rate,proto3,oneof"`
}

type Field_EnumType struct {
	EnumType Field_EnumInput_Type `protobuf:"varint,17,opt,name=enumType,proto3,enum=pgde.form.Field_EnumInput_Type,oneof"`
}

type Field_SelectOne struct {
	SelectOne *SourceList `protobuf:"bytes,18,opt,name=selectOne,proto3,oneof"`
}

type Field_SelectMany struct {
	SelectMany *ChooseList `protobuf:"bytes,19,opt,name=selectMany,proto3,oneof"`
}

type Field_Embed struct {
	Embed *MaterialColor `protobuf:"bytes,20,opt,name=embed,proto3,oneof"`
}

type Field_BoolSwitch struct {
	BoolSwitch *Field_SwitchInput `protobuf:"bytes,21,opt,name=boolSwitch,proto3,oneof"`
}

type Field_Datetime struct {
	Datetime *Field_DatetimePickerInput `protobuf:"bytes,22,opt,name=datetime,proto3,oneof"`
}

type Field_IgnoreMap struct {
	IgnoreMap bool `protobuf:"varint,23,opt,name=ignoreMap,proto3,oneof"`
}

func (*Field_Text) isField_Type() {}

func (*Field_Signature) isField_Type() {}

func (*Field_Number) isField_Type() {}

func (*Field_Stepper) isField_Type() {}

func (*Field_Slider) isField_Type() {}

func (*Field_Rate) isField_Type() {}

func (*Field_EnumType) isField_Type() {}

func (*Field_SelectOne) isField_Type() {}

func (*Field_SelectMany) isField_Type() {}

func (*Field_Embed) isField_Type() {}

func (*Field_BoolSwitch) isField_Type() {}

func (*Field_Datetime) isField_Type() {}

func (*Field_IgnoreMap) isField_Type() {}

func (m *Field) GetType() isField_Type {
	if m != nil {
		return m.Type
	}
	return nil
}

func (m *Field) GetText() *Field_TextInput {
	if x, ok := m.GetType().(*Field_Text); ok {
		return x.Text
	}
	return nil
}

func (m *Field) GetSignature() *Field_SignatureInput {
	if x, ok := m.GetType().(*Field_Signature); ok {
		return x.Signature
	}
	return nil
}

func (m *Field) GetNumber() *Field_NumberInput {
	if x, ok := m.GetType().(*Field_Number); ok {
		return x.Number
	}
	return nil
}

func (m *Field) GetStepper() *Field_StepperInput {
	if x, ok := m.GetType().(*Field_Stepper); ok {
		return x.Stepper
	}
	return nil
}

func (m *Field) GetSlider() *Field_SliderInput {
	if x, ok := m.GetType().(*Field_Slider); ok {
		return x.Slider
	}
	return nil
}

func (m *Field) GetRate() *Field_RateInput {
	if x, ok := m.GetType().(*Field_Rate); ok {
		return x.Rate
	}
	return nil
}

func (m *Field) GetEnumType() Field_EnumInput_Type {
	if x, ok := m.GetType().(*Field_EnumType); ok {
		return x.EnumType
	}
	return Field_EnumInput_radio
}

func (m *Field) GetSelectOne() *SourceList {
	if x, ok := m.GetType().(*Field_SelectOne); ok {
		return x.SelectOne
	}
	return nil
}

func (m *Field) GetSelectMany() *ChooseList {
	if x, ok := m.GetType().(*Field_SelectMany); ok {
		return x.SelectMany
	}
	return nil
}

func (m *Field) GetEmbed() *MaterialColor {
	if x, ok := m.GetType().(*Field_Embed); ok {
		return x.Embed
	}
	return nil
}

func (m *Field) GetBoolSwitch() *Field_SwitchInput {
	if x, ok := m.GetType().(*Field_BoolSwitch); ok {
		return x.BoolSwitch
	}
	return nil
}

func (m *Field) GetDatetime() *Field_DatetimePickerInput {
	if x, ok := m.GetType().(*Field_Datetime); ok {
		return x.Datetime
	}
	return nil
}

func (m *Field) GetIgnoreMap() bool {
	if x, ok := m.GetType().(*Field_IgnoreMap); ok {
		return x.IgnoreMap
	}
	return false
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Field) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Field_Hide)(nil),
		(*Field_Disabled)(nil),
		(*Field_EnsureAgain)(nil),
		(*Field_Text)(nil),
		(*Field_Signature)(nil),
		(*Field_Number)(nil),
		(*Field_Stepper)(nil),
		(*Field_Slider)(nil),
		(*Field_Rate)(nil),
		(*Field_EnumType)(nil),
		(*Field_SelectOne)(nil),
		(*Field_SelectMany)(nil),
		(*Field_Embed)(nil),
		(*Field_BoolSwitch)(nil),
		(*Field_Datetime)(nil),
		(*Field_IgnoreMap)(nil),
	}
}

type Field_TextInput struct {
	KeyboardType         Field_TextInput_Type `protobuf:"varint,1,opt,name=keyboardType,proto3,enum=pgde.form.Field_TextInput_Type" json:"keyboardType,omitempty"`
	ObscureText          bool                 `protobuf:"varint,2,opt,name=obscureText,proto3" json:"obscureText,omitempty"`
	Autocorrect          bool                 `protobuf:"varint,3,opt,name=autocorrect,proto3" json:"autocorrect,omitempty"`
	MaxLines             int32                `protobuf:"varint,4,opt,name=maxLines,proto3" json:"maxLines,omitempty"`
	MaxLengthEnforced    bool                 `protobuf:"varint,5,opt,name=maxLengthEnforced,proto3" json:"maxLengthEnforced,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Field_TextInput) Reset()         { *m = Field_TextInput{} }
func (m *Field_TextInput) String() string { return proto.CompactTextString(m) }
func (*Field_TextInput) ProtoMessage()    {}
func (*Field_TextInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_23d710dfe11887bd, []int{4, 0}
}

func (m *Field_TextInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Field_TextInput.Unmarshal(m, b)
}
func (m *Field_TextInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Field_TextInput.Marshal(b, m, deterministic)
}
func (m *Field_TextInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Field_TextInput.Merge(m, src)
}
func (m *Field_TextInput) XXX_Size() int {
	return xxx_messageInfo_Field_TextInput.Size(m)
}
func (m *Field_TextInput) XXX_DiscardUnknown() {
	xxx_messageInfo_Field_TextInput.DiscardUnknown(m)
}

var xxx_messageInfo_Field_TextInput proto.InternalMessageInfo

func (m *Field_TextInput) GetKeyboardType() Field_TextInput_Type {
	if m != nil {
		return m.KeyboardType
	}
	return Field_TextInput_autoByType
}

func (m *Field_TextInput) GetObscureText() bool {
	if m != nil {
		return m.ObscureText
	}
	return false
}

func (m *Field_TextInput) GetAutocorrect() bool {
	if m != nil {
		return m.Autocorrect
	}
	return false
}

func (m *Field_TextInput) GetMaxLines() int32 {
	if m != nil {
		return m.MaxLines
	}
	return 0
}

func (m *Field_TextInput) GetMaxLengthEnforced() bool {
	if m != nil {
		return m.MaxLengthEnforced
	}
	return false
}

type Field_SignatureInput struct {
	Width                float64        `protobuf:"fixed64,1,opt,name=width,proto3" json:"width,omitempty"`
	Height               float64        `protobuf:"fixed64,2,opt,name=height,proto3" json:"height,omitempty"`
	BackgroundColor      *MaterialColor `protobuf:"bytes,3,opt,name=backgroundColor,proto3" json:"backgroundColor,omitempty"`
	PenColor             *MaterialColor `protobuf:"bytes,4,opt,name=penColor,proto3" json:"penColor,omitempty"`
	PenStrokeWidth       float64        `protobuf:"fixed64,5,opt,name=penStrokeWidth,proto3" json:"penStrokeWidth,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Field_SignatureInput) Reset()         { *m = Field_SignatureInput{} }
func (m *Field_SignatureInput) String() string { return proto.CompactTextString(m) }
func (*Field_SignatureInput) ProtoMessage()    {}
func (*Field_SignatureInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_23d710dfe11887bd, []int{4, 1}
}

func (m *Field_SignatureInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Field_SignatureInput.Unmarshal(m, b)
}
func (m *Field_SignatureInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Field_SignatureInput.Marshal(b, m, deterministic)
}
func (m *Field_SignatureInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Field_SignatureInput.Merge(m, src)
}
func (m *Field_SignatureInput) XXX_Size() int {
	return xxx_messageInfo_Field_SignatureInput.Size(m)
}
func (m *Field_SignatureInput) XXX_DiscardUnknown() {
	xxx_messageInfo_Field_SignatureInput.DiscardUnknown(m)
}

var xxx_messageInfo_Field_SignatureInput proto.InternalMessageInfo

func (m *Field_SignatureInput) GetWidth() float64 {
	if m != nil {
		return m.Width
	}
	return 0
}

func (m *Field_SignatureInput) GetHeight() float64 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *Field_SignatureInput) GetBackgroundColor() *MaterialColor {
	if m != nil {
		return m.BackgroundColor
	}
	return nil
}

func (m *Field_SignatureInput) GetPenColor() *MaterialColor {
	if m != nil {
		return m.PenColor
	}
	return nil
}

func (m *Field_SignatureInput) GetPenStrokeWidth() float64 {
	if m != nil {
		return m.PenStrokeWidth
	}
	return 0
}

type Field_NumberInput struct {
	Unit                 *units.Show     `protobuf:"bytes,1,opt,name=unit,proto3" json:"unit,omitempty"`
	UnitPlace            Field_UnitPlace `protobuf:"varint,2,opt,name=unitPlace,proto3,enum=pgde.form.Field_UnitPlace" json:"unitPlace,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Field_NumberInput) Reset()         { *m = Field_NumberInput{} }
func (m *Field_NumberInput) String() string { return proto.CompactTextString(m) }
func (*Field_NumberInput) ProtoMessage()    {}
func (*Field_NumberInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_23d710dfe11887bd, []int{4, 2}
}

func (m *Field_NumberInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Field_NumberInput.Unmarshal(m, b)
}
func (m *Field_NumberInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Field_NumberInput.Marshal(b, m, deterministic)
}
func (m *Field_NumberInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Field_NumberInput.Merge(m, src)
}
func (m *Field_NumberInput) XXX_Size() int {
	return xxx_messageInfo_Field_NumberInput.Size(m)
}
func (m *Field_NumberInput) XXX_DiscardUnknown() {
	xxx_messageInfo_Field_NumberInput.DiscardUnknown(m)
}

var xxx_messageInfo_Field_NumberInput proto.InternalMessageInfo

func (m *Field_NumberInput) GetUnit() *units.Show {
	if m != nil {
		return m.Unit
	}
	return nil
}

func (m *Field_NumberInput) GetUnitPlace() Field_UnitPlace {
	if m != nil {
		return m.UnitPlace
	}
	return Field_noUnitPlace
}

type Field_StepperInput struct {
	Unit                 *units.Show     `protobuf:"bytes,1,opt,name=unit,proto3" json:"unit,omitempty"`
	UnitPlace            Field_UnitPlace `protobuf:"varint,2,opt,name=unitPlace,proto3,enum=pgde.form.Field_UnitPlace" json:"unitPlace,omitempty"`
	Step                 uint32          `protobuf:"varint,3,opt,name=step,proto3" json:"step,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Field_StepperInput) Reset()         { *m = Field_StepperInput{} }
func (m *Field_StepperInput) String() string { return proto.CompactTextString(m) }
func (*Field_StepperInput) ProtoMessage()    {}
func (*Field_StepperInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_23d710dfe11887bd, []int{4, 3}
}

func (m *Field_StepperInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Field_StepperInput.Unmarshal(m, b)
}
func (m *Field_StepperInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Field_StepperInput.Marshal(b, m, deterministic)
}
func (m *Field_StepperInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Field_StepperInput.Merge(m, src)
}
func (m *Field_StepperInput) XXX_Size() int {
	return xxx_messageInfo_Field_StepperInput.Size(m)
}
func (m *Field_StepperInput) XXX_DiscardUnknown() {
	xxx_messageInfo_Field_StepperInput.DiscardUnknown(m)
}

var xxx_messageInfo_Field_StepperInput proto.InternalMessageInfo

func (m *Field_StepperInput) GetUnit() *units.Show {
	if m != nil {
		return m.Unit
	}
	return nil
}

func (m *Field_StepperInput) GetUnitPlace() Field_UnitPlace {
	if m != nil {
		return m.UnitPlace
	}
	return Field_noUnitPlace
}

func (m *Field_StepperInput) GetStep() uint32 {
	if m != nil {
		return m.Step
	}
	return 0
}

type Field_SliderInput struct {
	Unit                 *units.Show     `protobuf:"bytes,1,opt,name=unit,proto3" json:"unit,omitempty"`
	UnitPlace            Field_UnitPlace `protobuf:"varint,2,opt,name=unitPlace,proto3,enum=pgde.form.Field_UnitPlace" json:"unitPlace,omitempty"`
	Divisions            uint32          `protobuf:"varint,3,opt,name=divisions,proto3" json:"divisions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Field_SliderInput) Reset()         { *m = Field_SliderInput{} }
func (m *Field_SliderInput) String() string { return proto.CompactTextString(m) }
func (*Field_SliderInput) ProtoMessage()    {}
func (*Field_SliderInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_23d710dfe11887bd, []int{4, 4}
}

func (m *Field_SliderInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Field_SliderInput.Unmarshal(m, b)
}
func (m *Field_SliderInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Field_SliderInput.Marshal(b, m, deterministic)
}
func (m *Field_SliderInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Field_SliderInput.Merge(m, src)
}
func (m *Field_SliderInput) XXX_Size() int {
	return xxx_messageInfo_Field_SliderInput.Size(m)
}
func (m *Field_SliderInput) XXX_DiscardUnknown() {
	xxx_messageInfo_Field_SliderInput.DiscardUnknown(m)
}

var xxx_messageInfo_Field_SliderInput proto.InternalMessageInfo

func (m *Field_SliderInput) GetUnit() *units.Show {
	if m != nil {
		return m.Unit
	}
	return nil
}

func (m *Field_SliderInput) GetUnitPlace() Field_UnitPlace {
	if m != nil {
		return m.UnitPlace
	}
	return Field_noUnitPlace
}

func (m *Field_SliderInput) GetDivisions() uint32 {
	if m != nil {
		return m.Divisions
	}
	return 0
}

type Field_RateInput struct {
	Icon                 MaterialIcon `protobuf:"varint,1,opt,name=icon,proto3,enum=pgde.form.MaterialIcon" json:"icon,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Field_RateInput) Reset()         { *m = Field_RateInput{} }
func (m *Field_RateInput) String() string { return proto.CompactTextString(m) }
func (*Field_RateInput) ProtoMessage()    {}
func (*Field_RateInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_23d710dfe11887bd, []int{4, 5}
}

func (m *Field_RateInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Field_RateInput.Unmarshal(m, b)
}
func (m *Field_RateInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Field_RateInput.Marshal(b, m, deterministic)
}
func (m *Field_RateInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Field_RateInput.Merge(m, src)
}
func (m *Field_RateInput) XXX_Size() int {
	return xxx_messageInfo_Field_RateInput.Size(m)
}
func (m *Field_RateInput) XXX_DiscardUnknown() {
	xxx_messageInfo_Field_RateInput.DiscardUnknown(m)
}

var xxx_messageInfo_Field_RateInput proto.InternalMessageInfo

func (m *Field_RateInput) GetIcon() MaterialIcon {
	if m != nil {
		return m.Icon
	}
	return MaterialIcon_noMaterialIcon
}

type Field_EnumInput struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Field_EnumInput) Reset()         { *m = Field_EnumInput{} }
func (m *Field_EnumInput) String() string { return proto.CompactTextString(m) }
func (*Field_EnumInput) ProtoMessage()    {}
func (*Field_EnumInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_23d710dfe11887bd, []int{4, 6}
}

func (m *Field_EnumInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Field_EnumInput.Unmarshal(m, b)
}
func (m *Field_EnumInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Field_EnumInput.Marshal(b, m, deterministic)
}
func (m *Field_EnumInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Field_EnumInput.Merge(m, src)
}
func (m *Field_EnumInput) XXX_Size() int {
	return xxx_messageInfo_Field_EnumInput.Size(m)
}
func (m *Field_EnumInput) XXX_DiscardUnknown() {
	xxx_messageInfo_Field_EnumInput.DiscardUnknown(m)
}

var xxx_messageInfo_Field_EnumInput proto.InternalMessageInfo

type Field_SwitchInput struct {
	Checkbox             bool     `protobuf:"varint,1,opt,name=checkbox,proto3" json:"checkbox,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Field_SwitchInput) Reset()         { *m = Field_SwitchInput{} }
func (m *Field_SwitchInput) String() string { return proto.CompactTextString(m) }
func (*Field_SwitchInput) ProtoMessage()    {}
func (*Field_SwitchInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_23d710dfe11887bd, []int{4, 7}
}

func (m *Field_SwitchInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Field_SwitchInput.Unmarshal(m, b)
}
func (m *Field_SwitchInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Field_SwitchInput.Marshal(b, m, deterministic)
}
func (m *Field_SwitchInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Field_SwitchInput.Merge(m, src)
}
func (m *Field_SwitchInput) XXX_Size() int {
	return xxx_messageInfo_Field_SwitchInput.Size(m)
}
func (m *Field_SwitchInput) XXX_DiscardUnknown() {
	xxx_messageInfo_Field_SwitchInput.DiscardUnknown(m)
}

var xxx_messageInfo_Field_SwitchInput proto.InternalMessageInfo

func (m *Field_SwitchInput) GetCheckbox() bool {
	if m != nil {
		return m.Checkbox
	}
	return false
}

// type and format are defined by format.Format
type Field_DatetimePickerInput struct {
	DatePickerMode       Field_DatetimePickerInput_DatePickerMode `protobuf:"varint,1,opt,name=datePickerMode,proto3,enum=pgde.form.Field_DatetimePickerInput_DatePickerMode" json:"datePickerMode,omitempty"`
	Editable             bool                                     `protobuf:"varint,2,opt,name=editable,proto3" json:"editable,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                 `json:"-"`
	XXX_unrecognized     []byte                                   `json:"-"`
	XXX_sizecache        int32                                    `json:"-"`
}

func (m *Field_DatetimePickerInput) Reset()         { *m = Field_DatetimePickerInput{} }
func (m *Field_DatetimePickerInput) String() string { return proto.CompactTextString(m) }
func (*Field_DatetimePickerInput) ProtoMessage()    {}
func (*Field_DatetimePickerInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_23d710dfe11887bd, []int{4, 8}
}

func (m *Field_DatetimePickerInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Field_DatetimePickerInput.Unmarshal(m, b)
}
func (m *Field_DatetimePickerInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Field_DatetimePickerInput.Marshal(b, m, deterministic)
}
func (m *Field_DatetimePickerInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Field_DatetimePickerInput.Merge(m, src)
}
func (m *Field_DatetimePickerInput) XXX_Size() int {
	return xxx_messageInfo_Field_DatetimePickerInput.Size(m)
}
func (m *Field_DatetimePickerInput) XXX_DiscardUnknown() {
	xxx_messageInfo_Field_DatetimePickerInput.DiscardUnknown(m)
}

var xxx_messageInfo_Field_DatetimePickerInput proto.InternalMessageInfo

func (m *Field_DatetimePickerInput) GetDatePickerMode() Field_DatetimePickerInput_DatePickerMode {
	if m != nil {
		return m.DatePickerMode
	}
	return Field_DatetimePickerInput_day
}

func (m *Field_DatetimePickerInput) GetEditable() bool {
	if m != nil {
		return m.Editable
	}
	return false
}

type Field_InputDecoration struct {
	Icon       MaterialIcon `protobuf:"varint,1,opt,name=icon,proto3,enum=pgde.form.MaterialIcon" json:"icon,omitempty"`
	PrefixIcon MaterialIcon `protobuf:"varint,2,opt,name=prefixIcon,proto3,enum=pgde.form.MaterialIcon" json:"prefixIcon,omitempty"`
	SuffixIcon MaterialIcon `protobuf:"varint,3,opt,name=suffixIcon,proto3,enum=pgde.form.MaterialIcon" json:"suffixIcon,omitempty"`
	/// Optional text to place below the line as a character count.
	///
	/// Rendered using [counterStyle]. Uses [helperStyle] if [counterStyle] is
	/// null.
	///
	/// The semantic label can be replaced by providing a [semanticCounterText].
	///
	/// If null or an empty string and [counter] isn't specified, then nothing
	/// will appear in the counter's location.
	Counter              []Field_InputDecoration_CounterType `protobuf:"varint,4,rep,packed,name=counter,proto3,enum=pgde.form.Field_InputDecoration_CounterType" json:"counter,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                            `json:"-"`
	XXX_unrecognized     []byte                              `json:"-"`
	XXX_sizecache        int32                               `json:"-"`
}

func (m *Field_InputDecoration) Reset()         { *m = Field_InputDecoration{} }
func (m *Field_InputDecoration) String() string { return proto.CompactTextString(m) }
func (*Field_InputDecoration) ProtoMessage()    {}
func (*Field_InputDecoration) Descriptor() ([]byte, []int) {
	return fileDescriptor_23d710dfe11887bd, []int{4, 9}
}

func (m *Field_InputDecoration) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Field_InputDecoration.Unmarshal(m, b)
}
func (m *Field_InputDecoration) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Field_InputDecoration.Marshal(b, m, deterministic)
}
func (m *Field_InputDecoration) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Field_InputDecoration.Merge(m, src)
}
func (m *Field_InputDecoration) XXX_Size() int {
	return xxx_messageInfo_Field_InputDecoration.Size(m)
}
func (m *Field_InputDecoration) XXX_DiscardUnknown() {
	xxx_messageInfo_Field_InputDecoration.DiscardUnknown(m)
}

var xxx_messageInfo_Field_InputDecoration proto.InternalMessageInfo

func (m *Field_InputDecoration) GetIcon() MaterialIcon {
	if m != nil {
		return m.Icon
	}
	return MaterialIcon_noMaterialIcon
}

func (m *Field_InputDecoration) GetPrefixIcon() MaterialIcon {
	if m != nil {
		return m.PrefixIcon
	}
	return MaterialIcon_noMaterialIcon
}

func (m *Field_InputDecoration) GetSuffixIcon() MaterialIcon {
	if m != nil {
		return m.SuffixIcon
	}
	return MaterialIcon_noMaterialIcon
}

func (m *Field_InputDecoration) GetCounter() []Field_InputDecoration_CounterType {
	if m != nil {
		return m.Counter
	}
	return nil
}

type SourceList struct {
	Pager       bool   `protobuf:"varint,1,opt,name=pager,proto3" json:"pager,omitempty"`
	Rows        uint32 `protobuf:"varint,2,opt,name=rows,proto3" json:"rows,omitempty"`
	Remove      bool   `protobuf:"varint,3,opt,name=remove,proto3" json:"remove,omitempty"`
	GroupByType bool   `protobuf:"varint,6,opt,name=groupByType,proto3" json:"groupByType,omitempty"`
	// add custom search widget
	Search               bool     `protobuf:"varint,7,opt,name=search,proto3" json:"search,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SourceList) Reset()         { *m = SourceList{} }
func (m *SourceList) String() string { return proto.CompactTextString(m) }
func (*SourceList) ProtoMessage()    {}
func (*SourceList) Descriptor() ([]byte, []int) {
	return fileDescriptor_23d710dfe11887bd, []int{5}
}

func (m *SourceList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SourceList.Unmarshal(m, b)
}
func (m *SourceList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SourceList.Marshal(b, m, deterministic)
}
func (m *SourceList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SourceList.Merge(m, src)
}
func (m *SourceList) XXX_Size() int {
	return xxx_messageInfo_SourceList.Size(m)
}
func (m *SourceList) XXX_DiscardUnknown() {
	xxx_messageInfo_SourceList.DiscardUnknown(m)
}

var xxx_messageInfo_SourceList proto.InternalMessageInfo

func (m *SourceList) GetPager() bool {
	if m != nil {
		return m.Pager
	}
	return false
}

func (m *SourceList) GetRows() uint32 {
	if m != nil {
		return m.Rows
	}
	return 0
}

func (m *SourceList) GetRemove() bool {
	if m != nil {
		return m.Remove
	}
	return false
}

func (m *SourceList) GetGroupByType() bool {
	if m != nil {
		return m.GroupByType
	}
	return false
}

func (m *SourceList) GetSearch() bool {
	if m != nil {
		return m.Search
	}
	return false
}

type ChooseList struct {
	Src                  *ChooseList_SourceList `protobuf:"bytes,1,opt,name=src,proto3" json:"src,omitempty"`
	Dst                  *ChooseList_DestList   `protobuf:"bytes,2,opt,name=dst,proto3" json:"dst,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *ChooseList) Reset()         { *m = ChooseList{} }
func (m *ChooseList) String() string { return proto.CompactTextString(m) }
func (*ChooseList) ProtoMessage()    {}
func (*ChooseList) Descriptor() ([]byte, []int) {
	return fileDescriptor_23d710dfe11887bd, []int{6}
}

func (m *ChooseList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChooseList.Unmarshal(m, b)
}
func (m *ChooseList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChooseList.Marshal(b, m, deterministic)
}
func (m *ChooseList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChooseList.Merge(m, src)
}
func (m *ChooseList) XXX_Size() int {
	return xxx_messageInfo_ChooseList.Size(m)
}
func (m *ChooseList) XXX_DiscardUnknown() {
	xxx_messageInfo_ChooseList.DiscardUnknown(m)
}

var xxx_messageInfo_ChooseList proto.InternalMessageInfo

func (m *ChooseList) GetSrc() *ChooseList_SourceList {
	if m != nil {
		return m.Src
	}
	return nil
}

func (m *ChooseList) GetDst() *ChooseList_DestList {
	if m != nil {
		return m.Dst
	}
	return nil
}

type ChooseList_SourceList struct {
	Pager       bool   `protobuf:"varint,1,opt,name=pager,proto3" json:"pager,omitempty"`
	Rows        uint32 `protobuf:"varint,2,opt,name=rows,proto3" json:"rows,omitempty"`
	GroupByType bool   `protobuf:"varint,6,opt,name=groupByType,proto3" json:"groupByType,omitempty"`
	// add custom search widget
	Search               bool     `protobuf:"varint,7,opt,name=search,proto3" json:"search,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChooseList_SourceList) Reset()         { *m = ChooseList_SourceList{} }
func (m *ChooseList_SourceList) String() string { return proto.CompactTextString(m) }
func (*ChooseList_SourceList) ProtoMessage()    {}
func (*ChooseList_SourceList) Descriptor() ([]byte, []int) {
	return fileDescriptor_23d710dfe11887bd, []int{6, 0}
}

func (m *ChooseList_SourceList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChooseList_SourceList.Unmarshal(m, b)
}
func (m *ChooseList_SourceList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChooseList_SourceList.Marshal(b, m, deterministic)
}
func (m *ChooseList_SourceList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChooseList_SourceList.Merge(m, src)
}
func (m *ChooseList_SourceList) XXX_Size() int {
	return xxx_messageInfo_ChooseList_SourceList.Size(m)
}
func (m *ChooseList_SourceList) XXX_DiscardUnknown() {
	xxx_messageInfo_ChooseList_SourceList.DiscardUnknown(m)
}

var xxx_messageInfo_ChooseList_SourceList proto.InternalMessageInfo

func (m *ChooseList_SourceList) GetPager() bool {
	if m != nil {
		return m.Pager
	}
	return false
}

func (m *ChooseList_SourceList) GetRows() uint32 {
	if m != nil {
		return m.Rows
	}
	return 0
}

func (m *ChooseList_SourceList) GetGroupByType() bool {
	if m != nil {
		return m.GroupByType
	}
	return false
}

func (m *ChooseList_SourceList) GetSearch() bool {
	if m != nil {
		return m.Search
	}
	return false
}

type ChooseList_DestList struct {
	GroupByType bool   `protobuf:"varint,1,opt,name=groupByType,proto3" json:"groupByType,omitempty"`
	Pager       bool   `protobuf:"varint,2,opt,name=pager,proto3" json:"pager,omitempty"`
	Rows        uint32 `protobuf:"varint,3,opt,name=rows,proto3" json:"rows,omitempty"`
	Add         bool   `protobuf:"varint,4,opt,name=add,proto3" json:"add,omitempty"`
	AddMany     bool   `protobuf:"varint,5,opt,name=addMany,proto3" json:"addMany,omitempty"`
	Remove      bool   `protobuf:"varint,6,opt,name=remove,proto3" json:"remove,omitempty"`
	RemoveAll   bool   `protobuf:"varint,7,opt,name=removeAll,proto3" json:"removeAll,omitempty"`
	Unique      bool   `protobuf:"varint,8,opt,name=unique,proto3" json:"unique,omitempty"`
	Rank        bool   `protobuf:"varint,9,opt,name=rank,proto3" json:"rank,omitempty"`
	// add custom search widget, only enable edit/remove when searching
	Search               bool     `protobuf:"varint,10,opt,name=search,proto3" json:"search,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChooseList_DestList) Reset()         { *m = ChooseList_DestList{} }
func (m *ChooseList_DestList) String() string { return proto.CompactTextString(m) }
func (*ChooseList_DestList) ProtoMessage()    {}
func (*ChooseList_DestList) Descriptor() ([]byte, []int) {
	return fileDescriptor_23d710dfe11887bd, []int{6, 1}
}

func (m *ChooseList_DestList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChooseList_DestList.Unmarshal(m, b)
}
func (m *ChooseList_DestList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChooseList_DestList.Marshal(b, m, deterministic)
}
func (m *ChooseList_DestList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChooseList_DestList.Merge(m, src)
}
func (m *ChooseList_DestList) XXX_Size() int {
	return xxx_messageInfo_ChooseList_DestList.Size(m)
}
func (m *ChooseList_DestList) XXX_DiscardUnknown() {
	xxx_messageInfo_ChooseList_DestList.DiscardUnknown(m)
}

var xxx_messageInfo_ChooseList_DestList proto.InternalMessageInfo

func (m *ChooseList_DestList) GetGroupByType() bool {
	if m != nil {
		return m.GroupByType
	}
	return false
}

func (m *ChooseList_DestList) GetPager() bool {
	if m != nil {
		return m.Pager
	}
	return false
}

func (m *ChooseList_DestList) GetRows() uint32 {
	if m != nil {
		return m.Rows
	}
	return 0
}

func (m *ChooseList_DestList) GetAdd() bool {
	if m != nil {
		return m.Add
	}
	return false
}

func (m *ChooseList_DestList) GetAddMany() bool {
	if m != nil {
		return m.AddMany
	}
	return false
}

func (m *ChooseList_DestList) GetRemove() bool {
	if m != nil {
		return m.Remove
	}
	return false
}

func (m *ChooseList_DestList) GetRemoveAll() bool {
	if m != nil {
		return m.RemoveAll
	}
	return false
}

func (m *ChooseList_DestList) GetUnique() bool {
	if m != nil {
		return m.Unique
	}
	return false
}

func (m *ChooseList_DestList) GetRank() bool {
	if m != nil {
		return m.Rank
	}
	return false
}

func (m *ChooseList_DestList) GetSearch() bool {
	if m != nil {
		return m.Search
	}
	return false
}

var E_DefaultField = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.EnumOptions)(nil),
	ExtensionType: (*Field)(nil),
	Field:         919114,
	Name:          "pgde.form.defaultField",
	Tag:           "bytes,919114,opt,name=defaultField",
	Filename:      "pgde/form/form.proto",
}

var E_InputOption = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.EnumValueOptions)(nil),
	ExtensionType: (*InputOption)(nil),
	Field:         919114,
	Name:          "pgde.form.inputOption",
	Tag:           "bytes,919114,opt,name=inputOption",
	Filename:      "pgde/form/form.proto",
}

var E_Header = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.OneofOptions)(nil),
	ExtensionType: (*OneofHeader)(nil),
	Field:         919114,
	Name:          "pgde.form.header",
	Tag:           "bytes,919114,opt,name=header",
	Filename:      "pgde/form/form.proto",
}

var E_Node = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.MessageOptions)(nil),
	ExtensionType: (*Node)(nil),
	Field:         919114,
	Name:          "pgde.form.node",
	Tag:           "bytes,919114,opt,name=node",
	Filename:      "pgde/form/form.proto",
}

var E_EntryField = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FieldOptions)(nil),
	ExtensionType: (*EntryField)(nil),
	Field:         919114,
	Name:          "pgde.form.entryField",
	Tag:           "bytes,919114,opt,name=entryField",
	Filename:      "pgde/form/form.proto",
}

var E_Field = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FieldOptions)(nil),
	ExtensionType: (*Field)(nil),
	Field:         919115,
	Name:          "pgde.form.field",
	Tag:           "bytes,919115,opt,name=field",
	Filename:      "pgde/form/form.proto",
}

var E_Id = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FieldOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         919116,
	Name:          "pgde.form.id",
	Tag:           "varint,919116,opt,name=id",
	Filename:      "pgde/form/form.proto",
}

func init() {
	proto.RegisterEnum("pgde.form.Protector", Protector_name, Protector_value)
	proto.RegisterEnum("pgde.form.OneofHeader_Title_Show", OneofHeader_Title_Show_name, OneofHeader_Title_Show_value)
	proto.RegisterEnum("pgde.form.OneofHeader_AfterCreate_State", OneofHeader_AfterCreate_State_name, OneofHeader_AfterCreate_State_value)
	proto.RegisterEnum("pgde.form.Node_Type", Node_Type_name, Node_Type_value)
	proto.RegisterEnum("pgde.form.Field_UnitPlace", Field_UnitPlace_name, Field_UnitPlace_value)
	proto.RegisterEnum("pgde.form.Field_TextInput_Type", Field_TextInput_Type_name, Field_TextInput_Type_value)
	proto.RegisterEnum("pgde.form.Field_EnumInput_Type", Field_EnumInput_Type_name, Field_EnumInput_Type_value)
	proto.RegisterEnum("pgde.form.Field_DatetimePickerInput_DatePickerMode", Field_DatetimePickerInput_DatePickerMode_name, Field_DatetimePickerInput_DatePickerMode_value)
	proto.RegisterEnum("pgde.form.Field_InputDecoration_CounterType", Field_InputDecoration_CounterType_name, Field_InputDecoration_CounterType_value)
	proto.RegisterType((*InputOption)(nil), "pgde.form.InputOption")
	proto.RegisterType((*OneofHeader)(nil), "pgde.form.OneofHeader")
	proto.RegisterType((*OneofHeader_Title)(nil), "pgde.form.OneofHeader.Title")
	proto.RegisterType((*OneofHeader_AfterCreate)(nil), "pgde.form.OneofHeader.AfterCreate")
	proto.RegisterType((*Node)(nil), "pgde.form.Node")
	proto.RegisterType((*EntryField)(nil), "pgde.form.EntryField")
	proto.RegisterType((*EntryField_Form)(nil), "pgde.form.EntryField.Form")
	proto.RegisterType((*EntryField_DestList)(nil), "pgde.form.EntryField.DestList")
	proto.RegisterType((*Field)(nil), "pgde.form.Field")
	proto.RegisterType((*Field_TextInput)(nil), "pgde.form.Field.TextInput")
	proto.RegisterType((*Field_SignatureInput)(nil), "pgde.form.Field.SignatureInput")
	proto.RegisterType((*Field_NumberInput)(nil), "pgde.form.Field.NumberInput")
	proto.RegisterType((*Field_StepperInput)(nil), "pgde.form.Field.StepperInput")
	proto.RegisterType((*Field_SliderInput)(nil), "pgde.form.Field.SliderInput")
	proto.RegisterType((*Field_RateInput)(nil), "pgde.form.Field.RateInput")
	proto.RegisterType((*Field_EnumInput)(nil), "pgde.form.Field.EnumInput")
	proto.RegisterType((*Field_SwitchInput)(nil), "pgde.form.Field.SwitchInput")
	proto.RegisterType((*Field_DatetimePickerInput)(nil), "pgde.form.Field.DatetimePickerInput")
	proto.RegisterType((*Field_InputDecoration)(nil), "pgde.form.Field.InputDecoration")
	proto.RegisterType((*SourceList)(nil), "pgde.form.SourceList")
	proto.RegisterType((*ChooseList)(nil), "pgde.form.ChooseList")
	proto.RegisterType((*ChooseList_SourceList)(nil), "pgde.form.ChooseList.SourceList")
	proto.RegisterType((*ChooseList_DestList)(nil), "pgde.form.ChooseList.DestList")
	proto.RegisterExtension(E_DefaultField)
	proto.RegisterExtension(E_InputOption)
	proto.RegisterExtension(E_Header)
	proto.RegisterExtension(E_Node)
	proto.RegisterExtension(E_EntryField)
	proto.RegisterExtension(E_Field)
	proto.RegisterExtension(E_Id)
}

func init() { proto.RegisterFile("pgde/form/form.proto", fileDescriptor_23d710dfe11887bd) }

var fileDescriptor_23d710dfe11887bd = []byte{
	// 1940 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x58, 0x5f, 0x6f, 0x24, 0x47,
	0x11, 0xf7, 0xec, 0x1f, 0xef, 0x6e, 0xad, 0xcf, 0x37, 0xe9, 0xf8, 0x2e, 0xa3, 0xe1, 0x92, 0xbb,
	0x2c, 0x51, 0x64, 0x20, 0xb7, 0x3e, 0x9c, 0x40, 0x0e, 0x47, 0x81, 0x3b, 0xfb, 0xee, 0x70, 0x50,
	0x7c, 0x3e, 0x8d, 0x4d, 0x40, 0x20, 0x90, 0x7a, 0x67, 0x6a, 0x77, 0x5b, 0x9e, 0xed, 0x1e, 0x7a,
	0x7a, 0xce, 0xde, 0x3c, 0x22, 0xf1, 0x44, 0x5e, 0xf8, 0x06, 0x7c, 0x07, 0xbe, 0x40, 0x1e, 0x51,
	0x40, 0x42, 0xe2, 0x8d, 0x37, 0x84, 0xf2, 0x15, 0x78, 0x06, 0x75, 0xf7, 0xfc, 0x5b, 0xaf, 0x7d,
	0x7f, 0x40, 0x81, 0x97, 0x51, 0x77, 0xf5, 0xef, 0x57, 0xdd, 0x5d, 0x53, 0x55, 0x5d, 0xdd, 0xb0,
	0x91, 0x4c, 0x22, 0xdc, 0x1a, 0x0b, 0x39, 0x33, 0x9f, 0x61, 0x22, 0x85, 0x12, 0xa4, 0xa7, 0xa5,
	0x43, 0x2d, 0xf0, 0x6f, 0x4d, 0x84, 0x98, 0xc4, 0xb8, 0x65, 0x06, 0x46, 0xd9, 0x78, 0x2b, 0xc2,
	0x34, 0x94, 0x2c, 0x51, 0x42, 0x5a, 0xb0, 0x7f, 0xad, 0x52, 0x11, 0x8a, 0xb8, 0x14, 0xd7, 0x34,
	0xb3, 0x50, 0xf0, 0x5c, 0x7a, 0xdd, 0x48, 0x33, 0xce, 0x54, 0x6a, 0xbf, 0x0b, 0xe8, 0x4f, 0x51,
	0x0a, 0xf3, 0xb1, 0xd2, 0xc1, 0x0e, 0xf4, 0x3f, 0xe2, 0x49, 0xa6, 0x0e, 0x13, 0xc5, 0x04, 0x27,
	0xdf, 0x82, 0x96, 0x56, 0xe5, 0x39, 0xb7, 0x9c, 0xcd, 0xf5, 0xed, 0xd7, 0x86, 0xe5, 0x2a, 0x87,
	0x07, 0x54, 0xa1, 0x64, 0x34, 0xfe, 0x28, 0x14, 0x3c, 0x30, 0xa0, 0xc1, 0x5f, 0x1b, 0xd0, 0x3f,
	0xe4, 0x28, 0xc6, 0xfb, 0x48, 0x23, 0x94, 0x2f, 0x45, 0x26, 0xef, 0x43, 0x5b, 0x31, 0x15, 0xa3,
	0xd7, 0x30, 0xe8, 0x37, 0x6b, 0xe8, 0x9a, 0xce, 0xe1, 0xb1, 0xc6, 0x0c, 0x8f, 0xa6, 0xe2, 0x34,
	0xb0, 0x78, 0xf2, 0x23, 0xe8, 0xd3, 0xb1, 0x42, 0xb9, 0x27, 0x91, 0x2a, 0xf4, 0x9a, 0x86, 0xbe,
	0x79, 0x09, 0xfd, 0x7e, 0x85, 0x1c, 0x1e, 0x29, 0xaa, 0x30, 0xa8, 0x93, 0xfd, 0x6f, 0x43, 0xdb,
	0x4c, 0x30, 0xd8, 0x84, 0x96, 0x9e, 0x83, 0x74, 0xed, 0x16, 0xdc, 0x15, 0xdd, 0x52, 0x78, 0xa6,
	0x5c, 0x87, 0xac, 0x41, 0x57, 0xcb, 0x8e, 0x75, 0xaf, 0xe1, 0xff, 0x12, 0xfa, 0x35, 0xa5, 0x83,
	0x43, 0x68, 0x1b, 0xbd, 0x1a, 0x3f, 0x65, 0x11, 0x5a, 0xa6, 0xd1, 0xe1, 0x94, 0x3a, 0x1a, 0x0b,
	0x3a, 0x9a, 0x04, 0x60, 0x75, 0x2c, 0xc5, 0xa7, 0xc8, 0xdd, 0x16, 0x59, 0x07, 0x08, 0xa7, 0x94,
	0x4f, 0x90, 0x8e, 0x62, 0x74, 0xdb, 0x83, 0x7f, 0x38, 0xd0, 0x7a, 0x2c, 0x22, 0x24, 0x9b, 0xd0,
	0x52, 0xf3, 0x04, 0x73, 0x6b, 0x6e, 0xd4, 0x36, 0xa8, 0x87, 0x87, 0xc7, 0xf3, 0x04, 0x03, 0x83,
	0x28, 0xed, 0xde, 0x7c, 0x11, 0xbb, 0x6f, 0x43, 0x4f, 0xff, 0x79, 0x0c, 0x95, 0x90, 0x5e, 0x6b,
	0x49, 0xf7, 0x93, 0x62, 0x2c, 0xa8, 0x60, 0x83, 0x43, 0x68, 0xe9, 0xe9, 0xc8, 0x15, 0xe8, 0x65,
	0x3c, 0xc2, 0x31, 0xe3, 0x18, 0xb9, 0x2b, 0xa4, 0x07, 0x6d, 0xe4, 0x4a, 0xce, 0xed, 0x4e, 0x63,
	0xa4, 0x63, 0xb7, 0xa1, 0x5b, 0x4f, 0x19, 0x9e, 0xba, 0x4d, 0xbd, 0x67, 0xbd, 0xbc, 0xc7, 0x74,
	0x86, 0x6e, 0x8b, 0xf4, 0xa1, 0x83, 0x31, 0xce, 0x90, 0x2b, 0xb7, 0x3d, 0xf8, 0xac, 0x05, 0xf0,
	0x50, 0x53, 0x1f, 0x31, 0x8c, 0x23, 0x72, 0x07, 0x5a, 0x7a, 0x72, 0xb3, 0xd5, 0xfe, 0xb6, 0x5f,
	0x5b, 0x4e, 0x05, 0x1a, 0x3e, 0x12, 0x72, 0xb6, 0xbf, 0x12, 0x18, 0x24, 0x79, 0x0f, 0x5a, 0x31,
	0x4b, 0x95, 0x71, 0x9e, 0xfe, 0xf6, 0x1b, 0x17, 0x33, 0x1e, 0x60, 0xaa, 0x3e, 0x66, 0xa9, 0xd2,
	0x2c, 0x8d, 0x26, 0xdf, 0x81, 0x5e, 0x8a, 0x31, 0x86, 0xea, 0x90, 0x5b, 0xc7, 0xe9, 0x6f, 0x5f,
	0xab, 0x51, 0x8f, 0x44, 0x26, 0x43, 0xcc, 0x19, 0x15, 0x92, 0xbc, 0x0f, 0x60, 0x3b, 0x07, 0x94,
	0xcf, 0x8d, 0xcd, 0x16, 0x79, 0x7b, 0x53, 0x21, 0xd2, 0x82, 0x57, 0x83, 0xfa, 0x6f, 0x40, 0x4b,
	0xaf, 0x9a, 0x5c, 0x87, 0x55, 0x89, 0x33, 0xf1, 0xd4, 0x3a, 0x7b, 0x37, 0xc8, 0x7b, 0xfe, 0xbf,
	0x1c, 0xe8, 0x16, 0x8b, 0x24, 0xb7, 0xa0, 0x3f, 0x91, 0x22, 0x4b, 0x76, 0xe7, 0xc7, 0xc5, 0x6f,
	0xef, 0x06, 0x75, 0x11, 0xd9, 0x80, 0x76, 0x42, 0x27, 0x28, 0x73, 0x2d, 0xb6, 0x43, 0xbe, 0x06,
	0x2d, 0x29, 0x4e, 0x53, 0xb3, 0x9f, 0x2b, 0xbb, 0x9d, 0x2f, 0xbe, 0xfc, 0xbc, 0xd9, 0xd8, 0x84,
	0xc0, 0x08, 0x89, 0x0b, 0x4d, 0x1a, 0x45, 0x66, 0xcd, 0xdd, 0x40, 0x37, 0x09, 0x81, 0x16, 0x46,
	0x4c, 0x79, 0x6d, 0x23, 0x32, 0xed, 0xda, 0xfa, 0x56, 0xeb, 0xeb, 0x23, 0x37, 0xa0, 0x67, 0x5b,
	0xf7, 0xe3, 0xd8, 0xeb, 0x98, 0xa1, 0x4a, 0xa0, 0x59, 0x19, 0x67, 0xbf, 0xca, 0xd0, 0xeb, 0x5a,
	0x96, 0xed, 0xe9, 0x19, 0x24, 0xe5, 0x27, 0x5e, 0xcf, 0xce, 0xa0, 0xdb, 0x1a, 0x9b, 0x22, 0x95,
	0xe1, 0xd4, 0x03, 0x8b, 0xb5, 0xbd, 0xdd, 0x16, 0x34, 0x58, 0x3a, 0xf8, 0xdb, 0x06, 0xb4, 0xad,
	0x27, 0xdc, 0x03, 0x88, 0x30, 0x14, 0x92, 0xea, 0x6c, 0x94, 0xfb, 0xc3, 0xad, 0x9a, 0xa9, 0xed,
	0x8f, 0x35, 0x19, 0xeb, 0x41, 0x89, 0x0b, 0x6a, 0x9c, 0x45, 0xff, 0x6e, 0xbc, 0x90, 0x7f, 0x93,
	0x0d, 0x1b, 0xbb, 0xc6, 0x84, 0x5d, 0xed, 0x2d, 0xba, 0x47, 0x6e, 0x40, 0x37, 0x62, 0xa9, 0x0e,
	0xcb, 0xdc, 0x80, 0xfb, 0x2b, 0x41, 0x29, 0x21, 0x03, 0xe8, 0x23, 0x4f, 0x33, 0x89, 0xf7, 0x27,
	0x94, 0x71, 0x6b, 0xce, 0xfd, 0x95, 0xa0, 0x2e, 0xd4, 0x7e, 0xad, 0xe3, 0xdf, 0xeb, 0x2f, 0xf9,
	0xb5, 0xdd, 0x87, 0x4e, 0x07, 0x66, 0x2f, 0xfb, 0x4e, 0x60, 0x90, 0xe4, 0x07, 0xd0, 0x4b, 0xd9,
	0x84, 0x53, 0x95, 0x49, 0xf4, 0xd6, 0x0c, 0xed, 0xe6, 0x12, 0xed, 0xa8, 0x40, 0x14, 0xdc, 0x8a,
	0x43, 0xbe, 0x0b, 0xab, 0x3c, 0x9b, 0x8d, 0x50, 0x7a, 0x57, 0x0c, 0xfb, 0xc6, 0x12, 0xfb, 0xb1,
	0x19, 0x2e, 0xa8, 0x39, 0x9a, 0x7c, 0x0f, 0x3a, 0xa9, 0xc2, 0x24, 0x41, 0xe9, 0xad, 0x1b, 0xe2,
	0xeb, 0xcb, 0xd3, 0xda, 0xf1, 0x82, 0x59, 0xe0, 0xf5, 0x94, 0x69, 0xcc, 0x22, 0x94, 0xde, 0xd5,
	0x4b, 0xa6, 0x3c, 0x32, 0xc3, 0xe5, 0x94, 0x16, 0xad, 0xad, 0x23, 0x75, 0x06, 0x77, 0x2f, 0xb1,
	0x4e, 0x40, 0x55, 0xb9, 0x43, 0x83, 0x24, 0x1f, 0x42, 0x17, 0x79, 0x36, 0x33, 0xf1, 0xf1, 0x8a,
	0xf9, 0xb5, 0xcb, 0xc6, 0x79, 0xc8, 0xb3, 0x99, 0x61, 0x99, 0x0c, 0xb9, 0xef, 0x04, 0x25, 0x65,
	0x31, 0xfc, 0xc9, 0xb3, 0xc2, 0xdf, 0xb9, 0x3c, 0xfc, 0x5f, 0x7d, 0x56, 0xf8, 0x3b, 0xf5, 0xf0,
	0x27, 0x77, 0xa0, 0x8d, 0xb3, 0x11, 0x46, 0xde, 0x86, 0xe1, 0x78, 0x17, 0x24, 0xe6, 0x3d, 0x7d,
	0x9c, 0xef, 0x3b, 0x81, 0x05, 0x92, 0xef, 0x03, 0x8c, 0x84, 0x88, 0x8f, 0x4e, 0x99, 0x0a, 0xa7,
	0xde, 0xb5, 0xcb, 0xcc, 0x69, 0x86, 0x0b, 0xd3, 0xd4, 0x18, 0x64, 0x17, 0xba, 0x11, 0x55, 0xa8,
	0xd8, 0x0c, 0xbd, 0xeb, 0x86, 0xfd, 0xd6, 0x12, 0xfb, 0x41, 0x0e, 0x78, 0xc2, 0xc2, 0x93, 0xea,
	0xa7, 0x94, 0x3c, 0xf2, 0x06, 0xf4, 0xd8, 0x84, 0x0b, 0x89, 0x07, 0x34, 0xf1, 0x5e, 0x33, 0x6e,
	0xed, 0x04, 0x95, 0xc8, 0xff, 0x4b, 0x03, 0x7a, 0xa5, 0xe3, 0x92, 0x3d, 0x58, 0x3b, 0xc1, 0xf9,
	0x48, 0x50, 0x19, 0x1d, 0x57, 0xa7, 0xd5, 0xcd, 0xcb, 0x5d, 0xdd, 0x1e, 0x5c, 0x0b, 0x24, 0x9d,
	0xfa, 0xc4, 0x28, 0x0d, 0x33, 0x89, 0x1a, 0x96, 0xa7, 0xb7, 0xba, 0x48, 0x23, 0x68, 0xa6, 0x44,
	0x28, 0xa4, 0xc4, 0x50, 0xd9, 0x40, 0x0d, 0xea, 0x22, 0xe2, 0x43, 0x77, 0x46, 0xcf, 0x3e, 0x66,
	0x1c, 0x53, 0x13, 0xad, 0xed, 0xa0, 0xec, 0x93, 0x77, 0xe0, 0x15, 0xdd, 0x46, 0x3e, 0x51, 0xd3,
	0x87, 0x7c, 0x2c, 0x64, 0x88, 0x51, 0x9e, 0x00, 0x97, 0x07, 0x06, 0x22, 0x3f, 0xed, 0xd6, 0x01,
	0xf4, 0x04, 0x36, 0xf9, 0xba, 0x2b, 0xfa, 0x3c, 0x2b, 0x8c, 0xe4, 0x36, 0x88, 0x0b, 0x6b, 0x38,
	0xa3, 0x2c, 0xbe, 0x1f, 0x45, 0x12, 0xd3, 0xd4, 0x6d, 0xea, 0xd3, 0x71, 0x96, 0xc5, 0x8a, 0xc5,
	0x8c, 0xeb, 0x03, 0x0f, 0x8a, 0x48, 0x74, 0xdb, 0xfa, 0xa4, 0x4c, 0xa6, 0x82, 0xa3, 0xbb, 0x5a,
	0xd6, 0x04, 0x1d, 0xd2, 0x81, 0x66, 0x26, 0x63, 0xb7, 0xeb, 0xff, 0xdd, 0x81, 0xf5, 0xc5, 0x98,
	0xd6, 0xa9, 0xfe, 0x94, 0x45, 0x6a, 0x6a, 0xec, 0xe9, 0x04, 0xb6, 0xa3, 0xb3, 0xe8, 0x14, 0xd9,
	0x64, 0x6a, 0x4d, 0xe4, 0x04, 0x79, 0x8f, 0xec, 0xc2, 0xd5, 0x11, 0x0d, 0x4f, 0xf4, 0x59, 0xc1,
	0x23, 0xe3, 0x52, 0xf9, 0xe9, 0x76, 0xa9, 0xcb, 0x05, 0xe7, 0x09, 0xe4, 0x3d, 0xe8, 0x26, 0xc8,
	0x2d, 0xb9, 0xf5, 0x1c, 0x72, 0x89, 0x24, 0x6f, 0xc3, 0x7a, 0x82, 0xfc, 0x48, 0x49, 0x71, 0x82,
	0x3f, 0x31, 0x0b, 0x6e, 0x9b, 0x95, 0x9d, 0x93, 0xfa, 0x33, 0xe8, 0xd7, 0xf2, 0x0e, 0x79, 0x0b,
	0x5a, 0xba, 0x34, 0xcd, 0x13, 0xbc, 0x6b, 0x27, 0xb2, 0xc5, 0xaa, 0x29, 0xf5, 0xcc, 0x28, 0xb9,
	0xab, 0xcb, 0x0d, 0xa6, 0x9e, 0xc4, 0x34, 0x2c, 0xca, 0xc4, 0xe5, 0x2c, 0xf1, 0xe3, 0x02, 0x11,
	0x54, 0x60, 0xff, 0xd7, 0x0e, 0xac, 0xd5, 0xd3, 0xd5, 0x57, 0x3d, 0xa1, 0x3e, 0xf3, 0x74, 0x3a,
	0xb4, 0x87, 0x70, 0x60, 0xda, 0xfe, 0x6f, 0x1d, 0xe8, 0xd7, 0x32, 0xdf, 0x57, 0xbe, 0x86, 0x1b,
	0xd0, 0x8b, 0xd8, 0x53, 0x96, 0x32, 0xc1, 0xf3, 0x6a, 0x20, 0xa8, 0x04, 0xfe, 0x5d, 0xe8, 0x95,
	0x09, 0xf5, 0xa5, 0x2a, 0x75, 0x1f, 0xa1, 0x57, 0x26, 0xd5, 0xc1, 0x4f, 0xf3, 0xe0, 0xe8, 0x41,
	0x5b, 0xd2, 0x88, 0x89, 0x3c, 0x2e, 0xa4, 0x48, 0x22, 0x71, 0xaa, 0x6b, 0xde, 0x0d, 0x70, 0x53,
	0x9c, 0xe8, 0x3a, 0x0f, 0xa3, 0x3d, 0xc1, 0x95, 0x14, 0xb1, 0xad, 0x7f, 0xc3, 0x29, 0x86, 0x27,
	0x23, 0x71, 0xe6, 0x36, 0x35, 0x39, 0x9c, 0xb2, 0x24, 0x75, 0x5b, 0x3a, 0x1c, 0x74, 0x81, 0xe0,
	0xb6, 0xfd, 0x6f, 0x40, 0xbf, 0x96, 0xd8, 0x74, 0x3c, 0x17, 0x8c, 0xbc, 0x16, 0x2a, 0xfb, 0xfe,
	0x1f, 0x1c, 0x78, 0xf5, 0x82, 0x34, 0x46, 0x7e, 0x0e, 0xeb, 0x3a, 0x42, 0xad, 0xe8, 0x40, 0x44,
	0x45, 0x3a, 0x7a, 0xf7, 0x45, 0x92, 0xa0, 0x91, 0x55, 0xd4, 0xe0, 0x9c, 0x2a, 0xbd, 0x20, 0x5d,
	0x2c, 0xe9, 0xd3, 0x3f, 0xcf, 0x50, 0x65, 0x7f, 0xf0, 0x75, 0x58, 0x5f, 0x64, 0xeb, 0xe0, 0x8e,
	0xe8, 0xdc, 0xde, 0x06, 0xe6, 0x48, 0xa5, 0xeb, 0xf8, 0xbf, 0x6f, 0xc0, 0xd5, 0x73, 0x95, 0xcb,
	0xcb, 0x5e, 0x99, 0x20, 0x91, 0x38, 0x66, 0x67, 0x5a, 0x96, 0xfb, 0xc6, 0xa5, 0x94, 0x1a, 0xd4,
	0x9c, 0x60, 0xd9, 0xb8, 0x20, 0x3e, 0xe7, 0x9a, 0x50, 0x83, 0x92, 0x47, 0xd0, 0x09, 0x45, 0xc6,
	0x15, 0xea, 0x9c, 0xd0, 0xdc, 0x5c, 0xdf, 0x7e, 0xe7, 0x79, 0xb5, 0xd8, 0x70, 0xcf, 0xe2, 0x4d,
	0x96, 0x2f, 0xc8, 0x83, 0xb7, 0xa1, 0x5f, 0x93, 0x6b, 0x9b, 0x8c, 0xe6, 0x4a, 0xe7, 0xd4, 0x2b,
	0xd0, 0x0b, 0xa7, 0x54, 0xd2, 0x50, 0xa1, 0x74, 0x9d, 0xc1, 0x3d, 0xe8, 0x95, 0xae, 0x4d, 0xae,
	0x42, 0x9f, 0x8b, 0xb2, 0xeb, 0xae, 0xe8, 0x8c, 0x6a, 0xd7, 0xe6, 0x3a, 0x7a, 0x30, 0xa6, 0x23,
	0x8c, 0x8f, 0xac, 0xa0, 0xe1, 0xb7, 0xff, 0xf8, 0xe5, 0xe7, 0x4d, 0x67, 0xb7, 0x03, 0xed, 0x51,
	0xc6, 0xe2, 0x68, 0x77, 0xd5, 0x5e, 0x9f, 0x06, 0xbf, 0x73, 0x00, 0xaa, 0x93, 0xbd, 0xaa, 0xa1,
	0x9d, 0x8b, 0x6a, 0xe8, 0xc6, 0x45, 0x35, 0x74, 0x55, 0x1d, 0x37, 0x17, 0xaa, 0xe3, 0x73, 0x05,
	0xfb, 0xea, 0x72, 0xc1, 0x5e, 0x55, 0xbd, 0x9d, 0x7a, 0xd5, 0x3b, 0xf8, 0x67, 0x13, 0xa0, 0xaa,
	0x1a, 0xc8, 0x36, 0x34, 0x53, 0x19, 0x5e, 0x50, 0xed, 0x56, 0x98, 0x5a, 0x71, 0x12, 0x68, 0x30,
	0xb9, 0x03, 0xcd, 0xe8, 0xc2, 0xfb, 0x4f, 0x8d, 0x53, 0x5c, 0x2d, 0x02, 0x0d, 0xf5, 0xe7, 0xff,
	0xad, 0x1d, 0xfe, 0xe3, 0xfd, 0xfa, 0xbf, 0x69, 0xfc, 0xef, 0xef, 0x39, 0x1e, 0x74, 0x68, 0x14,
	0x99, 0x92, 0xcd, 0x9e, 0xf4, 0x45, 0xf7, 0xff, 0x77, 0xdb, 0xf9, 0xe6, 0x3d, 0xe8, 0x95, 0xf7,
	0x0f, 0xeb, 0xde, 0x65, 0xd7, 0x5d, 0xd1, 0x29, 0x23, 0x61, 0x3a, 0x85, 0xf6, 0xa1, 0x93, 0x50,
	0xa5, 0x50, 0x72, 0x9b, 0x39, 0x13, 0x9a, 0xa6, 0xa7, 0x42, 0x46, 0x6e, 0x73, 0xe7, 0x18, 0xd6,
	0x22, 0x1c, 0xd3, 0x2c, 0x56, 0xf6, 0xbe, 0x74, 0x63, 0x68, 0x1f, 0x8f, 0x86, 0xc5, 0xe3, 0x91,
	0xa9, 0x7f, 0xed, 0x63, 0x4e, 0xea, 0x7d, 0xf1, 0xd9, 0xdd, 0xfa, 0x59, 0x53, 0x45, 0x6d, 0xb0,
	0xa0, 0x65, 0xe7, 0x17, 0xd0, 0x67, 0xb5, 0x47, 0xa0, 0x37, 0x2f, 0x54, 0xfa, 0x09, 0x8d, 0x33,
	0x3c, 0xaf, 0xf9, 0x7a, 0x4d, 0x73, 0xed, 0x1d, 0x29, 0xa8, 0xeb, 0xdb, 0x39, 0xd4, 0x65, 0x8b,
	0x79, 0x21, 0x7a, 0x7d, 0x49, 0xb3, 0x79, 0xac, 0x79, 0x96, 0xd6, 0xda, 0x6b, 0x4e, 0x90, 0xab,
	0xd9, 0x79, 0x04, 0x2d, 0xae, 0x93, 0xec, 0xcd, 0x25, 0x75, 0x07, 0x98, 0xa6, 0x74, 0xb2, 0xb4,
	0xcc, 0xab, 0xe7, 0x5e, 0x4f, 0x02, 0xc3, 0xdf, 0xf9, 0x04, 0x00, 0xab, 0x57, 0x88, 0xe5, 0xc5,
	0x19, 0xf9, 0x79, 0x5d, 0xd7, 0x2e, 0x7c, 0x6c, 0x08, 0x6a, 0x9a, 0x76, 0x7e, 0x08, 0xed, 0xf1,
	0x8b, 0xa8, 0xfc, 0xd3, 0xa5, 0xff, 0xc7, 0xf2, 0x77, 0xb6, 0xa0, 0xc1, 0x9e, 0xab, 0xe5, 0xcf,
	0x46, 0x4b, 0x37, 0x68, 0xb0, 0x68, 0xf7, 0xc3, 0x9f, 0x7d, 0x30, 0x61, 0x6a, 0x9a, 0x8d, 0x86,
	0xa1, 0x98, 0x6d, 0xe1, 0x2c, 0x61, 0x12, 0xc7, 0xe2, 0xcc, 0xbe, 0x2d, 0x86, 0xb7, 0x27, 0xc8,
	0x6f, 0x47, 0x54, 0xaa, 0xdb, 0x78, 0xa6, 0xb6, 0x92, 0x93, 0xc9, 0x56, 0xf9, 0x82, 0xf8, 0x81,
	0xfe, 0x8c, 0x56, 0x0d, 0xee, 0xdd, 0x7f, 0x07, 0x00, 0x00, 0xff, 0xff, 0xc8, 0x7e, 0xbe, 0x01,
	0xb4, 0x14, 0x00, 0x00,
}
