// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pgde/form/form.proto

package form

import (
	fmt "fmt"
	units "github.com/empirefox/protoc-gen-dart-ext/pkg/pgde/units"
	_ "github.com/empirefox/protoc-gen-dart-ext/pkg/pgde/zero"
	proto "github.com/golang/protobuf/proto"
	descriptor "github.com/golang/protobuf/protoc-gen-go/descriptor"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Protector int32

const (
	Protector_noProtector Protector = 0
	Protector_pin         Protector = 1
	Protector_pattern     Protector = 2
	Protector_password    Protector = 3
)

var Protector_name = map[int32]string{
	0: "noProtector",
	1: "pin",
	2: "pattern",
	3: "password",
}

var Protector_value = map[string]int32{
	"noProtector": 0,
	"pin":         1,
	"pattern":     2,
	"password":    3,
}

func (x Protector) String() string {
	return proto.EnumName(Protector_name, int32(x))
}

func (Protector) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_23d710dfe11887bd, []int{0}
}

// configurable on all number fields
type UnitPlace int32

const (
	UnitPlace_noUnitPlace UnitPlace = 0
	UnitPlace_suffix      UnitPlace = 1
	UnitPlace_labelSuffix UnitPlace = 2
)

var UnitPlace_name = map[int32]string{
	0: "noUnitPlace",
	1: "suffix",
	2: "labelSuffix",
}

var UnitPlace_value = map[string]int32{
	"noUnitPlace": 0,
	"suffix":      1,
	"labelSuffix": 2,
}

func (x UnitPlace) String() string {
	return proto.EnumName(UnitPlace_name, int32(x))
}

func (UnitPlace) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_23d710dfe11887bd, []int{1}
}

type TextInput_Type int32

const (
	TextInput_autoByType   TextInput_Type = 0
	TextInput_datetime     TextInput_Type = 2
	TextInput_emailAddress TextInput_Type = 3
	TextInput_multiline    TextInput_Type = 4
	TextInput_number       TextInput_Type = 5
	TextInput_phone        TextInput_Type = 6
	TextInput_text         TextInput_Type = 7
	TextInput_url          TextInput_Type = 8
)

var TextInput_Type_name = map[int32]string{
	0: "autoByType",
	2: "datetime",
	3: "emailAddress",
	4: "multiline",
	5: "number",
	6: "phone",
	7: "text",
	8: "url",
}

var TextInput_Type_value = map[string]int32{
	"autoByType":   0,
	"datetime":     2,
	"emailAddress": 3,
	"multiline":    4,
	"number":       5,
	"phone":        6,
	"text":         7,
	"url":          8,
}

func (x TextInput_Type) String() string {
	return proto.EnumName(TextInput_Type_name, int32(x))
}

func (TextInput_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_23d710dfe11887bd, []int{3, 0}
}

type RadioInput_Type int32

const (
	RadioInput_radio RadioInput_Type = 0
	// extract a new message?
	RadioInput_dropdown         RadioInput_Type = 1
	RadioInput_segmentedControl RadioInput_Type = 2
)

var RadioInput_Type_name = map[int32]string{
	0: "radio",
	1: "dropdown",
	2: "segmentedControl",
}

var RadioInput_Type_value = map[string]int32{
	"radio":            0,
	"dropdown":         1,
	"segmentedControl": 2,
}

func (x RadioInput_Type) String() string {
	return proto.EnumName(RadioInput_Type_name, int32(x))
}

func (RadioInput_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_23d710dfe11887bd, []int{10, 0}
}

type ListInput_Type int32

const (
	// values must be checked from fixed list
	ListInput_checkbox ListInput_Type = 0
	// values can be others
	ListInput_chips ListInput_Type = 1
)

var ListInput_Type_name = map[int32]string{
	0: "checkbox",
	1: "chips",
}

var ListInput_Type_value = map[string]int32{
	"checkbox": 0,
	"chips":    1,
}

func (x ListInput_Type) String() string {
	return proto.EnumName(ListInput_Type_name, int32(x))
}

func (ListInput_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_23d710dfe11887bd, []int{12, 0}
}

type DatetimePickerInput_DatePickerMode int32

const (
	DatetimePickerInput_day  DatetimePickerInput_DatePickerMode = 0
	DatetimePickerInput_year DatetimePickerInput_DatePickerMode = 1
)

var DatetimePickerInput_DatePickerMode_name = map[int32]string{
	0: "day",
	1: "year",
}

var DatetimePickerInput_DatePickerMode_value = map[string]int32{
	"day":  0,
	"year": 1,
}

func (x DatetimePickerInput_DatePickerMode) String() string {
	return proto.EnumName(DatetimePickerInput_DatePickerMode_name, int32(x))
}

func (DatetimePickerInput_DatePickerMode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_23d710dfe11887bd, []int{13, 0}
}

type InputDecoration_CounterType int32

const (
	InputDecoration_byte      InputDecoration_CounterType = 0
	InputDecoration_character InputDecoration_CounterType = 1
)

var InputDecoration_CounterType_name = map[int32]string{
	0: "byte",
	1: "character",
}

var InputDecoration_CounterType_value = map[string]int32{
	"byte":      0,
	"character": 1,
}

func (x InputDecoration_CounterType) String() string {
	return proto.EnumName(InputDecoration_CounterType_name, int32(x))
}

func (InputDecoration_CounterType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_23d710dfe11887bd, []int{16, 0}
}

type InputOption struct {
	Icon                 MaterialIcon `protobuf:"varint,1,opt,name=icon,proto3,enum=pgde.form.MaterialIcon" json:"icon,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *InputOption) Reset()         { *m = InputOption{} }
func (m *InputOption) String() string { return proto.CompactTextString(m) }
func (*InputOption) ProtoMessage()    {}
func (*InputOption) Descriptor() ([]byte, []int) {
	return fileDescriptor_23d710dfe11887bd, []int{0}
}

func (m *InputOption) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InputOption.Unmarshal(m, b)
}
func (m *InputOption) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InputOption.Marshal(b, m, deterministic)
}
func (m *InputOption) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InputOption.Merge(m, src)
}
func (m *InputOption) XXX_Size() int {
	return xxx_messageInfo_InputOption.Size(m)
}
func (m *InputOption) XXX_DiscardUnknown() {
	xxx_messageInfo_InputOption.DiscardUnknown(m)
}

var xxx_messageInfo_InputOption proto.InternalMessageInfo

func (m *InputOption) GetIcon() MaterialIcon {
	if m != nil {
		return m.Icon
	}
	return MaterialIcon_noMaterialIcon
}

type Node struct {
	Ignore               bool         `protobuf:"varint,1,opt,name=ignore,proto3" json:"ignore,omitempty"`
	Icon                 MaterialIcon `protobuf:"varint,2,opt,name=icon,proto3,enum=pgde.form.MaterialIcon" json:"icon,omitempty"`
	Protector            Protector    `protobuf:"varint,3,opt,name=protector,proto3,enum=pgde.form.Protector" json:"protector,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Node) Reset()         { *m = Node{} }
func (m *Node) String() string { return proto.CompactTextString(m) }
func (*Node) ProtoMessage()    {}
func (*Node) Descriptor() ([]byte, []int) {
	return fileDescriptor_23d710dfe11887bd, []int{1}
}

func (m *Node) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Node.Unmarshal(m, b)
}
func (m *Node) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Node.Marshal(b, m, deterministic)
}
func (m *Node) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Node.Merge(m, src)
}
func (m *Node) XXX_Size() int {
	return xxx_messageInfo_Node.Size(m)
}
func (m *Node) XXX_DiscardUnknown() {
	xxx_messageInfo_Node.DiscardUnknown(m)
}

var xxx_messageInfo_Node proto.InternalMessageInfo

func (m *Node) GetIgnore() bool {
	if m != nil {
		return m.Ignore
	}
	return false
}

func (m *Node) GetIcon() MaterialIcon {
	if m != nil {
		return m.Icon
	}
	return MaterialIcon_noMaterialIcon
}

func (m *Node) GetProtector() Protector {
	if m != nil {
		return m.Protector
	}
	return Protector_noProtector
}

type Field struct {
	Decoration *InputDecoration `protobuf:"bytes,1,opt,name=decoration,proto3" json:"decoration,omitempty"`
	Protector  Protector        `protobuf:"varint,2,opt,name=protector,proto3,enum=pgde.form.Protector" json:"protector,omitempty"`
	// Types that are valid to be assigned to Build:
	//	*Field_Hide
	//	*Field_Disabled
	//	*Field_EnsureAgain
	//	*Field_Embed
	Build isField_Build `protobuf_oneof:"build"`
	// Types that are valid to be assigned to Type:
	//	*Field_Text
	//	*Field_TypeAhead
	//	*Field_Signature
	//	*Field_Number
	//	*Field_Stepper
	//	*Field_Slider
	//	*Field_Rate
	//	*Field_Radio
	//	*Field_BoolSwitch
	//	*Field_List
	//	*Field_Datetime
	//	*Field_Map
	Type                 isField_Type `protobuf_oneof:"type"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Field) Reset()         { *m = Field{} }
func (m *Field) String() string { return proto.CompactTextString(m) }
func (*Field) ProtoMessage()    {}
func (*Field) Descriptor() ([]byte, []int) {
	return fileDescriptor_23d710dfe11887bd, []int{2}
}

func (m *Field) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Field.Unmarshal(m, b)
}
func (m *Field) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Field.Marshal(b, m, deterministic)
}
func (m *Field) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Field.Merge(m, src)
}
func (m *Field) XXX_Size() int {
	return xxx_messageInfo_Field.Size(m)
}
func (m *Field) XXX_DiscardUnknown() {
	xxx_messageInfo_Field.DiscardUnknown(m)
}

var xxx_messageInfo_Field proto.InternalMessageInfo

func (m *Field) GetDecoration() *InputDecoration {
	if m != nil {
		return m.Decoration
	}
	return nil
}

func (m *Field) GetProtector() Protector {
	if m != nil {
		return m.Protector
	}
	return Protector_noProtector
}

type isField_Build interface {
	isField_Build()
}

type Field_Hide struct {
	Hide bool `protobuf:"varint,3,opt,name=hide,proto3,oneof"`
}

type Field_Disabled struct {
	Disabled bool `protobuf:"varint,4,opt,name=disabled,proto3,oneof"`
}

type Field_EnsureAgain struct {
	EnsureAgain bool `protobuf:"varint,5,opt,name=ensureAgain,proto3,oneof"`
}

type Field_Embed struct {
	Embed bool `protobuf:"varint,6,opt,name=embed,proto3,oneof"`
}

func (*Field_Hide) isField_Build() {}

func (*Field_Disabled) isField_Build() {}

func (*Field_EnsureAgain) isField_Build() {}

func (*Field_Embed) isField_Build() {}

func (m *Field) GetBuild() isField_Build {
	if m != nil {
		return m.Build
	}
	return nil
}

func (m *Field) GetHide() bool {
	if x, ok := m.GetBuild().(*Field_Hide); ok {
		return x.Hide
	}
	return false
}

func (m *Field) GetDisabled() bool {
	if x, ok := m.GetBuild().(*Field_Disabled); ok {
		return x.Disabled
	}
	return false
}

func (m *Field) GetEnsureAgain() bool {
	if x, ok := m.GetBuild().(*Field_EnsureAgain); ok {
		return x.EnsureAgain
	}
	return false
}

func (m *Field) GetEmbed() bool {
	if x, ok := m.GetBuild().(*Field_Embed); ok {
		return x.Embed
	}
	return false
}

type isField_Type interface {
	isField_Type()
}

type Field_Text struct {
	Text *TextInput `protobuf:"bytes,11,opt,name=text,proto3,oneof"`
}

type Field_TypeAhead struct {
	TypeAhead *TypeAheadInput `protobuf:"bytes,12,opt,name=typeAhead,proto3,oneof"`
}

type Field_Signature struct {
	Signature *SignatureInput `protobuf:"bytes,13,opt,name=signature,proto3,oneof"`
}

type Field_Number struct {
	Number *NumberInput `protobuf:"bytes,14,opt,name=number,proto3,oneof"`
}

type Field_Stepper struct {
	Stepper *StepperInput `protobuf:"bytes,15,opt,name=stepper,proto3,oneof"`
}

type Field_Slider struct {
	Slider *SliderInput `protobuf:"bytes,16,opt,name=slider,proto3,oneof"`
}

type Field_Rate struct {
	Rate *RateInput `protobuf:"bytes,17,opt,name=rate,proto3,oneof"`
}

type Field_Radio struct {
	Radio *RadioInput `protobuf:"bytes,18,opt,name=radio,proto3,oneof"`
}

type Field_BoolSwitch struct {
	BoolSwitch *SwitchInput `protobuf:"bytes,19,opt,name=boolSwitch,proto3,oneof"`
}

type Field_List struct {
	List *ListInput `protobuf:"bytes,20,opt,name=list,proto3,oneof"`
}

type Field_Datetime struct {
	Datetime *DatetimePickerInput `protobuf:"bytes,21,opt,name=datetime,proto3,oneof"`
}

type Field_Map struct {
	Map *MapInput `protobuf:"bytes,22,opt,name=map,proto3,oneof"`
}

func (*Field_Text) isField_Type() {}

func (*Field_TypeAhead) isField_Type() {}

func (*Field_Signature) isField_Type() {}

func (*Field_Number) isField_Type() {}

func (*Field_Stepper) isField_Type() {}

func (*Field_Slider) isField_Type() {}

func (*Field_Rate) isField_Type() {}

func (*Field_Radio) isField_Type() {}

func (*Field_BoolSwitch) isField_Type() {}

func (*Field_List) isField_Type() {}

func (*Field_Datetime) isField_Type() {}

func (*Field_Map) isField_Type() {}

func (m *Field) GetType() isField_Type {
	if m != nil {
		return m.Type
	}
	return nil
}

func (m *Field) GetText() *TextInput {
	if x, ok := m.GetType().(*Field_Text); ok {
		return x.Text
	}
	return nil
}

func (m *Field) GetTypeAhead() *TypeAheadInput {
	if x, ok := m.GetType().(*Field_TypeAhead); ok {
		return x.TypeAhead
	}
	return nil
}

func (m *Field) GetSignature() *SignatureInput {
	if x, ok := m.GetType().(*Field_Signature); ok {
		return x.Signature
	}
	return nil
}

func (m *Field) GetNumber() *NumberInput {
	if x, ok := m.GetType().(*Field_Number); ok {
		return x.Number
	}
	return nil
}

func (m *Field) GetStepper() *StepperInput {
	if x, ok := m.GetType().(*Field_Stepper); ok {
		return x.Stepper
	}
	return nil
}

func (m *Field) GetSlider() *SliderInput {
	if x, ok := m.GetType().(*Field_Slider); ok {
		return x.Slider
	}
	return nil
}

func (m *Field) GetRate() *RateInput {
	if x, ok := m.GetType().(*Field_Rate); ok {
		return x.Rate
	}
	return nil
}

func (m *Field) GetRadio() *RadioInput {
	if x, ok := m.GetType().(*Field_Radio); ok {
		return x.Radio
	}
	return nil
}

func (m *Field) GetBoolSwitch() *SwitchInput {
	if x, ok := m.GetType().(*Field_BoolSwitch); ok {
		return x.BoolSwitch
	}
	return nil
}

func (m *Field) GetList() *ListInput {
	if x, ok := m.GetType().(*Field_List); ok {
		return x.List
	}
	return nil
}

func (m *Field) GetDatetime() *DatetimePickerInput {
	if x, ok := m.GetType().(*Field_Datetime); ok {
		return x.Datetime
	}
	return nil
}

func (m *Field) GetMap() *MapInput {
	if x, ok := m.GetType().(*Field_Map); ok {
		return x.Map
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Field) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Field_Hide)(nil),
		(*Field_Disabled)(nil),
		(*Field_EnsureAgain)(nil),
		(*Field_Embed)(nil),
		(*Field_Text)(nil),
		(*Field_TypeAhead)(nil),
		(*Field_Signature)(nil),
		(*Field_Number)(nil),
		(*Field_Stepper)(nil),
		(*Field_Slider)(nil),
		(*Field_Rate)(nil),
		(*Field_Radio)(nil),
		(*Field_BoolSwitch)(nil),
		(*Field_List)(nil),
		(*Field_Datetime)(nil),
		(*Field_Map)(nil),
	}
}

type TextInput struct {
	KeyboardType         TextInput_Type `protobuf:"varint,1,opt,name=keyboardType,proto3,enum=pgde.form.TextInput_Type" json:"keyboardType,omitempty"`
	ObscureText          bool           `protobuf:"varint,2,opt,name=obscureText,proto3" json:"obscureText,omitempty"`
	Autocorrect          bool           `protobuf:"varint,3,opt,name=autocorrect,proto3" json:"autocorrect,omitempty"`
	MaxLines             int32          `protobuf:"varint,4,opt,name=maxLines,proto3" json:"maxLines,omitempty"`
	MaxLengthEnforced    bool           `protobuf:"varint,5,opt,name=maxLengthEnforced,proto3" json:"maxLengthEnforced,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *TextInput) Reset()         { *m = TextInput{} }
func (m *TextInput) String() string { return proto.CompactTextString(m) }
func (*TextInput) ProtoMessage()    {}
func (*TextInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_23d710dfe11887bd, []int{3}
}

func (m *TextInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TextInput.Unmarshal(m, b)
}
func (m *TextInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TextInput.Marshal(b, m, deterministic)
}
func (m *TextInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TextInput.Merge(m, src)
}
func (m *TextInput) XXX_Size() int {
	return xxx_messageInfo_TextInput.Size(m)
}
func (m *TextInput) XXX_DiscardUnknown() {
	xxx_messageInfo_TextInput.DiscardUnknown(m)
}

var xxx_messageInfo_TextInput proto.InternalMessageInfo

func (m *TextInput) GetKeyboardType() TextInput_Type {
	if m != nil {
		return m.KeyboardType
	}
	return TextInput_autoByType
}

func (m *TextInput) GetObscureText() bool {
	if m != nil {
		return m.ObscureText
	}
	return false
}

func (m *TextInput) GetAutocorrect() bool {
	if m != nil {
		return m.Autocorrect
	}
	return false
}

func (m *TextInput) GetMaxLines() int32 {
	if m != nil {
		return m.MaxLines
	}
	return 0
}

func (m *TextInput) GetMaxLengthEnforced() bool {
	if m != nil {
		return m.MaxLengthEnforced
	}
	return false
}

type TypeAheadInput struct {
	// Types that are valid to be assigned to Builder:
	//	*TypeAheadInput_CodeAccessor
	//	*TypeAheadInput_FromEnum
	Builder              isTypeAheadInput_Builder `protobuf_oneof:"builder"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *TypeAheadInput) Reset()         { *m = TypeAheadInput{} }
func (m *TypeAheadInput) String() string { return proto.CompactTextString(m) }
func (*TypeAheadInput) ProtoMessage()    {}
func (*TypeAheadInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_23d710dfe11887bd, []int{4}
}

func (m *TypeAheadInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TypeAheadInput.Unmarshal(m, b)
}
func (m *TypeAheadInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TypeAheadInput.Marshal(b, m, deterministic)
}
func (m *TypeAheadInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TypeAheadInput.Merge(m, src)
}
func (m *TypeAheadInput) XXX_Size() int {
	return xxx_messageInfo_TypeAheadInput.Size(m)
}
func (m *TypeAheadInput) XXX_DiscardUnknown() {
	xxx_messageInfo_TypeAheadInput.DiscardUnknown(m)
}

var xxx_messageInfo_TypeAheadInput proto.InternalMessageInfo

type isTypeAheadInput_Builder interface {
	isTypeAheadInput_Builder()
}

type TypeAheadInput_CodeAccessor struct {
	CodeAccessor string `protobuf:"bytes,1,opt,name=codeAccessor,proto3,oneof"`
}

type TypeAheadInput_FromEnum struct {
	FromEnum bool `protobuf:"varint,2,opt,name=fromEnum,proto3,oneof"`
}

func (*TypeAheadInput_CodeAccessor) isTypeAheadInput_Builder() {}

func (*TypeAheadInput_FromEnum) isTypeAheadInput_Builder() {}

func (m *TypeAheadInput) GetBuilder() isTypeAheadInput_Builder {
	if m != nil {
		return m.Builder
	}
	return nil
}

func (m *TypeAheadInput) GetCodeAccessor() string {
	if x, ok := m.GetBuilder().(*TypeAheadInput_CodeAccessor); ok {
		return x.CodeAccessor
	}
	return ""
}

func (m *TypeAheadInput) GetFromEnum() bool {
	if x, ok := m.GetBuilder().(*TypeAheadInput_FromEnum); ok {
		return x.FromEnum
	}
	return false
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*TypeAheadInput) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*TypeAheadInput_CodeAccessor)(nil),
		(*TypeAheadInput_FromEnum)(nil),
	}
}

type SignatureInput struct {
	Width                float64        `protobuf:"fixed64,1,opt,name=width,proto3" json:"width,omitempty"`
	Height               float64        `protobuf:"fixed64,2,opt,name=height,proto3" json:"height,omitempty"`
	BackgroundColor      *MaterialColor `protobuf:"bytes,3,opt,name=backgroundColor,proto3" json:"backgroundColor,omitempty"`
	PenColor             *MaterialColor `protobuf:"bytes,4,opt,name=penColor,proto3" json:"penColor,omitempty"`
	PenStrokeWidth       float64        `protobuf:"fixed64,5,opt,name=penStrokeWidth,proto3" json:"penStrokeWidth,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *SignatureInput) Reset()         { *m = SignatureInput{} }
func (m *SignatureInput) String() string { return proto.CompactTextString(m) }
func (*SignatureInput) ProtoMessage()    {}
func (*SignatureInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_23d710dfe11887bd, []int{5}
}

func (m *SignatureInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignatureInput.Unmarshal(m, b)
}
func (m *SignatureInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignatureInput.Marshal(b, m, deterministic)
}
func (m *SignatureInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignatureInput.Merge(m, src)
}
func (m *SignatureInput) XXX_Size() int {
	return xxx_messageInfo_SignatureInput.Size(m)
}
func (m *SignatureInput) XXX_DiscardUnknown() {
	xxx_messageInfo_SignatureInput.DiscardUnknown(m)
}

var xxx_messageInfo_SignatureInput proto.InternalMessageInfo

func (m *SignatureInput) GetWidth() float64 {
	if m != nil {
		return m.Width
	}
	return 0
}

func (m *SignatureInput) GetHeight() float64 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *SignatureInput) GetBackgroundColor() *MaterialColor {
	if m != nil {
		return m.BackgroundColor
	}
	return nil
}

func (m *SignatureInput) GetPenColor() *MaterialColor {
	if m != nil {
		return m.PenColor
	}
	return nil
}

func (m *SignatureInput) GetPenStrokeWidth() float64 {
	if m != nil {
		return m.PenStrokeWidth
	}
	return 0
}

type NumberInput struct {
	Unit                 *units.Show `protobuf:"bytes,1,opt,name=unit,proto3" json:"unit,omitempty"`
	UnitPlace            UnitPlace   `protobuf:"varint,2,opt,name=unitPlace,proto3,enum=pgde.form.UnitPlace" json:"unitPlace,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *NumberInput) Reset()         { *m = NumberInput{} }
func (m *NumberInput) String() string { return proto.CompactTextString(m) }
func (*NumberInput) ProtoMessage()    {}
func (*NumberInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_23d710dfe11887bd, []int{6}
}

func (m *NumberInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NumberInput.Unmarshal(m, b)
}
func (m *NumberInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NumberInput.Marshal(b, m, deterministic)
}
func (m *NumberInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NumberInput.Merge(m, src)
}
func (m *NumberInput) XXX_Size() int {
	return xxx_messageInfo_NumberInput.Size(m)
}
func (m *NumberInput) XXX_DiscardUnknown() {
	xxx_messageInfo_NumberInput.DiscardUnknown(m)
}

var xxx_messageInfo_NumberInput proto.InternalMessageInfo

func (m *NumberInput) GetUnit() *units.Show {
	if m != nil {
		return m.Unit
	}
	return nil
}

func (m *NumberInput) GetUnitPlace() UnitPlace {
	if m != nil {
		return m.UnitPlace
	}
	return UnitPlace_noUnitPlace
}

type StepperInput struct {
	Unit                 *units.Show `protobuf:"bytes,1,opt,name=unit,proto3" json:"unit,omitempty"`
	UnitPlace            UnitPlace   `protobuf:"varint,2,opt,name=unitPlace,proto3,enum=pgde.form.UnitPlace" json:"unitPlace,omitempty"`
	Step                 uint32      `protobuf:"varint,3,opt,name=step,proto3" json:"step,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *StepperInput) Reset()         { *m = StepperInput{} }
func (m *StepperInput) String() string { return proto.CompactTextString(m) }
func (*StepperInput) ProtoMessage()    {}
func (*StepperInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_23d710dfe11887bd, []int{7}
}

func (m *StepperInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StepperInput.Unmarshal(m, b)
}
func (m *StepperInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StepperInput.Marshal(b, m, deterministic)
}
func (m *StepperInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StepperInput.Merge(m, src)
}
func (m *StepperInput) XXX_Size() int {
	return xxx_messageInfo_StepperInput.Size(m)
}
func (m *StepperInput) XXX_DiscardUnknown() {
	xxx_messageInfo_StepperInput.DiscardUnknown(m)
}

var xxx_messageInfo_StepperInput proto.InternalMessageInfo

func (m *StepperInput) GetUnit() *units.Show {
	if m != nil {
		return m.Unit
	}
	return nil
}

func (m *StepperInput) GetUnitPlace() UnitPlace {
	if m != nil {
		return m.UnitPlace
	}
	return UnitPlace_noUnitPlace
}

func (m *StepperInput) GetStep() uint32 {
	if m != nil {
		return m.Step
	}
	return 0
}

type SliderInput struct {
	Unit                 *units.Show `protobuf:"bytes,1,opt,name=unit,proto3" json:"unit,omitempty"`
	UnitPlace            UnitPlace   `protobuf:"varint,2,opt,name=unitPlace,proto3,enum=pgde.form.UnitPlace" json:"unitPlace,omitempty"`
	Divisions            uint32      `protobuf:"varint,3,opt,name=divisions,proto3" json:"divisions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *SliderInput) Reset()         { *m = SliderInput{} }
func (m *SliderInput) String() string { return proto.CompactTextString(m) }
func (*SliderInput) ProtoMessage()    {}
func (*SliderInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_23d710dfe11887bd, []int{8}
}

func (m *SliderInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SliderInput.Unmarshal(m, b)
}
func (m *SliderInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SliderInput.Marshal(b, m, deterministic)
}
func (m *SliderInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SliderInput.Merge(m, src)
}
func (m *SliderInput) XXX_Size() int {
	return xxx_messageInfo_SliderInput.Size(m)
}
func (m *SliderInput) XXX_DiscardUnknown() {
	xxx_messageInfo_SliderInput.DiscardUnknown(m)
}

var xxx_messageInfo_SliderInput proto.InternalMessageInfo

func (m *SliderInput) GetUnit() *units.Show {
	if m != nil {
		return m.Unit
	}
	return nil
}

func (m *SliderInput) GetUnitPlace() UnitPlace {
	if m != nil {
		return m.UnitPlace
	}
	return UnitPlace_noUnitPlace
}

func (m *SliderInput) GetDivisions() uint32 {
	if m != nil {
		return m.Divisions
	}
	return 0
}

type RateInput struct {
	Icon                 MaterialIcon `protobuf:"varint,1,opt,name=icon,proto3,enum=pgde.form.MaterialIcon" json:"icon,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *RateInput) Reset()         { *m = RateInput{} }
func (m *RateInput) String() string { return proto.CompactTextString(m) }
func (*RateInput) ProtoMessage()    {}
func (*RateInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_23d710dfe11887bd, []int{9}
}

func (m *RateInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RateInput.Unmarshal(m, b)
}
func (m *RateInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RateInput.Marshal(b, m, deterministic)
}
func (m *RateInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RateInput.Merge(m, src)
}
func (m *RateInput) XXX_Size() int {
	return xxx_messageInfo_RateInput.Size(m)
}
func (m *RateInput) XXX_DiscardUnknown() {
	xxx_messageInfo_RateInput.DiscardUnknown(m)
}

var xxx_messageInfo_RateInput proto.InternalMessageInfo

func (m *RateInput) GetIcon() MaterialIcon {
	if m != nil {
		return m.Icon
	}
	return MaterialIcon_noMaterialIcon
}

type RadioInput struct {
	Type RadioInput_Type `protobuf:"varint,1,opt,name=type,proto3,enum=pgde.form.RadioInput_Type" json:"type,omitempty"`
	// Types that are valid to be assigned to Builder:
	//	*RadioInput_CodeAccessor
	//	*RadioInput_FromEnum
	Builder              isRadioInput_Builder `protobuf_oneof:"builder"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *RadioInput) Reset()         { *m = RadioInput{} }
func (m *RadioInput) String() string { return proto.CompactTextString(m) }
func (*RadioInput) ProtoMessage()    {}
func (*RadioInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_23d710dfe11887bd, []int{10}
}

func (m *RadioInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RadioInput.Unmarshal(m, b)
}
func (m *RadioInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RadioInput.Marshal(b, m, deterministic)
}
func (m *RadioInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RadioInput.Merge(m, src)
}
func (m *RadioInput) XXX_Size() int {
	return xxx_messageInfo_RadioInput.Size(m)
}
func (m *RadioInput) XXX_DiscardUnknown() {
	xxx_messageInfo_RadioInput.DiscardUnknown(m)
}

var xxx_messageInfo_RadioInput proto.InternalMessageInfo

func (m *RadioInput) GetType() RadioInput_Type {
	if m != nil {
		return m.Type
	}
	return RadioInput_radio
}

type isRadioInput_Builder interface {
	isRadioInput_Builder()
}

type RadioInput_CodeAccessor struct {
	CodeAccessor string `protobuf:"bytes,2,opt,name=codeAccessor,proto3,oneof"`
}

type RadioInput_FromEnum struct {
	FromEnum bool `protobuf:"varint,3,opt,name=fromEnum,proto3,oneof"`
}

func (*RadioInput_CodeAccessor) isRadioInput_Builder() {}

func (*RadioInput_FromEnum) isRadioInput_Builder() {}

func (m *RadioInput) GetBuilder() isRadioInput_Builder {
	if m != nil {
		return m.Builder
	}
	return nil
}

func (m *RadioInput) GetCodeAccessor() string {
	if x, ok := m.GetBuilder().(*RadioInput_CodeAccessor); ok {
		return x.CodeAccessor
	}
	return ""
}

func (m *RadioInput) GetFromEnum() bool {
	if x, ok := m.GetBuilder().(*RadioInput_FromEnum); ok {
		return x.FromEnum
	}
	return false
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*RadioInput) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*RadioInput_CodeAccessor)(nil),
		(*RadioInput_FromEnum)(nil),
	}
}

type SwitchInput struct {
	Checkbox             bool     `protobuf:"varint,1,opt,name=checkbox,proto3" json:"checkbox,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SwitchInput) Reset()         { *m = SwitchInput{} }
func (m *SwitchInput) String() string { return proto.CompactTextString(m) }
func (*SwitchInput) ProtoMessage()    {}
func (*SwitchInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_23d710dfe11887bd, []int{11}
}

func (m *SwitchInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SwitchInput.Unmarshal(m, b)
}
func (m *SwitchInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SwitchInput.Marshal(b, m, deterministic)
}
func (m *SwitchInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SwitchInput.Merge(m, src)
}
func (m *SwitchInput) XXX_Size() int {
	return xxx_messageInfo_SwitchInput.Size(m)
}
func (m *SwitchInput) XXX_DiscardUnknown() {
	xxx_messageInfo_SwitchInput.DiscardUnknown(m)
}

var xxx_messageInfo_SwitchInput proto.InternalMessageInfo

func (m *SwitchInput) GetCheckbox() bool {
	if m != nil {
		return m.Checkbox
	}
	return false
}

type ListInput struct {
	Type ListInput_Type `protobuf:"varint,1,opt,name=type,proto3,enum=pgde.form.ListInput_Type" json:"type,omitempty"`
	// Types that are valid to be assigned to Builder:
	//	*ListInput_CodeAccessor
	//	*ListInput_FromEnum
	Builder              isListInput_Builder `protobuf_oneof:"builder"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *ListInput) Reset()         { *m = ListInput{} }
func (m *ListInput) String() string { return proto.CompactTextString(m) }
func (*ListInput) ProtoMessage()    {}
func (*ListInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_23d710dfe11887bd, []int{12}
}

func (m *ListInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListInput.Unmarshal(m, b)
}
func (m *ListInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListInput.Marshal(b, m, deterministic)
}
func (m *ListInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListInput.Merge(m, src)
}
func (m *ListInput) XXX_Size() int {
	return xxx_messageInfo_ListInput.Size(m)
}
func (m *ListInput) XXX_DiscardUnknown() {
	xxx_messageInfo_ListInput.DiscardUnknown(m)
}

var xxx_messageInfo_ListInput proto.InternalMessageInfo

func (m *ListInput) GetType() ListInput_Type {
	if m != nil {
		return m.Type
	}
	return ListInput_checkbox
}

type isListInput_Builder interface {
	isListInput_Builder()
}

type ListInput_CodeAccessor struct {
	CodeAccessor string `protobuf:"bytes,2,opt,name=codeAccessor,proto3,oneof"`
}

type ListInput_FromEnum struct {
	FromEnum bool `protobuf:"varint,3,opt,name=fromEnum,proto3,oneof"`
}

func (*ListInput_CodeAccessor) isListInput_Builder() {}

func (*ListInput_FromEnum) isListInput_Builder() {}

func (m *ListInput) GetBuilder() isListInput_Builder {
	if m != nil {
		return m.Builder
	}
	return nil
}

func (m *ListInput) GetCodeAccessor() string {
	if x, ok := m.GetBuilder().(*ListInput_CodeAccessor); ok {
		return x.CodeAccessor
	}
	return ""
}

func (m *ListInput) GetFromEnum() bool {
	if x, ok := m.GetBuilder().(*ListInput_FromEnum); ok {
		return x.FromEnum
	}
	return false
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*ListInput) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*ListInput_CodeAccessor)(nil),
		(*ListInput_FromEnum)(nil),
	}
}

// type and format are defined by format.Format
type DatetimePickerInput struct {
	DatePickerMode       DatetimePickerInput_DatePickerMode `protobuf:"varint,1,opt,name=datePickerMode,proto3,enum=pgde.form.DatetimePickerInput_DatePickerMode" json:"datePickerMode,omitempty"`
	Editable             bool                               `protobuf:"varint,2,opt,name=editable,proto3" json:"editable,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                           `json:"-"`
	XXX_unrecognized     []byte                             `json:"-"`
	XXX_sizecache        int32                              `json:"-"`
}

func (m *DatetimePickerInput) Reset()         { *m = DatetimePickerInput{} }
func (m *DatetimePickerInput) String() string { return proto.CompactTextString(m) }
func (*DatetimePickerInput) ProtoMessage()    {}
func (*DatetimePickerInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_23d710dfe11887bd, []int{13}
}

func (m *DatetimePickerInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DatetimePickerInput.Unmarshal(m, b)
}
func (m *DatetimePickerInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DatetimePickerInput.Marshal(b, m, deterministic)
}
func (m *DatetimePickerInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DatetimePickerInput.Merge(m, src)
}
func (m *DatetimePickerInput) XXX_Size() int {
	return xxx_messageInfo_DatetimePickerInput.Size(m)
}
func (m *DatetimePickerInput) XXX_DiscardUnknown() {
	xxx_messageInfo_DatetimePickerInput.DiscardUnknown(m)
}

var xxx_messageInfo_DatetimePickerInput proto.InternalMessageInfo

func (m *DatetimePickerInput) GetDatePickerMode() DatetimePickerInput_DatePickerMode {
	if m != nil {
		return m.DatePickerMode
	}
	return DatetimePickerInput_day
}

func (m *DatetimePickerInput) GetEditable() bool {
	if m != nil {
		return m.Editable
	}
	return false
}

type MapInput struct {
	Key                  *MapKeyValueInput `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value                *MapKeyValueInput `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *MapInput) Reset()         { *m = MapInput{} }
func (m *MapInput) String() string { return proto.CompactTextString(m) }
func (*MapInput) ProtoMessage()    {}
func (*MapInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_23d710dfe11887bd, []int{14}
}

func (m *MapInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MapInput.Unmarshal(m, b)
}
func (m *MapInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MapInput.Marshal(b, m, deterministic)
}
func (m *MapInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MapInput.Merge(m, src)
}
func (m *MapInput) XXX_Size() int {
	return xxx_messageInfo_MapInput.Size(m)
}
func (m *MapInput) XXX_DiscardUnknown() {
	xxx_messageInfo_MapInput.DiscardUnknown(m)
}

var xxx_messageInfo_MapInput proto.InternalMessageInfo

func (m *MapInput) GetKey() *MapKeyValueInput {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *MapInput) GetValue() *MapKeyValueInput {
	if m != nil {
		return m.Value
	}
	return nil
}

type MapKeyValueInput struct {
	// Types that are valid to be assigned to Type:
	//	*MapKeyValueInput_Text
	//	*MapKeyValueInput_TypeAhead
	//	*MapKeyValueInput_Signature
	//	*MapKeyValueInput_Number
	//	*MapKeyValueInput_Stepper
	//	*MapKeyValueInput_Slider
	//	*MapKeyValueInput_Rate
	//	*MapKeyValueInput_Radio
	//	*MapKeyValueInput_BoolSwitch
	//	*MapKeyValueInput_Datetime
	Type                 isMapKeyValueInput_Type `protobuf_oneof:"type"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *MapKeyValueInput) Reset()         { *m = MapKeyValueInput{} }
func (m *MapKeyValueInput) String() string { return proto.CompactTextString(m) }
func (*MapKeyValueInput) ProtoMessage()    {}
func (*MapKeyValueInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_23d710dfe11887bd, []int{15}
}

func (m *MapKeyValueInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MapKeyValueInput.Unmarshal(m, b)
}
func (m *MapKeyValueInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MapKeyValueInput.Marshal(b, m, deterministic)
}
func (m *MapKeyValueInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MapKeyValueInput.Merge(m, src)
}
func (m *MapKeyValueInput) XXX_Size() int {
	return xxx_messageInfo_MapKeyValueInput.Size(m)
}
func (m *MapKeyValueInput) XXX_DiscardUnknown() {
	xxx_messageInfo_MapKeyValueInput.DiscardUnknown(m)
}

var xxx_messageInfo_MapKeyValueInput proto.InternalMessageInfo

type isMapKeyValueInput_Type interface {
	isMapKeyValueInput_Type()
}

type MapKeyValueInput_Text struct {
	Text *TextInput `protobuf:"bytes,11,opt,name=text,proto3,oneof"`
}

type MapKeyValueInput_TypeAhead struct {
	TypeAhead *TypeAheadInput `protobuf:"bytes,12,opt,name=typeAhead,proto3,oneof"`
}

type MapKeyValueInput_Signature struct {
	Signature *SignatureInput `protobuf:"bytes,13,opt,name=signature,proto3,oneof"`
}

type MapKeyValueInput_Number struct {
	Number *NumberInput `protobuf:"bytes,14,opt,name=number,proto3,oneof"`
}

type MapKeyValueInput_Stepper struct {
	Stepper *StepperInput `protobuf:"bytes,15,opt,name=stepper,proto3,oneof"`
}

type MapKeyValueInput_Slider struct {
	Slider *SliderInput `protobuf:"bytes,16,opt,name=slider,proto3,oneof"`
}

type MapKeyValueInput_Rate struct {
	Rate *RateInput `protobuf:"bytes,17,opt,name=rate,proto3,oneof"`
}

type MapKeyValueInput_Radio struct {
	Radio *RadioInput `protobuf:"bytes,18,opt,name=radio,proto3,oneof"`
}

type MapKeyValueInput_BoolSwitch struct {
	BoolSwitch *SwitchInput `protobuf:"bytes,19,opt,name=boolSwitch,proto3,oneof"`
}

type MapKeyValueInput_Datetime struct {
	Datetime *DatetimePickerInput `protobuf:"bytes,21,opt,name=datetime,proto3,oneof"`
}

func (*MapKeyValueInput_Text) isMapKeyValueInput_Type() {}

func (*MapKeyValueInput_TypeAhead) isMapKeyValueInput_Type() {}

func (*MapKeyValueInput_Signature) isMapKeyValueInput_Type() {}

func (*MapKeyValueInput_Number) isMapKeyValueInput_Type() {}

func (*MapKeyValueInput_Stepper) isMapKeyValueInput_Type() {}

func (*MapKeyValueInput_Slider) isMapKeyValueInput_Type() {}

func (*MapKeyValueInput_Rate) isMapKeyValueInput_Type() {}

func (*MapKeyValueInput_Radio) isMapKeyValueInput_Type() {}

func (*MapKeyValueInput_BoolSwitch) isMapKeyValueInput_Type() {}

func (*MapKeyValueInput_Datetime) isMapKeyValueInput_Type() {}

func (m *MapKeyValueInput) GetType() isMapKeyValueInput_Type {
	if m != nil {
		return m.Type
	}
	return nil
}

func (m *MapKeyValueInput) GetText() *TextInput {
	if x, ok := m.GetType().(*MapKeyValueInput_Text); ok {
		return x.Text
	}
	return nil
}

func (m *MapKeyValueInput) GetTypeAhead() *TypeAheadInput {
	if x, ok := m.GetType().(*MapKeyValueInput_TypeAhead); ok {
		return x.TypeAhead
	}
	return nil
}

func (m *MapKeyValueInput) GetSignature() *SignatureInput {
	if x, ok := m.GetType().(*MapKeyValueInput_Signature); ok {
		return x.Signature
	}
	return nil
}

func (m *MapKeyValueInput) GetNumber() *NumberInput {
	if x, ok := m.GetType().(*MapKeyValueInput_Number); ok {
		return x.Number
	}
	return nil
}

func (m *MapKeyValueInput) GetStepper() *StepperInput {
	if x, ok := m.GetType().(*MapKeyValueInput_Stepper); ok {
		return x.Stepper
	}
	return nil
}

func (m *MapKeyValueInput) GetSlider() *SliderInput {
	if x, ok := m.GetType().(*MapKeyValueInput_Slider); ok {
		return x.Slider
	}
	return nil
}

func (m *MapKeyValueInput) GetRate() *RateInput {
	if x, ok := m.GetType().(*MapKeyValueInput_Rate); ok {
		return x.Rate
	}
	return nil
}

func (m *MapKeyValueInput) GetRadio() *RadioInput {
	if x, ok := m.GetType().(*MapKeyValueInput_Radio); ok {
		return x.Radio
	}
	return nil
}

func (m *MapKeyValueInput) GetBoolSwitch() *SwitchInput {
	if x, ok := m.GetType().(*MapKeyValueInput_BoolSwitch); ok {
		return x.BoolSwitch
	}
	return nil
}

func (m *MapKeyValueInput) GetDatetime() *DatetimePickerInput {
	if x, ok := m.GetType().(*MapKeyValueInput_Datetime); ok {
		return x.Datetime
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*MapKeyValueInput) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*MapKeyValueInput_Text)(nil),
		(*MapKeyValueInput_TypeAhead)(nil),
		(*MapKeyValueInput_Signature)(nil),
		(*MapKeyValueInput_Number)(nil),
		(*MapKeyValueInput_Stepper)(nil),
		(*MapKeyValueInput_Slider)(nil),
		(*MapKeyValueInput_Rate)(nil),
		(*MapKeyValueInput_Radio)(nil),
		(*MapKeyValueInput_BoolSwitch)(nil),
		(*MapKeyValueInput_Datetime)(nil),
	}
}

type InputDecoration struct {
	Icon       MaterialIcon `protobuf:"varint,1,opt,name=icon,proto3,enum=pgde.form.MaterialIcon" json:"icon,omitempty"`
	PrefixIcon MaterialIcon `protobuf:"varint,2,opt,name=prefixIcon,proto3,enum=pgde.form.MaterialIcon" json:"prefixIcon,omitempty"`
	SuffixIcon MaterialIcon `protobuf:"varint,3,opt,name=suffixIcon,proto3,enum=pgde.form.MaterialIcon" json:"suffixIcon,omitempty"`
	/// Optional text to place below the line as a character count.
	///
	/// Rendered using [counterStyle]. Uses [helperStyle] if [counterStyle] is
	/// null.
	///
	/// The semantic label can be replaced by providing a [semanticCounterText].
	///
	/// If null or an empty string and [counter] isn't specified, then nothing
	/// will appear in the counter's location.
	Counter              []InputDecoration_CounterType `protobuf:"varint,4,rep,packed,name=counter,proto3,enum=pgde.form.InputDecoration_CounterType" json:"counter,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                      `json:"-"`
	XXX_unrecognized     []byte                        `json:"-"`
	XXX_sizecache        int32                         `json:"-"`
}

func (m *InputDecoration) Reset()         { *m = InputDecoration{} }
func (m *InputDecoration) String() string { return proto.CompactTextString(m) }
func (*InputDecoration) ProtoMessage()    {}
func (*InputDecoration) Descriptor() ([]byte, []int) {
	return fileDescriptor_23d710dfe11887bd, []int{16}
}

func (m *InputDecoration) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InputDecoration.Unmarshal(m, b)
}
func (m *InputDecoration) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InputDecoration.Marshal(b, m, deterministic)
}
func (m *InputDecoration) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InputDecoration.Merge(m, src)
}
func (m *InputDecoration) XXX_Size() int {
	return xxx_messageInfo_InputDecoration.Size(m)
}
func (m *InputDecoration) XXX_DiscardUnknown() {
	xxx_messageInfo_InputDecoration.DiscardUnknown(m)
}

var xxx_messageInfo_InputDecoration proto.InternalMessageInfo

func (m *InputDecoration) GetIcon() MaterialIcon {
	if m != nil {
		return m.Icon
	}
	return MaterialIcon_noMaterialIcon
}

func (m *InputDecoration) GetPrefixIcon() MaterialIcon {
	if m != nil {
		return m.PrefixIcon
	}
	return MaterialIcon_noMaterialIcon
}

func (m *InputDecoration) GetSuffixIcon() MaterialIcon {
	if m != nil {
		return m.SuffixIcon
	}
	return MaterialIcon_noMaterialIcon
}

func (m *InputDecoration) GetCounter() []InputDecoration_CounterType {
	if m != nil {
		return m.Counter
	}
	return nil
}

var E_DefaultField = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.EnumOptions)(nil),
	ExtensionType: (*Field)(nil),
	Field:         919114,
	Name:          "pgde.form.defaultField",
	Tag:           "bytes,919114,opt,name=defaultField",
	Filename:      "pgde/form/form.proto",
}

var E_InputOption = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.EnumValueOptions)(nil),
	ExtensionType: (*InputOption)(nil),
	Field:         919114,
	Name:          "pgde.form.inputOption",
	Tag:           "bytes,919114,opt,name=inputOption",
	Filename:      "pgde/form/form.proto",
}

var E_Embed = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.OneofOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         919114,
	Name:          "pgde.form.embed",
	Tag:           "varint,919114,opt,name=embed",
	Filename:      "pgde/form/form.proto",
}

var E_Node = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.MessageOptions)(nil),
	ExtensionType: (*Node)(nil),
	Field:         919114,
	Name:          "pgde.form.node",
	Tag:           "bytes,919114,opt,name=node",
	Filename:      "pgde/form/form.proto",
}

var E_Field = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FieldOptions)(nil),
	ExtensionType: (*Field)(nil),
	Field:         919114,
	Name:          "pgde.form.field",
	Tag:           "bytes,919114,opt,name=field",
	Filename:      "pgde/form/form.proto",
}

func init() {
	proto.RegisterEnum("pgde.form.Protector", Protector_name, Protector_value)
	proto.RegisterEnum("pgde.form.UnitPlace", UnitPlace_name, UnitPlace_value)
	proto.RegisterEnum("pgde.form.TextInput_Type", TextInput_Type_name, TextInput_Type_value)
	proto.RegisterEnum("pgde.form.RadioInput_Type", RadioInput_Type_name, RadioInput_Type_value)
	proto.RegisterEnum("pgde.form.ListInput_Type", ListInput_Type_name, ListInput_Type_value)
	proto.RegisterEnum("pgde.form.DatetimePickerInput_DatePickerMode", DatetimePickerInput_DatePickerMode_name, DatetimePickerInput_DatePickerMode_value)
	proto.RegisterEnum("pgde.form.InputDecoration_CounterType", InputDecoration_CounterType_name, InputDecoration_CounterType_value)
	proto.RegisterType((*InputOption)(nil), "pgde.form.InputOption")
	proto.RegisterType((*Node)(nil), "pgde.form.Node")
	proto.RegisterType((*Field)(nil), "pgde.form.Field")
	proto.RegisterType((*TextInput)(nil), "pgde.form.TextInput")
	proto.RegisterType((*TypeAheadInput)(nil), "pgde.form.TypeAheadInput")
	proto.RegisterType((*SignatureInput)(nil), "pgde.form.SignatureInput")
	proto.RegisterType((*NumberInput)(nil), "pgde.form.NumberInput")
	proto.RegisterType((*StepperInput)(nil), "pgde.form.StepperInput")
	proto.RegisterType((*SliderInput)(nil), "pgde.form.SliderInput")
	proto.RegisterType((*RateInput)(nil), "pgde.form.RateInput")
	proto.RegisterType((*RadioInput)(nil), "pgde.form.RadioInput")
	proto.RegisterType((*SwitchInput)(nil), "pgde.form.SwitchInput")
	proto.RegisterType((*ListInput)(nil), "pgde.form.ListInput")
	proto.RegisterType((*DatetimePickerInput)(nil), "pgde.form.DatetimePickerInput")
	proto.RegisterType((*MapInput)(nil), "pgde.form.MapInput")
	proto.RegisterType((*MapKeyValueInput)(nil), "pgde.form.MapKeyValueInput")
	proto.RegisterType((*InputDecoration)(nil), "pgde.form.InputDecoration")
	proto.RegisterExtension(E_DefaultField)
	proto.RegisterExtension(E_InputOption)
	proto.RegisterExtension(E_Embed)
	proto.RegisterExtension(E_Node)
	proto.RegisterExtension(E_Field)
}

func init() { proto.RegisterFile("pgde/form/form.proto", fileDescriptor_23d710dfe11887bd) }

var fileDescriptor_23d710dfe11887bd = []byte{
	// 1553 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x58, 0x6d, 0x6f, 0x1b, 0xc5,
	0x16, 0xde, 0xf5, 0x4b, 0x62, 0x1f, 0x3b, 0xce, 0x76, 0x9a, 0xe6, 0x6e, 0x73, 0x7b, 0x6f, 0x7b,
	0xf7, 0x56, 0xbd, 0xbd, 0x85, 0x38, 0x90, 0x52, 0x08, 0x11, 0x48, 0x4d, 0xfa, 0x42, 0x2b, 0xfa,
	0xa6, 0x4d, 0x0b, 0x12, 0x12, 0x42, 0xeb, 0xdd, 0x63, 0x7b, 0x94, 0xf5, 0xce, 0x6a, 0x76, 0xb6,
	0x89, 0x11, 0x12, 0x9f, 0xf8, 0xc6, 0x2f, 0xe0, 0x17, 0x20, 0x24, 0xfe, 0x03, 0xe2, 0x13, 0xf0,
	0x17, 0xf8, 0xc2, 0x07, 0x7e, 0x08, 0x9a, 0x99, 0xdd, 0xf5, 0xda, 0x0e, 0xe4, 0x45, 0xf4, 0x8b,
	0x93, 0x39, 0xe7, 0x79, 0xce, 0xcc, 0x19, 0xcf, 0x79, 0xe6, 0x8c, 0x61, 0x25, 0x1e, 0x04, 0xb8,
	0xd1, 0x67, 0x7c, 0xa4, 0x3e, 0xba, 0x31, 0x67, 0x82, 0x91, 0xa6, 0xb4, 0x76, 0xa5, 0x61, 0xed,
	0xca, 0x80, 0xb1, 0x41, 0x88, 0x1b, 0xca, 0xd1, 0x4b, 0xfb, 0x1b, 0x01, 0x26, 0x3e, 0xa7, 0xb1,
	0x60, 0x5c, 0x83, 0xd7, 0x2e, 0x4c, 0x42, 0xf8, 0x2c, 0x2c, 0xcc, 0xa5, 0xc8, 0xd4, 0x67, 0x51,
	0x66, 0x5d, 0x55, 0xd6, 0x34, 0xa2, 0x22, 0xd1, 0x9f, 0x53, 0xe8, 0xcf, 0x91, 0x33, 0xf5, 0xa1,
	0xad, 0xce, 0x36, 0xb4, 0x1e, 0x46, 0x71, 0x2a, 0x9e, 0xc6, 0x82, 0xb2, 0x88, 0xbc, 0x06, 0x35,
	0x19, 0xca, 0x36, 0xaf, 0x98, 0xd7, 0x3b, 0x9b, 0xff, 0xe8, 0x16, 0xab, 0xec, 0x3e, 0xf6, 0x04,
	0x72, 0xea, 0x85, 0x0f, 0x7d, 0x16, 0xb9, 0x0a, 0xe4, 0x7c, 0x09, 0xb5, 0x27, 0x2c, 0x40, 0xb2,
	0x0a, 0x0b, 0x74, 0x10, 0x31, 0x8e, 0x8a, 0xd6, 0x70, 0xb3, 0x51, 0x11, 0xac, 0x72, 0x82, 0x60,
	0x64, 0x13, 0x9a, 0x72, 0x45, 0xe8, 0x0b, 0xc6, 0xed, 0xaa, 0x62, 0xac, 0x94, 0x18, 0xcf, 0x72,
	0x9f, 0x3b, 0x81, 0x39, 0xbf, 0x2e, 0x40, 0xfd, 0x3e, 0xc5, 0x30, 0x20, 0xdb, 0x00, 0x01, 0xfa,
	0x8c, 0x7b, 0x32, 0x0b, 0xb5, 0x8c, 0xd6, 0xe6, 0x5a, 0x89, 0xae, 0x72, 0xbc, 0x5b, 0x20, 0xdc,
	0x12, 0x7a, 0x7a, 0xe6, 0xca, 0x89, 0x66, 0x26, 0x2b, 0x50, 0x1b, 0xd2, 0x00, 0xd5, 0x42, 0x1b,
	0x0f, 0x0c, 0x57, 0x8d, 0xc8, 0x25, 0x68, 0x04, 0x34, 0xf1, 0x7a, 0x21, 0x06, 0x76, 0x2d, 0xf3,
	0x14, 0x16, 0xe2, 0x40, 0x0b, 0xa3, 0x24, 0xe5, 0xb8, 0x33, 0xf0, 0x68, 0x64, 0xd7, 0x33, 0x40,
	0xd9, 0x48, 0x56, 0xa1, 0x8e, 0xa3, 0x1e, 0x06, 0xf6, 0x42, 0xe6, 0xd5, 0x43, 0x72, 0x03, 0x6a,
	0x02, 0x0f, 0x85, 0xdd, 0x52, 0x99, 0x95, 0x97, 0xf7, 0x1c, 0x0f, 0x85, 0xca, 0xee, 0x81, 0xe9,
	0x2a, 0x0c, 0x79, 0x17, 0x9a, 0x62, 0x1c, 0xe3, 0xce, 0x10, 0xbd, 0xc0, 0x6e, 0x2b, 0xc2, 0xc5,
	0x32, 0x21, 0xf7, 0xe5, 0xac, 0x09, 0x5a, 0x52, 0x13, 0x3a, 0x88, 0x3c, 0x91, 0x72, 0xb4, 0x97,
	0xe6, 0xa8, 0x7b, 0xb9, 0xaf, 0xa0, 0x16, 0x68, 0xf2, 0x06, 0x2c, 0x44, 0xe9, 0xa8, 0x87, 0xdc,
	0xee, 0x28, 0xde, 0x6a, 0x89, 0xf7, 0x44, 0x39, 0x72, 0x52, 0x86, 0x23, 0x37, 0x61, 0x31, 0x11,
	0x18, 0xc7, 0xc8, 0xed, 0x65, 0x45, 0x29, 0x9f, 0x90, 0x3d, 0xed, 0xc9, 0x39, 0x39, 0x52, 0x4e,
	0x93, 0x84, 0x34, 0x40, 0x6e, 0x5b, 0x73, 0xd3, 0xec, 0x29, 0x47, 0x31, 0x8d, 0xc6, 0xc9, 0xad,
	0xe3, 0x9e, 0x40, 0xfb, 0xdc, 0xdc, 0xd6, 0xb9, 0x9e, 0x28, 0x32, 0x51, 0x18, 0xb2, 0x0e, 0x75,
	0xee, 0x05, 0x94, 0xd9, 0x44, 0x81, 0x2f, 0x4c, 0x81, 0x03, 0xca, 0x72, 0xb4, 0x46, 0x91, 0x2d,
	0x80, 0x1e, 0x63, 0xe1, 0xde, 0x01, 0x15, 0xfe, 0xd0, 0x3e, 0x3f, 0xbf, 0x20, 0xe5, 0xc8, 0x49,
	0x25, 0xac, 0x5c, 0x54, 0x48, 0x13, 0x61, 0xaf, 0xcc, 0x2d, 0xea, 0x11, 0x4d, 0x26, 0xdf, 0xa7,
	0xc4, 0x90, 0xf7, 0xa0, 0x11, 0x78, 0x02, 0x05, 0x1d, 0xa1, 0x7d, 0x41, 0xe1, 0xff, 0x5d, 0xc2,
	0xdf, 0xcd, 0x5c, 0xcf, 0xa8, 0xbf, 0x3f, 0x49, 0xbe, 0x60, 0x90, 0xff, 0x41, 0x75, 0xe4, 0xc5,
	0xf6, 0xaa, 0x22, 0x9e, 0x9f, 0xaa, 0xc1, 0x38, 0x47, 0x4b, 0xc4, 0xee, 0x22, 0xd4, 0x7b, 0x29,
	0x0d, 0x83, 0xdd, 0x05, 0xa8, 0xc9, 0x13, 0xe1, 0xfc, 0x5c, 0x81, 0x66, 0x71, 0xba, 0xc8, 0xfb,
	0xd0, 0xde, 0xc7, 0x71, 0x8f, 0x79, 0x3c, 0x90, 0x27, 0x28, 0x53, 0x88, 0x8b, 0x47, 0x9d, 0x44,
	0x75, 0xc4, 0xdc, 0x29, 0x38, 0xb9, 0x02, 0x2d, 0xd6, 0x4b, 0xfc, 0x94, 0xa3, 0x84, 0xa9, 0x32,
	0x6b, 0xb8, 0x65, 0x93, 0x44, 0x78, 0xa9, 0x60, 0x3e, 0xe3, 0x1c, 0x7d, 0xa1, 0x2b, 0xcb, 0x2d,
	0x9b, 0xc8, 0x1a, 0x34, 0x46, 0xde, 0xe1, 0x23, 0x1a, 0x61, 0xa2, 0xca, 0xab, 0xee, 0x16, 0x63,
	0xf2, 0x3a, 0x9c, 0x93, 0xff, 0x63, 0x34, 0x10, 0xc3, 0x7b, 0x51, 0x9f, 0x71, 0x1f, 0x03, 0x5d,
	0x62, 0xee, 0xbc, 0xc3, 0x61, 0x50, 0x53, 0xab, 0xea, 0x00, 0xc8, 0x09, 0x76, 0xc7, 0x72, 0x64,
	0x19, 0xa4, 0x3d, 0xd9, 0x6a, 0xab, 0x42, 0x2c, 0x68, 0xe3, 0xc8, 0xa3, 0xe1, 0x4e, 0x10, 0x70,
	0x4c, 0x12, 0xab, 0x4a, 0x96, 0xa0, 0x39, 0x4a, 0x43, 0x41, 0x43, 0x1a, 0xa1, 0x55, 0x23, 0x90,
	0x9f, 0x79, 0xab, 0x4e, 0x9a, 0x50, 0x8f, 0x87, 0x2c, 0x42, 0x6b, 0x81, 0x34, 0x74, 0xb1, 0x5a,
	0x8b, 0x64, 0x11, 0xaa, 0x29, 0x0f, 0xad, 0x86, 0xf3, 0x19, 0x74, 0xa6, 0xeb, 0x8e, 0x5c, 0x85,
	0xb6, 0xcf, 0x02, 0xdc, 0xf1, 0x7d, 0x4c, 0x12, 0xc6, 0xd5, 0x7e, 0x36, 0x1f, 0x18, 0xee, 0x94,
	0x55, 0x2a, 0x4a, 0x9f, 0xb3, 0xd1, 0xbd, 0x28, 0x1d, 0xe9, 0x3d, 0x93, 0x8a, 0x92, 0x5b, 0x76,
	0x9b, 0xb0, 0xa8, 0xbe, 0x32, 0xe4, 0xce, 0x6f, 0x26, 0x74, 0xa6, 0xcb, 0x93, 0xac, 0x40, 0xfd,
	0x80, 0x06, 0x62, 0xa8, 0x42, 0x9b, 0xae, 0x1e, 0x48, 0xb1, 0x1e, 0x22, 0x1d, 0x0c, 0xf5, 0x77,
	0x60, 0xba, 0xd9, 0x88, 0xec, 0xc2, 0x72, 0xcf, 0xf3, 0xf7, 0x07, 0x9c, 0xa5, 0x51, 0x70, 0x47,
	0xde, 0x32, 0xea, 0x2b, 0x68, 0x6d, 0xda, 0x47, 0xe8, 0xb6, 0xf2, 0xbb, 0xb3, 0x04, 0xf2, 0x16,
	0x34, 0x62, 0x8c, 0x34, 0xb9, 0x76, 0x0c, 0xb9, 0x40, 0x92, 0x6b, 0xd0, 0x89, 0x31, 0xda, 0x13,
	0x9c, 0xed, 0xe3, 0xc7, 0x6a, 0xc1, 0x75, 0xb5, 0xb2, 0x19, 0xab, 0x33, 0x80, 0x56, 0x49, 0x48,
	0xc8, 0x55, 0xa8, 0xc9, 0xeb, 0x2d, 0x13, 0x7b, 0x4b, 0x4f, 0xa4, 0x2f, 0xbc, 0xbd, 0x21, 0x3b,
	0x70, 0x95, 0x57, 0x8a, 0xbb, 0xfc, 0xfb, 0x2c, 0xf4, 0x7c, 0x3c, 0x42, 0xdc, 0x5f, 0xe4, 0x3e,
	0x77, 0x02, 0x73, 0xbe, 0x80, 0x76, 0x59, 0x7e, 0x5e, 0xdd, 0x4c, 0x84, 0x40, 0x4d, 0x0a, 0x9b,
	0xda, 0xe9, 0x25, 0x57, 0xfd, 0xef, 0x7c, 0x65, 0x42, 0xab, 0xa4, 0x64, 0xaf, 0x70, 0xf6, 0x4b,
	0xd0, 0x0c, 0xe8, 0x4b, 0x9a, 0x50, 0x16, 0x25, 0xd9, 0x12, 0x26, 0x06, 0x67, 0x0b, 0x9a, 0x85,
	0x40, 0x9e, 0xae, 0x2f, 0xf8, 0xd1, 0x04, 0x98, 0xc8, 0x25, 0xe9, 0x6a, 0x3d, 0xc9, 0xb8, 0x6b,
	0x47, 0x6a, 0xaa, 0x96, 0x0c, 0x85, 0x9b, 0xab, 0x8c, 0xca, 0xb1, 0x95, 0x51, 0x9d, 0xad, 0x0c,
	0xe7, 0x56, 0x56, 0xe0, 0xcd, 0x4c, 0xd0, 0xb3, 0xda, 0xe6, 0x2c, 0x0e, 0xd8, 0x41, 0x64, 0x99,
	0x64, 0x05, 0xac, 0x04, 0x07, 0x23, 0x8c, 0x04, 0x06, 0x77, 0x58, 0x24, 0x38, 0x0b, 0xad, 0x4a,
	0xb9, 0xa0, 0xfe, 0x0f, 0xad, 0x92, 0x7c, 0x4b, 0xed, 0xf1, 0x87, 0xe8, 0xef, 0xf7, 0xd8, 0x61,
	0xd6, 0xe5, 0x14, 0x63, 0xe7, 0x3b, 0x13, 0x9a, 0x85, 0x6c, 0x93, 0xf5, 0xa9, 0x74, 0x2f, 0x1e,
	0x25, 0xed, 0x7f, 0x77, 0xb6, 0x97, 0xb3, 0x6c, 0xdb, 0x93, 0x45, 0x5a, 0x86, 0xcc, 0xdd, 0x1f,
	0xd2, 0x38, 0xb1, 0xcc, 0x72, 0x5e, 0xdf, 0x9b, 0x70, 0xfe, 0x88, 0x3b, 0x83, 0xbc, 0x80, 0x8e,
	0x94, 0x3e, 0x6d, 0x7a, 0xcc, 0x82, 0x3c, 0x81, 0xf5, 0xbf, 0xbe, 0x6b, 0x94, 0x6d, 0x42, 0x72,
	0x67, 0x82, 0xc8, 0x7d, 0xc3, 0x80, 0x0a, 0xd9, 0x01, 0x65, 0xa2, 0x5f, 0x8c, 0x9d, 0xff, 0x42,
	0x67, 0x9a, 0x2d, 0xf5, 0x32, 0xf0, 0xc6, 0x96, 0x21, 0x25, 0x74, 0x8c, 0x1e, 0xb7, 0x4c, 0x27,
	0x84, 0x46, 0x7e, 0x53, 0x91, 0x75, 0xa8, 0xee, 0xe3, 0x38, 0xab, 0x84, 0x7f, 0x4e, 0xdf, 0x65,
	0x1f, 0xe2, 0xf8, 0x23, 0x2f, 0x4c, 0xf5, 0x79, 0x75, 0x25, 0x8e, 0xbc, 0x09, 0xf5, 0x97, 0xd2,
	0xa4, 0x26, 0x3e, 0x86, 0xa0, 0x91, 0xce, 0xb7, 0x35, 0xb0, 0x66, 0x7d, 0x27, 0x6a, 0xbe, 0x8c,
	0x33, 0x35, 0x5f, 0xc6, 0xd9, 0x9b, 0x2f, 0xe3, 0x2c, 0xcd, 0x97, 0x71, 0x86, 0xe6, 0xcb, 0x38,
	0x7d, 0xf3, 0x65, 0x9c, 0xaa, 0xf9, 0x32, 0x4e, 0xd5, 0x7c, 0x19, 0x67, 0x69, 0xbe, 0x8c, 0xa9,
	0xe6, 0xeb, 0xf4, 0x0d, 0x95, 0x31, 0x69, 0xa8, 0x8a, 0xf6, 0xe8, 0x9b, 0x0a, 0x2c, 0xcf, 0x3c,
	0x2b, 0x4e, 0x25, 0x93, 0xe4, 0x1d, 0x80, 0x98, 0x63, 0x9f, 0x1e, 0x3e, 0x3c, 0xc1, 0x23, 0xa9,
	0x04, 0x95, 0xc4, 0x24, 0xed, 0xe7, 0xc4, 0xea, 0x31, 0xc4, 0x09, 0x94, 0xdc, 0x86, 0x45, 0x9f,
	0xa5, 0x91, 0x40, 0x79, 0x3d, 0x57, 0xaf, 0x77, 0x36, 0xaf, 0xfd, 0xf9, 0x13, 0xa9, 0x7b, 0x47,
	0x23, 0x95, 0x54, 0xe5, 0x34, 0xe7, 0x1a, 0xb4, 0x4a, 0x76, 0x59, 0xa6, 0xbd, 0xb1, 0x90, 0x9d,
	0xd3, 0x12, 0x34, 0xfd, 0xa1, 0xc7, 0x3d, 0x5f, 0x20, 0xb7, 0xcc, 0x1b, 0xb7, 0xa1, 0x59, 0xbc,
	0x9b, 0xc8, 0x32, 0xb4, 0x22, 0x56, 0x0c, 0x2d, 0x43, 0x96, 0x79, 0x4c, 0xa5, 0x0a, 0xb7, 0x60,
	0x31, 0xf6, 0x84, 0x40, 0x1e, 0x59, 0x15, 0xa9, 0x5e, 0xb1, 0x97, 0x24, 0x07, 0x8c, 0x07, 0x56,
	0x55, 0x46, 0x28, 0x2e, 0x2d, 0x1d, 0xa1, 0x18, 0x5a, 0x86, 0xec, 0xbc, 0x74, 0x5e, 0x96, 0x29,
	0x9d, 0xa1, 0xd7, 0xc3, 0x70, 0x4f, 0x1b, 0x2a, 0x6b, 0xf5, 0x9f, 0x7e, 0xff, 0xa1, 0x6a, 0x6e,
	0x3f, 0x87, 0x76, 0x80, 0x7d, 0x2f, 0x0d, 0x85, 0x7e, 0x23, 0x5e, 0xea, 0xea, 0x87, 0x76, 0x37,
	0x7f, 0x68, 0x77, 0xa5, 0x78, 0xea, 0x87, 0x6f, 0x62, 0xff, 0xf2, 0xf5, 0x56, 0xf9, 0x82, 0x55,
	0x5b, 0xa2, 0x78, 0xee, 0x54, 0x94, 0xed, 0x4f, 0xa1, 0x45, 0x4b, 0x0f, 0xe6, 0xff, 0x1c, 0x19,
	0x54, 0x89, 0xc7, 0x6c, 0xe4, 0xd5, 0xd9, 0xcd, 0xd6, 0x00, 0xb7, 0x1c, 0x6f, 0xfb, 0x56, 0xf6,
	0x00, 0x24, 0xff, 0x9a, 0x0b, 0xfc, 0x34, 0x42, 0xd6, 0x9f, 0x0e, 0xda, 0xc8, 0xde, 0x87, 0xdb,
	0xf7, 0xa1, 0x16, 0x49, 0x01, 0xbd, 0x3c, 0xc7, 0x7a, 0x8c, 0x49, 0xe2, 0x0d, 0xe6, 0x16, 0xb3,
	0x5c, 0x56, 0x08, 0x29, 0xdc, 0x8a, 0xbf, 0xfd, 0x01, 0xd4, 0xfb, 0x6a, 0xb3, 0xe6, 0xa7, 0x57,
	0xe9, 0x1f, 0xbf, 0x5b, 0x9a, 0xbf, 0xbb, 0xf5, 0xc9, 0xdb, 0x03, 0x2a, 0x86, 0x69, 0xaf, 0xeb,
	0xb3, 0xd1, 0x06, 0x8e, 0x62, 0xca, 0xb1, 0xcf, 0x0e, 0xf5, 0x8f, 0x1c, 0xfe, 0xfa, 0x00, 0xa3,
	0xf5, 0xc0, 0xe3, 0x62, 0x1d, 0x0f, 0xc5, 0x46, 0xbc, 0x3f, 0xd8, 0x28, 0x7e, 0xca, 0xe8, 0x2d,
	0x28, 0xc8, 0xcd, 0x3f, 0x02, 0x00, 0x00, 0xff, 0xff, 0x76, 0xa6, 0xd9, 0x03, 0x38, 0x11, 0x00,
	0x00,
}
