enum Rule {
  // float_const,
  float_lt,
  float_lte,
  float_gt,
  float_gte,
  // float_in,
  // float_not_in,

  // double_const,
  double_lt,
  double_lte,
  double_gt,
  double_gte,
  // double_in,
  // double_not_in,

  // int32_const,
  int32_lt,
  int32_lte,
  int32_gt,
  int32_gte,
  // int32_in,
  // int32_not_in,

  // int64_const,
  int64_lt,
  int64_lte,
  int64_gt,
  int64_gte,
  // int64_in,
  // int64_not_in,

  // uint32_const,
  uint32_lt,
  uint32_lte,
  uint32_gt,
  uint32_gte,
  // uint32_in,
  // uint32_not_in,

  // uint64_const,
  uint64_lt,
  uint64_lte,
  uint64_gt,
  uint64_gte,
  // uint64_in,
  // uint64_not_in,

  // sint32_const,
  sint32_lt,
  sint32_lte,
  sint32_gt,
  sint32_gte,
  // sint32_in,
  // sint32_not_in,

  // sint64_const,
  sint64_lt,
  sint64_lte,
  sint64_gt,
  sint64_gte,
  // sint64_in,
  // sint64_not_in,

  // fixed32_const,
  fixed32_lt,
  fixed32_lte,
  fixed32_gt,
  fixed32_gte,
  // fixed32_in,
  // fixed32_not_in,

  // fixed64_const,
  fixed64_lt,
  fixed64_lte,
  fixed64_gt,
  fixed64_gte,
  // fixed64_in,
  // fixed64_not_in,

  // sfixed32_const,
  sfixed32_lt,
  sfixed32_lte,
  sfixed32_gt,
  sfixed32_gte,
  // sfixed32_in,
  // sfixed32_not_in,

  // sfixed64_const,
  sfixed64_lt,
  sfixed64_lte,
  sfixed64_gt,
  sfixed64_gte,
  // sfixed64_in,
  // sfixed64_not_in,

  // bool_const,

  // string_const,
  string_len,
  string_min_len,
  string_max_len,
  string_len_bytes,
  string_min_bytes,
  string_max_bytes,
  string_pattern,
  string_prefix,
  string_suffix,
  string_contains,
  // string_in,
  // string_not_in,

  string_email,
  string_hostname,
  string_ip,
  string_ipv4,
  string_ipv6,
  string_uri,
  string_uri_ref,

  // accepts kConst and kConstPrint
  // bytes_const,
  bytes_len,
  bytes_min_len,
  bytes_max_len,
  bytes_pattern,
  bytes_prefix,
  bytes_suffix,
  bytes_contains,
  // bytes_in,
  // bytes_not_in,

  bytes_ip,
  bytes_ipv4,
  bytes_ipv6,

  // enum_const,
  enum_defined_only,
  // enum_in,
  // enum_not_in,

  // message_skip,
  // message_required,

  repeated_min_items,
  repeated_max_items,
  repeated_unique,
  repeated_items,

  map_min_pairs,
  map_max_pairs,
  map_no_sparse,
  map_keys,
  map_values,

  // any_required,
  // any_in,
  // any_not_in,

  // convert protobuf.Duration to core.Duration
  // duration_required,
  // duration_const, // DurationConstError
  duration_lt,
  duration_lte,
  duration_gt,
  duration_gte,
  // duration_in, // toString()
  // duration_not_in,

  // convert protobuf.Timestamp to core.Datetime
  // timestamp_required,
  // timestamp_const, // TimestampConstError
  timestamp_lt,
  timestamp_lte,
  timestamp_gt,
  timestamp_gte,
  timestamp_lt_now,
  timestamp_gt_now,
  timestamp_within,

  required,
  eq_const,
  in_or_not,
  range,
}
