// DO NOT EDIT. Generated by protoc-gen-dart-ext/tools.

/// last_modified: 2019-03-18 12:27:29.31636 +0000 UTC

abstract class AppLocalization {
  const AppLocalization();

  String get notificationChannelName;

  String get notificationChannelDesc;

  String get serviceTitle;

  String get nodeRunning;

  String get nodeStopped;

  String get nodeError;

  String get appName;

  String get appDesc;

  String get home;

  String get addNewOne;

  String get reorder;

  String get dataview;

  String get configureBackAlertTitle;

  String get configureBackAlertContent;

  String get configureBackAlertStay;

  String get configureBackAlertGoBack;

  String get configureBasicBindHint;

  String get configureBasicBindBadTcpAddr;

  String get configureBasicFlushIntervalHint;

  String get configureLogTargetHint;

  String get ConfigTree;

  String get version_ConfigTree;

  String get rootName_ConfigTree;

  String get rootPath_ConfigTree;

  String get configName_ConfigTree;

  String get configPath_ConfigTree;

  String get ipfsName_ConfigTree;

  String get ipfsPath_ConfigTree;

  String get storeName_ConfigTree;

  String get storePath_ConfigTree;

  String get filesRootName_ConfigTree;

  String get filesRootPath_ConfigTree;

  String get rulesRootName_ConfigTree;

  String get rulesRootPath_ConfigTree;

  String get Basic;

  String get version_Basic;

  String get dev_Basic;

  String get bind_Basic;

  String get flushIntervalMs_Basic;

  String get token_Basic;

  String get Log;

  String get dev_Log;

  String get level_Log;

  String get target_Log;

  String get Ipfs;

  String get fakeApiListenAddr_Ipfs;

  String get gatewayServerName_Ipfs;

  String get apiServerName_Ipfs;

  String get profile_Ipfs;

  String get autoMigrate_Ipfs;

  String get enableIpnsPubSub_Ipfs;

  String get enablePubSub_Ipfs;

  String get enableMultiplex_Ipfs;

  String get token_Ipfs;

  String get IpfsServer;

  String get name_IpfsServer;

  String get peer_IpfsServer;

  String get token_IpfsServer;

  String get FileServer;

  String get name_FileServer;

  String get zip_FileServer;

  String get redirect_FileServer;

  String get dev_FileServer;

  String get HttpProxyServer;

  String get name_HttpProxyServer;

  String get host_HttpProxyServer;

  String get keepAlive_HttpProxyServer;

  String get AdpRouter;

  String get rulesDirName_AdpRouter;

  String get blocked_AdpRouter;

  String get unblocked_AdpRouter;

  String get etcHostsIpAsBlocked_AdpRouter;

  String get dev_AdpRouter;

  String get IPNetRouter;

  String get ip_IPNetRouter;

  String get net_IPNetRouter;

  String get matched_IPNetRouter;

  String get unmatched_IPNetRouter;

  String get fileTest_IPNetRouter;

  String get RouterItem;

  String get name_RouterItem;

  String get adp_RouterItem;

  String get ipnet_RouterItem;

  String get Config;

  String get basic_Config;

  String get log_Config;

  String get ipfs_Config;

  String get ipfsServers_Config;

  String get fileServers_Config;

  String get httpProxyServers_Config;

  String get routers_Config;

  String get currencyXxx;

  String get currencyAll;

  String get currencyDzd;

  String get currencyArs;

  String get currencyAud;

  String get currencyBsd;

  String get currencyBhd;

  String get currencyBdt;

  String get currencyAmd;

  String get currencyBbd;

  String get currencyBmd;

  String get currencyBtn;

  String get currencyBob;

  String get currencyBwp;

  String get currencyBzd;

  String get currencySbd;

  String get currencyBnd;

  String get currencyMmk;

  String get currencyBif;

  String get currencyKhr;

  String get currencyCad;

  String get currencyCve;

  String get currencyKyd;

  String get currencyLkr;

  String get currencyClp;

  String get currencyCny;

  String get currencyCop;

  String get currencyKmf;

  String get currencyCrc;

  String get currencyHrk;

  String get currencyCup;

  String get currencyCzk;

  String get currencyDkk;

  String get currencyDop;

  String get currencySvc;

  String get currencyEtb;

  String get currencyErn;

  String get currencyFkp;

  String get currencyFjd;

  String get currencyDjf;

  String get currencyGmd;

  String get currencyGip;

  String get currencyGtq;

  String get currencyGnf;

  String get currencyGyd;

  String get currencyHtg;

  String get currencyHnl;

  String get currencyHkd;

  String get currencyHuf;

  String get currencyIsk;

  String get currencyInr;

  String get currencyIdr;

  String get currencyIrr;

  String get currencyIqd;

  String get currencyIls;

  String get currencyJmd;

  String get currencyJpy;

  String get currencyKzt;

  String get currencyJod;

  String get currencyKes;

  String get currencyKpw;

  String get currencyKrw;

  String get currencyKwd;

  String get currencyKgs;

  String get currencyLak;

  String get currencyLbp;

  String get currencyLsl;

  String get currencyLrd;

  String get currencyLyd;

  String get currencyMop;

  String get currencyMwk;

  String get currencyMyr;

  String get currencyMvr;

  String get currencyMur;

  String get currencyMxn;

  String get currencyMnt;

  String get currencyMdl;

  String get currencyMad;

  String get currencyOmr;

  String get currencyNad;

  String get currencyNpr;

  String get currencyAng;

  String get currencyAwg;

  String get currencyVuv;

  String get currencyNzd;

  String get currencyNio;

  String get currencyNgn;

  String get currencyNok;

  String get currencyPkr;

  String get currencyPab;

  String get currencyPgk;

  String get currencyPyg;

  String get currencyPen;

  String get currencyPhp;

  String get currencyQar;

  String get currencyRub;

  String get currencyRwf;

  String get currencyShp;

  String get currencySar;

  String get currencyScr;

  String get currencySll;

  String get currencySgd;

  String get currencyVnd;

  String get currencySos;

  String get currencyZar;

  String get currencySsp;

  String get currencySzl;

  String get currencySek;

  String get currencyChf;

  String get currencySyp;

  String get currencyThb;

  String get currencyTop;

  String get currencyTtd;

  String get currencyAed;

  String get currencyTnd;

  String get currencyUgx;

  String get currencyMkd;

  String get currencyEgp;

  String get currencyGbp;

  String get currencyTzs;

  String get currencyUsd;

  String get currencyUyu;

  String get currencyUzs;

  String get currencyWst;

  String get currencyYer;

  String get currencyTwd;

  String get currencyUyw;

  String get currencyVes;

  String get currencyMru;

  String get currencyStn;

  String get currencyCuc;

  String get currencyZwl;

  String get currencyByn;

  String get currencyTmt;

  String get currencyGhs;

  String get currencySdg;

  String get currencyUyi;

  String get currencyRsd;

  String get currencyMzn;

  String get currencyAzn;

  String get currencyRon;

  String get currencyChe;

  String get currencyChw;

  String get currencyTry;

  String get currencyXaf;

  String get currencyXcd;

  String get currencyXof;

  String get currencyXpf;

  String get currencyXba;

  String get currencyXbb;

  String get currencyXbc;

  String get currencyXbd;

  String get currencyXau;

  String get currencyXdr;

  String get currencyXag;

  String get currencyXpt;

  String get currencyXts;

  String get currencyXpd;

  String get currencyXua;

  String get currencyZmw;

  String get currencySrd;

  String get currencyMga;

  String get currencyCou;

  String get currencyAfn;

  String get currencyTjs;

  String get currencyAoa;

  String get currencyBgn;

  String get currencyCdf;

  String get currencyBam;

  String get currencyEur;

  String get currencyMxv;

  String get currencyUah;

  String get currencyGel;

  String get currencyBov;

  String get currencyPln;

  String get currencyBrl;

  String get currencyClf;

  String get currencyXsu;

  String get currencyUsn;
}

class AppLocalizationEn extends AppLocalization {
  const AppLocalizationEn();

  String get notificationChannelName => r'Hybrid';

  String get notificationChannelDesc => r'Keep hybrid always running';

  String get serviceTitle => r'Hybrid';

  String get nodeRunning => r'Node is running';

  String get nodeStopped => r'Node stopped';

  String get nodeError => r'Node stopped with error';

  String get appName => r'Hybrid';

  String get appDesc => r'Decentralized access anywhere.';

  String get home => r'Home';

  String get addNewOne => r'Add...';

  String get reorder => r'Reorder';

  String get dataview => r'View Data';

  String get configureBackAlertTitle => r'Alert';

  String get configureBackAlertContent =>
      r'Are you sure go back without save to stage.';

  String get configureBackAlertStay => r'Stay';

  String get configureBackAlertGoBack => r'Go back';

  String get configureBasicBindHint =>
      r'Address that should be set to proxy settings';

  String get configureBasicBindBadTcpAddr => r'Accept only tcp addresses';

  String get configureBasicFlushIntervalHint => r'ms';

  String get configureLogTargetHint =>
      r'"tcp://host:port?timeout=5s", file, sentryDSN or empty';

  String get ConfigTree => r'ConfigTree';

  String get version_ConfigTree => r'version';

  String get rootName_ConfigTree => r'rootName';

  String get rootPath_ConfigTree => r'rootPath';

  String get configName_ConfigTree => r'configName';

  String get configPath_ConfigTree => r'configPath';

  String get ipfsName_ConfigTree => r'ipfsName';

  String get ipfsPath_ConfigTree => r'ipfsPath';

  String get storeName_ConfigTree => r'storeName';

  String get storePath_ConfigTree => r'storePath';

  String get filesRootName_ConfigTree => r'filesRootName';

  String get filesRootPath_ConfigTree => r'filesRootPath';

  String get rulesRootName_ConfigTree => r'rulesRootName';

  String get rulesRootPath_ConfigTree => r'rulesRootPath';

  String get Basic => r'Basic';

  String get version_Basic => r'version';

  String get dev_Basic => r'dev';

  String get bind_Basic => r'bind';

  String get flushIntervalMs_Basic => r'flushIntervalMs';

  String get token_Basic => r'token';

  String get Log => r'Log';

  String get dev_Log => r'dev';

  String get level_Log => r'level';

  String get target_Log => r'target';

  String get Ipfs => r'Ipfs';

  String get fakeApiListenAddr_Ipfs => r'fakeApiListenAddr';

  String get gatewayServerName_Ipfs => r'gatewayServerName';

  String get apiServerName_Ipfs => r'apiServerName';

  String get profile_Ipfs => r'profile';

  String get autoMigrate_Ipfs => r'autoMigrate';

  String get enableIpnsPubSub_Ipfs => r'enableIpnsPubSub';

  String get enablePubSub_Ipfs => r'enablePubSub';

  String get enableMultiplex_Ipfs => r'enableMultiplex';

  String get token_Ipfs => r'token';

  String get IpfsServer => r'IpfsServer';

  String get name_IpfsServer => r'name';

  String get peer_IpfsServer => r'peer';

  String get token_IpfsServer => r'token';

  String get FileServer => r'FileServer';

  String get name_FileServer => r'name';

  String get zip_FileServer => r'zip';

  String get redirect_FileServer => r'redirect';

  String get dev_FileServer => r'dev';

  String get HttpProxyServer => r'HttpProxyServer';

  String get name_HttpProxyServer => r'name';

  String get host_HttpProxyServer => r'host';

  String get keepAlive_HttpProxyServer => r'keepAlive';

  String get AdpRouter => r'AdpRouter';

  String get rulesDirName_AdpRouter => r'rulesDirName';

  String get blocked_AdpRouter => r'blocked';

  String get unblocked_AdpRouter => r'unblocked';

  String get etcHostsIpAsBlocked_AdpRouter => r'etcHostsIpAsBlocked';

  String get dev_AdpRouter => r'dev';

  String get IPNetRouter => r'IPNetRouter';

  String get ip_IPNetRouter => r'ip';

  String get net_IPNetRouter => r'net';

  String get matched_IPNetRouter => r'matched';

  String get unmatched_IPNetRouter => r'unmatched';

  String get fileTest_IPNetRouter => r'fileTest';

  String get RouterItem => r'RouterItem';

  String get name_RouterItem => r'name';

  String get adp_RouterItem => r'adp';

  String get ipnet_RouterItem => r'ipnet';

  String get Config => r'Config';

  String get basic_Config => r'basic';

  String get log_Config => r'log';

  String get ipfs_Config => r'ipfs';

  String get ipfsServers_Config => r'ipfsServers';

  String get fileServers_Config => r'fileServers';

  String get httpProxyServers_Config => r'httpProxyServers';

  String get routers_Config => r'routers';

  String get currencyXxx =>
      r'The codes assigned for transactions where no currency is involved';

  String get currencyAll => r'Lek';

  String get currencyDzd => r'Algerian Dinar';

  String get currencyArs => r'Argentine Peso';

  String get currencyAud => r'Australian Dollar';

  String get currencyBsd => r'Bahamian Dollar';

  String get currencyBhd => r'Bahraini Dinar';

  String get currencyBdt => r'Taka';

  String get currencyAmd => r'Armenian Dram';

  String get currencyBbd => r'Barbados Dollar';

  String get currencyBmd => r'Bermudian Dollar';

  String get currencyBtn => r'Ngultrum';

  String get currencyBob => r'Boliviano';

  String get currencyBwp => r'Pula';

  String get currencyBzd => r'Belize Dollar';

  String get currencySbd => r'Solomon Islands Dollar';

  String get currencyBnd => r'Brunei Dollar';

  String get currencyMmk => r'Kyat';

  String get currencyBif => r'Burundi Franc';

  String get currencyKhr => r'Riel';

  String get currencyCad => r'Canadian Dollar';

  String get currencyCve => r'Cabo Verde Escudo';

  String get currencyKyd => r'Cayman Islands Dollar';

  String get currencyLkr => r'Sri Lanka Rupee';

  String get currencyClp => r'Chilean Peso';

  String get currencyCny => r'Yuan Renminbi';

  String get currencyCop => r'Colombian Peso';

  String get currencyKmf => r'Comorian Franc ';

  String get currencyCrc => r'Costa Rican Colon';

  String get currencyHrk => r'Kuna';

  String get currencyCup => r'Cuban Peso';

  String get currencyCzk => r'Czech Koruna';

  String get currencyDkk => r'Danish Krone';

  String get currencyDop => r'Dominican Peso';

  String get currencySvc => r'El Salvador Colon';

  String get currencyEtb => r'Ethiopian Birr';

  String get currencyErn => r'Nakfa';

  String get currencyFkp => r'Falkland Islands Pound';

  String get currencyFjd => r'Fiji Dollar';

  String get currencyDjf => r'Djibouti Franc';

  String get currencyGmd => r'Dalasi';

  String get currencyGip => r'Gibraltar Pound';

  String get currencyGtq => r'Quetzal';

  String get currencyGnf => r'Guinean Franc';

  String get currencyGyd => r'Guyana Dollar';

  String get currencyHtg => r'Gourde';

  String get currencyHnl => r'Lempira';

  String get currencyHkd => r'Hong Kong Dollar';

  String get currencyHuf => r'Forint';

  String get currencyIsk => r'Iceland Krona';

  String get currencyInr => r'Indian Rupee';

  String get currencyIdr => r'Rupiah';

  String get currencyIrr => r'Iranian Rial';

  String get currencyIqd => r'Iraqi Dinar';

  String get currencyIls => r'New Israeli Sheqel';

  String get currencyJmd => r'Jamaican Dollar';

  String get currencyJpy => r'Yen';

  String get currencyKzt => r'Tenge';

  String get currencyJod => r'Jordanian Dinar';

  String get currencyKes => r'Kenyan Shilling';

  String get currencyKpw => r'North Korean Won';

  String get currencyKrw => r'Won';

  String get currencyKwd => r'Kuwaiti Dinar';

  String get currencyKgs => r'Som';

  String get currencyLak => r'Lao Kip';

  String get currencyLbp => r'Lebanese Pound';

  String get currencyLsl => r'Loti';

  String get currencyLrd => r'Liberian Dollar';

  String get currencyLyd => r'Libyan Dinar';

  String get currencyMop => r'Pataca';

  String get currencyMwk => r'Malawi Kwacha';

  String get currencyMyr => r'Malaysian Ringgit';

  String get currencyMvr => r'Rufiyaa';

  String get currencyMur => r'Mauritius Rupee';

  String get currencyMxn => r'Mexican Peso';

  String get currencyMnt => r'Tugrik';

  String get currencyMdl => r'Moldovan Leu';

  String get currencyMad => r'Moroccan Dirham';

  String get currencyOmr => r'Rial Omani';

  String get currencyNad => r'Namibia Dollar';

  String get currencyNpr => r'Nepalese Rupee';

  String get currencyAng => r'Netherlands Antillean Guilder';

  String get currencyAwg => r'Aruban Florin';

  String get currencyVuv => r'Vatu';

  String get currencyNzd => r'New Zealand Dollar';

  String get currencyNio => r'Cordoba Oro';

  String get currencyNgn => r'Naira';

  String get currencyNok => r'Norwegian Krone';

  String get currencyPkr => r'Pakistan Rupee';

  String get currencyPab => r'Balboa';

  String get currencyPgk => r'Kina';

  String get currencyPyg => r'Guarani';

  String get currencyPen => r'Sol';

  String get currencyPhp => r'Philippine Peso';

  String get currencyQar => r'Qatari Rial';

  String get currencyRub => r'Russian Ruble';

  String get currencyRwf => r'Rwanda Franc';

  String get currencyShp => r'Saint Helena Pound';

  String get currencySar => r'Saudi Riyal';

  String get currencyScr => r'Seychelles Rupee';

  String get currencySll => r'Leone';

  String get currencySgd => r'Singapore Dollar';

  String get currencyVnd => r'Dong';

  String get currencySos => r'Somali Shilling';

  String get currencyZar => r'Rand';

  String get currencySsp => r'South Sudanese Pound';

  String get currencySzl => r'Lilangeni';

  String get currencySek => r'Swedish Krona';

  String get currencyChf => r'Swiss Franc';

  String get currencySyp => r'Syrian Pound';

  String get currencyThb => r'Baht';

  String get currencyTop => r'Pa’anga';

  String get currencyTtd => r'Trinidad and Tobago Dollar';

  String get currencyAed => r'UAE Dirham';

  String get currencyTnd => r'Tunisian Dinar';

  String get currencyUgx => r'Uganda Shilling';

  String get currencyMkd => r'Denar';

  String get currencyEgp => r'Egyptian Pound';

  String get currencyGbp => r'Pound Sterling';

  String get currencyTzs => r'Tanzanian Shilling';

  String get currencyUsd => r'US Dollar';

  String get currencyUyu => r'Peso Uruguayo';

  String get currencyUzs => r'Uzbekistan Sum';

  String get currencyWst => r'Tala';

  String get currencyYer => r'Yemeni Rial';

  String get currencyTwd => r'New Taiwan Dollar';

  String get currencyUyw => r'Unidad Previsional';

  String get currencyVes => r'Bolívar Soberano';

  String get currencyMru => r'Ouguiya';

  String get currencyStn => r'Dobra';

  String get currencyCuc => r'Peso Convertible';

  String get currencyZwl => r'Zimbabwe Dollar';

  String get currencyByn => r'Belarusian Ruble';

  String get currencyTmt => r'Turkmenistan New Manat';

  String get currencyGhs => r'Ghana Cedi';

  String get currencySdg => r'Sudanese Pound';

  String get currencyUyi => r'Uruguay Peso en Unidades Indexadas (UI)';

  String get currencyRsd => r'Serbian Dinar';

  String get currencyMzn => r'Mozambique Metical';

  String get currencyAzn => r'Azerbaijan Manat';

  String get currencyRon => r'Romanian Leu';

  String get currencyChe => r'WIR Euro';

  String get currencyChw => r'WIR Franc';

  String get currencyTry => r'Turkish Lira';

  String get currencyXaf => r'CFA Franc BEAC';

  String get currencyXcd => r'East Caribbean Dollar';

  String get currencyXof => r'CFA Franc BCEAO';

  String get currencyXpf => r'CFP Franc';

  String get currencyXba =>
      r'Bond Markets Unit European Composite Unit (EURCO)';

  String get currencyXbb =>
      r'Bond Markets Unit European Monetary Unit (E.M.U.-6)';

  String get currencyXbc =>
      r'Bond Markets Unit European Unit of Account 9 (E.U.A.-9)';

  String get currencyXbd =>
      r'Bond Markets Unit European Unit of Account 17 (E.U.A.-17)';

  String get currencyXau => r'Gold';

  String get currencyXdr => r'SDR (Special Drawing Right)';

  String get currencyXag => r'Silver';

  String get currencyXpt => r'Platinum';

  String get currencyXts => r'Codes specifically reserved for testing purposes';

  String get currencyXpd => r'Palladium';

  String get currencyXua => r'ADB Unit of Account';

  String get currencyZmw => r'Zambian Kwacha';

  String get currencySrd => r'Surinam Dollar';

  String get currencyMga => r'Malagasy Ariary';

  String get currencyCou => r'Unidad de Valor Real';

  String get currencyAfn => r'Afghani';

  String get currencyTjs => r'Somoni';

  String get currencyAoa => r'Kwanza';

  String get currencyBgn => r'Bulgarian Lev';

  String get currencyCdf => r'Congolese Franc';

  String get currencyBam => r'Convertible Mark';

  String get currencyEur => r'Euro';

  String get currencyMxv => r'Mexican Unidad de Inversion (UDI)';

  String get currencyUah => r'Hryvnia';

  String get currencyGel => r'Lari';

  String get currencyBov => r'Mvdol';

  String get currencyPln => r'Zloty';

  String get currencyBrl => r'Brazilian Real';

  String get currencyClf => r'Unidad de Fomento';

  String get currencyXsu => r'Sucre';

  String get currencyUsn => r'US Dollar (Next day)';
}

class AppLocalizationAs extends AppLocalization {
  const AppLocalizationAs();

  String get notificationChannelName => r'Hybrid';

  String get notificationChannelDesc => r'Keep hybrid always running';

  String get serviceTitle => r'Hybrid';

  String get nodeRunning => r'Node is running';

  String get nodeStopped => r'Node stopped';

  String get nodeError => r'Node stopped with error';

  String get appName => r'Hybrid';

  String get appDesc => r'Decentralized access anywhere.';

  String get home => r'Home';

  String get addNewOne => r'Add...';

  String get reorder => r'Reorder';

  String get dataview => r'View Data';

  String get configureBackAlertTitle => r'Alert';

  String get configureBackAlertContent =>
      r'Are you sure go back without save to stage.';

  String get configureBackAlertStay => r'Stay';

  String get configureBackAlertGoBack => r'Go back';

  String get configureBasicBindHint =>
      r'Address that should be set to proxy settings';

  String get configureBasicBindBadTcpAddr => r'Accept only tcp addresses';

  String get configureBasicFlushIntervalHint => r'ms';

  String get configureLogTargetHint =>
      r'"tcp://host:port?timeout=5s", file, sentryDSN or empty';

  String get ConfigTree => r'ConfigTree';

  String get version_ConfigTree => r'version';

  String get rootName_ConfigTree => r'rootName';

  String get rootPath_ConfigTree => r'rootPath';

  String get configName_ConfigTree => r'configName';

  String get configPath_ConfigTree => r'configPath';

  String get ipfsName_ConfigTree => r'ipfsName';

  String get ipfsPath_ConfigTree => r'ipfsPath';

  String get storeName_ConfigTree => r'storeName';

  String get storePath_ConfigTree => r'storePath';

  String get filesRootName_ConfigTree => r'filesRootName';

  String get filesRootPath_ConfigTree => r'filesRootPath';

  String get rulesRootName_ConfigTree => r'rulesRootName';

  String get rulesRootPath_ConfigTree => r'rulesRootPath';

  String get Basic => r'Basic';

  String get version_Basic => r'version';

  String get dev_Basic => r'dev';

  String get bind_Basic => r'bind';

  String get flushIntervalMs_Basic => r'flushIntervalMs';

  String get token_Basic => r'token';

  String get Log => r'Log';

  String get dev_Log => r'dev';

  String get level_Log => r'level';

  String get target_Log => r'target';

  String get Ipfs => r'Ipfs';

  String get fakeApiListenAddr_Ipfs => r'fakeApiListenAddr';

  String get gatewayServerName_Ipfs => r'gatewayServerName';

  String get apiServerName_Ipfs => r'apiServerName';

  String get profile_Ipfs => r'profile';

  String get autoMigrate_Ipfs => r'autoMigrate';

  String get enableIpnsPubSub_Ipfs => r'enableIpnsPubSub';

  String get enablePubSub_Ipfs => r'enablePubSub';

  String get enableMultiplex_Ipfs => r'enableMultiplex';

  String get token_Ipfs => r'token';

  String get IpfsServer => r'IpfsServer';

  String get name_IpfsServer => r'name';

  String get peer_IpfsServer => r'peer';

  String get token_IpfsServer => r'token';

  String get FileServer => r'FileServer';

  String get name_FileServer => r'name';

  String get zip_FileServer => r'zip';

  String get redirect_FileServer => r'redirect';

  String get dev_FileServer => r'dev';

  String get HttpProxyServer => r'HttpProxyServer';

  String get name_HttpProxyServer => r'name';

  String get host_HttpProxyServer => r'host';

  String get keepAlive_HttpProxyServer => r'keepAlive';

  String get AdpRouter => r'AdpRouter';

  String get rulesDirName_AdpRouter => r'rulesDirName';

  String get blocked_AdpRouter => r'blocked';

  String get unblocked_AdpRouter => r'unblocked';

  String get etcHostsIpAsBlocked_AdpRouter => r'etcHostsIpAsBlocked';

  String get dev_AdpRouter => r'dev';

  String get IPNetRouter => r'IPNetRouter';

  String get ip_IPNetRouter => r'ip';

  String get net_IPNetRouter => r'net';

  String get matched_IPNetRouter => r'matched';

  String get unmatched_IPNetRouter => r'unmatched';

  String get fileTest_IPNetRouter => r'fileTest';

  String get RouterItem => r'RouterItem';

  String get name_RouterItem => r'name';

  String get adp_RouterItem => r'adp';

  String get ipnet_RouterItem => r'ipnet';

  String get Config => r'Config';

  String get basic_Config => r'basic';

  String get log_Config => r'log';

  String get ipfs_Config => r'ipfs';

  String get ipfsServers_Config => r'ipfsServers';

  String get fileServers_Config => r'fileServers';

  String get httpProxyServers_Config => r'httpProxyServers';

  String get routers_Config => r'routers';

  String get currencyXxx =>
      r'The codes assigned for transactions where no currency is involved';

  String get currencyAll => r'Lek';

  String get currencyDzd => r'Algerian Dinar';

  String get currencyArs => r'Argentine Peso';

  String get currencyAud => r'Australian Dollar';

  String get currencyBsd => r'Bahamian Dollar';

  String get currencyBhd => r'Bahraini Dinar';

  String get currencyBdt => r'Taka';

  String get currencyAmd => r'Armenian Dram';

  String get currencyBbd => r'Barbados Dollar';

  String get currencyBmd => r'Bermudian Dollar';

  String get currencyBtn => r'Ngultrum';

  String get currencyBob => r'Boliviano';

  String get currencyBwp => r'Pula';

  String get currencyBzd => r'Belize Dollar';

  String get currencySbd => r'Solomon Islands Dollar';

  String get currencyBnd => r'Brunei Dollar';

  String get currencyMmk => r'Kyat';

  String get currencyBif => r'Burundi Franc';

  String get currencyKhr => r'Riel';

  String get currencyCad => r'Canadian Dollar';

  String get currencyCve => r'Cabo Verde Escudo';

  String get currencyKyd => r'Cayman Islands Dollar';

  String get currencyLkr => r'Sri Lanka Rupee';

  String get currencyClp => r'Chilean Peso';

  String get currencyCny => r'Yuan Renminbi';

  String get currencyCop => r'Colombian Peso';

  String get currencyKmf => r'Comorian Franc ';

  String get currencyCrc => r'Costa Rican Colon';

  String get currencyHrk => r'Kuna';

  String get currencyCup => r'Cuban Peso';

  String get currencyCzk => r'Czech Koruna';

  String get currencyDkk => r'Danish Krone';

  String get currencyDop => r'Dominican Peso';

  String get currencySvc => r'El Salvador Colon';

  String get currencyEtb => r'Ethiopian Birr';

  String get currencyErn => r'Nakfa';

  String get currencyFkp => r'Falkland Islands Pound';

  String get currencyFjd => r'Fiji Dollar';

  String get currencyDjf => r'Djibouti Franc';

  String get currencyGmd => r'Dalasi';

  String get currencyGip => r'Gibraltar Pound';

  String get currencyGtq => r'Quetzal';

  String get currencyGnf => r'Guinean Franc';

  String get currencyGyd => r'Guyana Dollar';

  String get currencyHtg => r'Gourde';

  String get currencyHnl => r'Lempira';

  String get currencyHkd => r'Hong Kong Dollar';

  String get currencyHuf => r'Forint';

  String get currencyIsk => r'Iceland Krona';

  String get currencyInr => r'Indian Rupee';

  String get currencyIdr => r'Rupiah';

  String get currencyIrr => r'Iranian Rial';

  String get currencyIqd => r'Iraqi Dinar';

  String get currencyIls => r'New Israeli Sheqel';

  String get currencyJmd => r'Jamaican Dollar';

  String get currencyJpy => r'Yen';

  String get currencyKzt => r'Tenge';

  String get currencyJod => r'Jordanian Dinar';

  String get currencyKes => r'Kenyan Shilling';

  String get currencyKpw => r'North Korean Won';

  String get currencyKrw => r'Won';

  String get currencyKwd => r'Kuwaiti Dinar';

  String get currencyKgs => r'Som';

  String get currencyLak => r'Lao Kip';

  String get currencyLbp => r'Lebanese Pound';

  String get currencyLsl => r'Loti';

  String get currencyLrd => r'Liberian Dollar';

  String get currencyLyd => r'Libyan Dinar';

  String get currencyMop => r'Pataca';

  String get currencyMwk => r'Malawi Kwacha';

  String get currencyMyr => r'Malaysian Ringgit';

  String get currencyMvr => r'Rufiyaa';

  String get currencyMur => r'Mauritius Rupee';

  String get currencyMxn => r'Mexican Peso';

  String get currencyMnt => r'Tugrik';

  String get currencyMdl => r'Moldovan Leu';

  String get currencyMad => r'Moroccan Dirham';

  String get currencyOmr => r'Rial Omani';

  String get currencyNad => r'Namibia Dollar';

  String get currencyNpr => r'Nepalese Rupee';

  String get currencyAng => r'Netherlands Antillean Guilder';

  String get currencyAwg => r'Aruban Florin';

  String get currencyVuv => r'Vatu';

  String get currencyNzd => r'New Zealand Dollar';

  String get currencyNio => r'Cordoba Oro';

  String get currencyNgn => r'Naira';

  String get currencyNok => r'Norwegian Krone';

  String get currencyPkr => r'Pakistan Rupee';

  String get currencyPab => r'Balboa';

  String get currencyPgk => r'Kina';

  String get currencyPyg => r'Guarani';

  String get currencyPen => r'Sol';

  String get currencyPhp => r'Philippine Peso';

  String get currencyQar => r'Qatari Rial';

  String get currencyRub => r'Russian Ruble';

  String get currencyRwf => r'Rwanda Franc';

  String get currencyShp => r'Saint Helena Pound';

  String get currencySar => r'Saudi Riyal';

  String get currencyScr => r'Seychelles Rupee';

  String get currencySll => r'Leone';

  String get currencySgd => r'Singapore Dollar';

  String get currencyVnd => r'Dong';

  String get currencySos => r'Somali Shilling';

  String get currencyZar => r'Rand';

  String get currencySsp => r'South Sudanese Pound';

  String get currencySzl => r'Lilangeni';

  String get currencySek => r'Swedish Krona';

  String get currencyChf => r'Swiss Franc';

  String get currencySyp => r'Syrian Pound';

  String get currencyThb => r'Baht';

  String get currencyTop => r'Pa’anga';

  String get currencyTtd => r'Trinidad and Tobago Dollar';

  String get currencyAed => r'UAE Dirham';

  String get currencyTnd => r'Tunisian Dinar';

  String get currencyUgx => r'Uganda Shilling';

  String get currencyMkd => r'Denar';

  String get currencyEgp => r'Egyptian Pound';

  String get currencyGbp => r'Pound Sterling';

  String get currencyTzs => r'Tanzanian Shilling';

  String get currencyUsd => r'US Dollar';

  String get currencyUyu => r'Peso Uruguayo';

  String get currencyUzs => r'Uzbekistan Sum';

  String get currencyWst => r'Tala';

  String get currencyYer => r'Yemeni Rial';

  String get currencyTwd => r'New Taiwan Dollar';

  String get currencyUyw => r'Unidad Previsional';

  String get currencyVes => r'Bolívar Soberano';

  String get currencyMru => r'Ouguiya';

  String get currencyStn => r'Dobra';

  String get currencyCuc => r'Peso Convertible';

  String get currencyZwl => r'Zimbabwe Dollar';

  String get currencyByn => r'Belarusian Ruble';

  String get currencyTmt => r'Turkmenistan New Manat';

  String get currencyGhs => r'Ghana Cedi';

  String get currencySdg => r'Sudanese Pound';

  String get currencyUyi => r'Uruguay Peso en Unidades Indexadas (UI)';

  String get currencyRsd => r'Serbian Dinar';

  String get currencyMzn => r'Mozambique Metical';

  String get currencyAzn => r'Azerbaijan Manat';

  String get currencyRon => r'Romanian Leu';

  String get currencyChe => r'WIR Euro';

  String get currencyChw => r'WIR Franc';

  String get currencyTry => r'Turkish Lira';

  String get currencyXaf => r'CFA Franc BEAC';

  String get currencyXcd => r'East Caribbean Dollar';

  String get currencyXof => r'CFA Franc BCEAO';

  String get currencyXpf => r'CFP Franc';

  String get currencyXba =>
      r'Bond Markets Unit European Composite Unit (EURCO)';

  String get currencyXbb =>
      r'Bond Markets Unit European Monetary Unit (E.M.U.-6)';

  String get currencyXbc =>
      r'Bond Markets Unit European Unit of Account 9 (E.U.A.-9)';

  String get currencyXbd =>
      r'Bond Markets Unit European Unit of Account 17 (E.U.A.-17)';

  String get currencyXau => r'Gold';

  String get currencyXdr => r'SDR (Special Drawing Right)';

  String get currencyXag => r'Silver';

  String get currencyXpt => r'Platinum';

  String get currencyXts => r'Codes specifically reserved for testing purposes';

  String get currencyXpd => r'Palladium';

  String get currencyXua => r'ADB Unit of Account';

  String get currencyZmw => r'Zambian Kwacha';

  String get currencySrd => r'Surinam Dollar';

  String get currencyMga => r'Malagasy Ariary';

  String get currencyCou => r'Unidad de Valor Real';

  String get currencyAfn => r'Afghani';

  String get currencyTjs => r'Somoni';

  String get currencyAoa => r'Kwanza';

  String get currencyBgn => r'Bulgarian Lev';

  String get currencyCdf => r'Congolese Franc';

  String get currencyBam => r'Convertible Mark';

  String get currencyEur => r'Euro';

  String get currencyMxv => r'Mexican Unidad de Inversion (UDI)';

  String get currencyUah => r'Hryvnia';

  String get currencyGel => r'Lari';

  String get currencyBov => r'Mvdol';

  String get currencyPln => r'Zloty';

  String get currencyBrl => r'Brazilian Real';

  String get currencyClf => r'Unidad de Fomento';

  String get currencyXsu => r'Sucre';

  String get currencyUsn => r'US Dollar (Next day)';
}

class AppLocalizationZhHans extends AppLocalization {
  const AppLocalizationZhHans();

  String get notificationChannelName => r'混合动力';

  String get notificationChannelDesc => r'保持混合动力始终运行';

  String get serviceTitle => r'混合动力';

  String get nodeRunning => r'节点正在运行';

  String get nodeStopped => r'节点已停止';

  String get nodeError => r'节点因错误而停止';

  String get appName => r'混合动力';

  String get appDesc => r'在任何地方。';

  String get home => r'主页';

  String get addNewOne => r'新建...';

  String get reorder => r'重新排序';

  String get dataview => r'查看数据';

  String get configureBackAlertTitle => r'警报';

  String get configureBackAlertContent => r'你确定不暂存吗?';

  String get configureBackAlertStay => r'留下';

  String get configureBackAlertGoBack => r'返回';

  String get configureBasicBindHint => r'应设置为代理设置的地址';

  String get configureBasicBindBadTcpAddr => r'只接受tcp地址';

  String get configureBasicFlushIntervalHint => r'毫秒';

  String get configureLogTargetHint =>
      r'“tcp：// host：port？timeout = 5s”，file，sentryDSN或为空';

  String get ConfigTree => r'配置目录';

  String get version_ConfigTree => r'版本';

  String get rootName_ConfigTree => r'root目录名';

  String get rootPath_ConfigTree => r'root路径';

  String get configName_ConfigTree => r'配置名称';

  String get configPath_ConfigTree => r'配置路径';

  String get ipfsName_ConfigTree => r'ipfs名称';

  String get ipfsPath_ConfigTree => r'ipfs路径';

  String get storeName_ConfigTree => r'存储目录名';

  String get storePath_ConfigTree => r'存储路径';

  String get filesRootName_ConfigTree => r'filesRootName';

  String get filesRootPath_ConfigTree => r'filesRootPath';

  String get rulesRootName_ConfigTree => r'rulesRootName';

  String get rulesRootPath_ConfigTree => r'rulesRootPath';

  String get Basic => r'基本';

  String get version_Basic => r'版本';

  String get dev_Basic => r'开发';

  String get bind_Basic => r'绑定地址';

  String get flushIntervalMs_Basic => r'flushIntervalMs';

  String get token_Basic => r'代币';

  String get Log => r'日志';

  String get dev_Log => r'开发';

  String get level_Log => r'水平';

  String get target_Log => r'目标';

  String get Ipfs => r'IPFS';

  String get fakeApiListenAddr_Ipfs => r'fakeApiListenAddr';

  String get gatewayServerName_Ipfs => r'gatewayServerName';

  String get apiServerName_Ipfs => r'apiServerName';

  String get profile_Ipfs => r'profile';

  String get autoMigrate_Ipfs => r'autoMigrate';

  String get enableIpnsPubSub_Ipfs => r'enableIpnsPubSub';

  String get enablePubSub_Ipfs => r'enablePubSub';

  String get enableMultiplex_Ipfs => r'enableMultiplex';

  String get token_Ipfs => r'令牌';

  String get IpfsServer => r'IpfsServer';

  String get name_IpfsServer => r'名称';

  String get peer_IpfsServer => r'对点';

  String get token_IpfsServer => r'令牌';

  String get FileServer => r'文件服务器';

  String get name_FileServer => r'名称';

  String get zip_FileServer => r'zip文件';

  String get redirect_FileServer => r'重定向';

  String get dev_FileServer => r'开发';

  String get HttpProxyServer => r'HttpProxyServer';

  String get name_HttpProxyServer => r'名称';

  String get host_HttpProxyServer => r'主机';

  String get keepAlive_HttpProxyServer => r'keepAlive';

  String get AdpRouter => r'AdpRouter';

  String get rulesDirName_AdpRouter => r'rulesDirName';

  String get blocked_AdpRouter => r'受阻';

  String get unblocked_AdpRouter => r'畅通';

  String get etcHostsIpAsBlocked_AdpRouter => r'etcHostsIpAsBlocked';

  String get dev_AdpRouter => r'开发';

  String get IPNetRouter => r'IPNetRouter';

  String get ip_IPNetRouter => r'IP';

  String get net_IPNetRouter => r'网络';

  String get matched_IPNetRouter => r'匹配';

  String get unmatched_IPNetRouter => r'未匹配';

  String get fileTest_IPNetRouter => r'fileTest';

  String get RouterItem => r'RouterItem';

  String get name_RouterItem => r'名称';

  String get adp_RouterItem => r'ADP';

  String get ipnet_RouterItem => r'IPNET';

  String get Config => r'配置';

  String get basic_Config => r'基本';

  String get log_Config => r'日志';

  String get ipfs_Config => r'ipfs';

  String get ipfsServers_Config => r'ipfsServers';

  String get fileServers_Config => r'文件服务器';

  String get httpProxyServers_Config => r'httpProxyServers';

  String get routers_Config => r'路由器';

  String get currencyXxx => r'分配给不涉及货币的交易的代码';

  String get currencyAll => r'沥';

  String get currencyDzd => r'阿尔及利亚第纳尔';

  String get currencyArs => r'阿根廷比索';

  String get currencyAud => r'澳元';

  String get currencyBsd => r'巴哈马元';

  String get currencyBhd => r'巴林第纳尔';

  String get currencyBdt => r'塔卡';

  String get currencyAmd => r'亚美尼亚德拉姆';

  String get currencyBbd => r'巴巴多斯元';

  String get currencyBmd => r'百慕大元';

  String get currencyBtn => r'努尔特鲁姆';

  String get currencyBob => r'诺';

  String get currencyBwp => r'普拉';

  String get currencyBzd => r'伯利兹元';

  String get currencySbd => r'所罗门群岛元';

  String get currencyBnd => r'文莱元';

  String get currencyMmk => r'缅元';

  String get currencyBif => r'布隆迪法郎';

  String get currencyKhr => r'瑞尔';

  String get currencyCad => r'加元';

  String get currencyCve => r'Cabo Verde Escudo';

  String get currencyKyd => r'开曼群岛元';

  String get currencyLkr => r'斯里兰卡卢比';

  String get currencyClp => r'智利比索';

  String get currencyCny => r'人民币';

  String get currencyCop => r'哥伦比亚比索';

  String get currencyKmf => r'科摩罗法郎';

  String get currencyCrc => r'哥斯达黎加科隆';

  String get currencyHrk => r'库纳';

  String get currencyCup => r'古巴比索';

  String get currencyCzk => r'捷克克朗';

  String get currencyDkk => r'丹麦克朗';

  String get currencyDop => r'多米尼加比索';

  String get currencySvc => r'萨尔瓦多科隆';

  String get currencyEtb => r'埃塞俄比亚比尔';

  String get currencyErn => r'纳克法';

  String get currencyFkp => r'福克兰群岛磅';

  String get currencyFjd => r'斐济元';

  String get currencyDjf => r'吉布提法郎';

  String get currencyGmd => r'达拉斯';

  String get currencyGip => r'直布罗陀庞德';

  String get currencyGtq => r'长尾的美鸟';

  String get currencyGnf => r'几内亚法郎';

  String get currencyGyd => r'圭亚那元';

  String get currencyHtg => r'古德';

  String get currencyHnl => r'伦皮拉';

  String get currencyHkd => r'港币';

  String get currencyHuf => r'福林';

  String get currencyIsk => r'冰岛克朗';

  String get currencyInr => r'印度卢比';

  String get currencyIdr => r'印尼盾';

  String get currencyIrr => r'伊朗里亚尔';

  String get currencyIqd => r'伊拉克第纳尔';

  String get currencyIls => r'新的以色列谢克尔';

  String get currencyJmd => r'牙买加元';

  String get currencyJpy => r'日元';

  String get currencyKzt => r'坚戈';

  String get currencyJod => r'约旦第纳尔';

  String get currencyKes => r'肯尼亚先令';

  String get currencyKpw => r'朝鲜元';

  String get currencyKrw => r'韩元';

  String get currencyKwd => r'科威特第纳尔';

  String get currencyKgs => r'索姆';

  String get currencyLak => r'老基普';

  String get currencyLbp => r'黎巴嫩镑';

  String get currencyLsl => r'洛蒂';

  String get currencyLrd => r'利比里亚元';

  String get currencyLyd => r'利比亚第纳尔';

  String get currencyMop => r'帕塔卡';

  String get currencyMwk => r'马拉维克瓦查';

  String get currencyMyr => r'马来西亚林吉特';

  String get currencyMvr => r'拉菲亚';

  String get currencyMur => r'毛里求斯卢比';

  String get currencyMxn => r'墨西哥比索';

  String get currencyMnt => r'图格里克';

  String get currencyMdl => r'摩尔多瓦列伊';

  String get currencyMad => r'摩洛哥迪拉姆';

  String get currencyOmr => r'里亚尔阿曼';

  String get currencyNad => r'纳米比亚元';

  String get currencyNpr => r'尼泊尔卢比';

  String get currencyAng => r'荷属安的列斯盾';

  String get currencyAwg => r'阿鲁巴弗罗林';

  String get currencyVuv => r'瓦图';

  String get currencyNzd => r'新西兰元';

  String get currencyNio => r'科尔多瓦奥罗';

  String get currencyNgn => r'奈拉';

  String get currencyNok => r'挪威克朗';

  String get currencyPkr => r'巴基斯坦卢比';

  String get currencyPab => r'巴尔博亚';

  String get currencyPgk => r'基那';

  String get currencyPyg => r'瓜拉尼';

  String get currencyPen => r'索尔';

  String get currencyPhp => r'菲律宾比索';

  String get currencyQar => r'卡塔尔里亚尔';

  String get currencyRub => r'俄罗斯卢布';

  String get currencyRwf => r'卢旺达法郎';

  String get currencyShp => r'圣赫勒拿磅';

  String get currencySar => r'沙特里亚尔';

  String get currencyScr => r'塞舌尔卢比';

  String get currencySll => r'塞拉利昂';

  String get currencySgd => r'新加坡元';

  String get currencyVnd => r'董';

  String get currencySos => r'索马里先令';

  String get currencyZar => r'兰德';

  String get currencySsp => r'南苏丹镑';

  String get currencySzl => r'吉尼';

  String get currencySek => r'瑞典克朗';

  String get currencyChf => r'瑞士法郎';

  String get currencySyp => r'叙利亚镑';

  String get currencyThb => r'铢';

  String get currencyTop => r'加潘加';

  String get currencyTtd => r'特立尼达和多巴哥元';

  String get currencyAed => r'阿联酋迪拉姆';

  String get currencyTnd => r'突尼斯第纳尔';

  String get currencyUgx => r'乌干达先令';

  String get currencyMkd => r'代纳尔';

  String get currencyEgp => r'埃及镑';

  String get currencyGbp => r'英镑';

  String get currencyTzs => r'坦桑尼亚先令';

  String get currencyUsd => r'美元';

  String get currencyUyu => r'比索乌拉圭';

  String get currencyUzs => r'乌兹别克斯坦Sum';

  String get currencyWst => r'塔拉';

  String get currencyYer => r'也门里亚尔';

  String get currencyTwd => r'新台币';

  String get currencyUyw => r'Unidad Previsional';

  String get currencyVes => r'玻利瓦尔索贝拉诺';

  String get currencyMru => r'乌吉亚';

  String get currencyStn => r'多布拉';

  String get currencyCuc => r'比索敞篷车';

  String get currencyZwl => r'津巴布韦元';

  String get currencyByn => r'白俄罗斯卢布';

  String get currencyTmt => r'土库曼斯坦新马纳特';

  String get currencyGhs => r'加纳塞地';

  String get currencySdg => r'苏丹镑';

  String get currencyUyi => r'Uruguay Peso en Unidades Indexadas（UI）';

  String get currencyRsd => r'塞尔维亚第纳尔';

  String get currencyMzn => r'莫桑比克Metical';

  String get currencyAzn => r'阿塞拜疆马纳特';

  String get currencyRon => r'罗马尼亚列伊';

  String get currencyChe => r'WIR欧元';

  String get currencyChw => r'WIR Franc';

  String get currencyTry => r'土耳其里拉';

  String get currencyXaf => r'CFA Franc BEAC';

  String get currencyXcd => r'东加勒比元';

  String get currencyXof => r'CFA Franc BCEAO';

  String get currencyXpf => r'CFP法郎';

  String get currencyXba => r'债券市场单位欧洲综合股（EURCO）';

  String get currencyXbb => r'债券市场单位欧洲货币单位（EMU-6）';

  String get currencyXbc => r'债券市场单位欧洲账户9（EUA-9）';

  String get currencyXbd => r'债券市场单位欧洲账户17（EUA-17）';

  String get currencyXau => r'金';

  String get currencyXdr => r'SDR（特别提款权）';

  String get currencyXag => r'银';

  String get currencyXpt => r'铂';

  String get currencyXts => r'代码专门用于测试目的';

  String get currencyXpd => r'钯';

  String get currencyXua => r'亚行帐户单位';

  String get currencyZmw => r'赞比亚克瓦查';

  String get currencySrd => r'苏里南元';

  String get currencyMga => r'马达加斯加阿里亚里';

  String get currencyCou => r'Unidad de Valor Real';

  String get currencyAfn => r'阿富汗';

  String get currencyTjs => r'索莫尼';

  String get currencyAoa => r'宽扎';

  String get currencyBgn => r'保加利亚列弗';

  String get currencyCdf => r'刚果法郎';

  String get currencyBam => r'可兑换马克';

  String get currencyEur => r'欧元';

  String get currencyMxv => r'墨西哥Unidad de Inversion（UDI）';

  String get currencyUah => r'赫夫纳';

  String get currencyGel => r'拉里';

  String get currencyBov => r'Mvdol';

  String get currencyPln => r'兹罗提';

  String get currencyBrl => r'巴西雷亚尔';

  String get currencyClf => r'Unidad de Fomento';

  String get currencyXsu => r'苏克雷';

  String get currencyUsn => r'美元（次日）';
}
